Repository nextcloud/mail, pull requests merged in 2018-12, with the labels that each got.

#1223 Change typeface of HTML mails to Nunito
  js/views/messageview.js
Labels: 3. to review, blocked, design, enhancement

#1185 Adjust redirect page design
  templates/redirect.php
Labels: 3. to review, bug, design

#1360 Add default labels to issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: 3. to review, technical debt

#1407 Fix navigation on left/right arrow in focussed input and textareas
  src/main.js
Labels: 3. to review, bug, regression

#1409 Fix awaiting of local attachment upload before sending a message
  src/components/Composer.vue
  src/components/ComposerAttachments.vue
Labels: 3. to review, bug, regression
