Repository nextcloud/mail, pull requests merged in 2018-09, with the labels that each got.

#1073 Add Moment component
  js/components/MessageListItem.vue
  js/components/Moment.vue
  package-lock.json
  package.json
Labels: 3. to review, enhancement

#1074 Add simple Vue avatar component
  js/components/Avatar.vue
  js/components/MessageListItem.vue
Labels: 3. to review

#1075 Add basic message details component
  js/components/Address.vue
  js/components/AddressList.vue
  js/components/FolderContent.vue
  js/components/Message.vue
  js/components/MessageHTMLBody.vue
  js/components/MessagePlainTextBody.vue
  js/directives/tooltip.js
  js/main.js
Labels: 2. developing

#1076 Use v-tooltip instead of jQuery plugin
  js/components/Address.vue
  js/directives/tooltip.js
  js/main.js
  package-lock.json
  package.json
Labels: 3. to review

#1080 Fix content details class
  js/components/Message.vue
Labels: 3. to review, bug

#1077 Add Vue-based composer component
  .babelrc
  appinfo/info.xml
  js/components/Composer.vue
  js/components/Message.vue
  js/tests/e2e/custom-assertions/elementCount.js
  js/tests/e2e/specs/test.js
  js/tests/unit/HelloWorld.spec.js
  js/tests/unit/components/Composer.test.js
  package-lock.json
  package.json
Labels: 2. developing

#1082 Add account settings view
  js/mixins/SidebarItems.js
  js/router.js
  js/views/AccountSettings.vue
Labels: 3. to review

#1091 Update config and babel for ie11
  .babelrc
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1061 Shorten table names and re-enable app code checker
  .travis.yml
  appinfo/database.xml
  appinfo/info.xml
  doc/developer.md
  lib/Db/CollectedAddressMapper.php
  lib/Migration/Version0100Date20180825194217.php
  lib/Migration/Version0110Date20180825195812.php
  lib/Migration/Version0110Date20180825201241.php
  tests/Db/CollectedAddressMapperTest.php
Labels: 3. to review, bounty, bug, enhancement

#1134 Disable js tests on vue refactor branch temporarily
  .travis.yml
Labels: 3. to review, technical debt

#1131 Fix Vue mock data loading
  js/components/FolderContent.vue
  js/service/AccountService.js
  js/service/FolderService.js
  js/service/MessageService.js
  js/store.js
  js/views/Home.vue
Labels: 3. to review, bug

#1132 Fix 'home' -> 'folder' redirection
  js/views/Home.vue
Labels: 3. to review, bug

#1133 Fix appNavigation exact routing by making it configurable
  js/components/core/navigationItem.vue
Labels: 3. to review, bug

#1135 Remove debug stmt
  js/mixins/SidebarItems.js
Labels: 3. to review, bug

#1136 Fix redirection on 'message' route -> don't jump to first msg
  js/components/FolderContent.vue
  js/service/MessageService.js
Labels: 3. to review, bug

#1137 Fix routing of the new message composer
  js/components/FolderContent.vue
  js/mixins/SidebarItems.js
Labels: 3. to review, bug

#1138 Remove dead (webpack) config
  js/OC.js
  js/webpack.base.config.js
  js/webpack.dev.config.js
  js/webpack.prod.config.js
Labels: 3. to review, bug

#1139 Load real accounts data
  js/service/AccountService.js
  js/service/FolderService.js
  package-lock.json
  package.json
Labels: 3. to review, enhancement

#1141 Fix account color bullet
  js/mixins/SidebarItems.js
  package-lock.json
  package.json
Labels: 3. to review, bug

#1142 Fix icons of special folders
  js/mixins/SidebarItems.js
Labels: 3. to review, bug

#1143 Fix displaying account email instead of name
  js/mixins/SidebarItems.js
Labels: 3. to review, bug

#1144 Load real message data
  css/mail.scss
  js/components/MessageListItem.vue
  js/service/MessageService.js
  js/webpack.common.js
  package-lock.json
  package.json
Labels: 3. to review, enhancement

#1151 Add rendering of text-only messages
  css/mail.scss
  js/components/Message.vue
  js/components/MessagePlainTextBody.vue
Labels: 3. to review, enhancement

#1153 Add loading of HTML message bodies
  js/components/Message.vue
  js/components/MessageHTMLBody.vue
  lib/Controller/MessagesController.php
Labels: 3. to review, enhancement

#1154 Add inifinte scroll to message/envelope list
  css/mail.scss
  js/components/MessageList.vue
  js/service/MessageService.js
  js/store.js
  package-lock.json
  package.json
Labels: 3. to review, enhancement

#1155 Add vue-based scroll-to-refresh
  js/components/MessageList.vue
  js/service/MessageService.js
  js/store.js
  package-lock.json
  package.json
Labels: 3. to review, enhancement

#1156 Make message and envelope unambiguous
  js/components/Envelope.vue
  js/components/EnvelopeList.vue
  js/components/FolderContent.vue
Labels: 3. to review

#1158 Mark seen messages as seen
  js/components/Message.vue
  js/service/MessageService.js
  js/store.js
Labels: 3. to review

#1160 Switch to upstream components lib
  js/components/core/appNavigation.vue
  js/components/core/navigationItem.vue
  js/components/core/popoverItem.vue
  js/components/core/popoverMenu.vue
  js/views/AccountSettings.vue
  js/views/Home.vue
  js/views/Setup.vue
  package-lock.json
  package.json
Labels: 3. to review

#1161 Re-enable js builds on Vue rework branch but disable tests
  .travis.yml
Labels: 3. to review

#1172 Lint code with eslint and format with prettier
  .editorconfig
  .eslintrc.js
  package-lock.json
  package.json
Labels: 3. to review
