Repository nextcloud/mail, pull requests merged in 2018-11, with the labels that each got.

#1224 Use Avatar component from nextcloud-vue
  src/components/Avatar.vue
  src/components/Envelope.vue
  webpack.common.js
Labels: 3. to review, technical debt

#1252 Add tabs to the setup/settings screen
  package-lock.json
  package.json
  src/components/AccountForm.vue
  src/views/Setup.vue
Labels: 3. to review, enhancement

#1256 Use action component for envelope actions
  src/components/Envelope.vue
Labels: 3. to review

#1258 Finish account setup feature
  lib/Controller/AccountsController.php
  src/components/AccountForm.vue
  src/service/AccountService.js
  src/store.js
  src/views/Setup.vue
  tests/Controller/AccountsControllerTest.php
Labels: 3. to review

#1262 Add test scripts to composer.json
  .travis.yml
  composer.json
Labels: 3. to review, technical debt

#1263 Fill reply recipients, subject and body
  package-lock.json
  package.json
  src/ReplyBuilder.js
  src/components/Composer.vue
  src/components/Envelope.vue
  src/components/Message.vue
  src/components/MessageHTMLBody.vue
  src/components/Moment.vue
  src/replybuilder.js
  src/tests/setup.js
  src/tests/unit/ReplyBuilder.spec.js
  src/tests/unit/util/HtmlHelper.spec.js
  src/util/HtmlHelper.js
  src/util/htmlhelper.js
  webpack.common.js
  webpack.dev.js
Labels: 3. to review, enhancement

#1264 Fix noreply handling on Vue rewrite branch
  src/components/Composer.vue
Labels: 3. to review, bug

#1265 Correctly route mailto link handling
  src/components/Composer.vue
  src/components/NewMessageDetail.vue
  src/router.js
  src/views/Home.vue
Labels: 3. to review, enhancement

#1267 Fix Vue unified inbox blockers
  src/components/Composer.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/FolderContent.vue
  src/components/Message.vue
  src/components/MessageAttachment.vue
  src/components/MessageAttachments.vue
  src/components/NewMessageDetail.vue
  src/mixins/SidebarItems.js
  src/router.js
  src/store.js
  src/util/EnvelopeUidParser.js
  src/views/Home.vue
Labels: 3. to review, technical debt

#1268 Re-implement unified inbox for Vue
  src/components/EnvelopeList.vue
  src/mixins/SidebarItems.js
  src/store.js
Labels: 2. developing, enhancement

#1273 Fix Travis' coverage reports on Scrutinizer
  .travis.yml
Labels: 3. to review, technical debt

#1277 Reduce Vue bundle size by using dynamic webpack imports
  src/main.js
  src/router.js
Labels: 3. to review, bug

#1281 Add missing color indicator for envelopes in a unified mailbox
  css/mail.scss
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/mixins/SidebarItems.js
  src/util/AccountColor.js
Labels: 3. to review, bug, regression

#1283 Fix automatically selected account
  src/components/Composer.vue
  src/components/NewMessageDetail.vue
Labels: 3. to review, bug, regression

#1288 Fix deleting envelope from unified mailbox
  src/store.js
Labels: 3. to review, bug, regression

#1289 Fix deletion of synced envelopes
  src/store.js
Labels: 3. to review, bug, regression

#1290 Fix timestamp update on envelopes
  src/components/Moment.vue
Labels: 3. to review, bug, regression

#1291 Handle message not found error
  src/components/Error.vue
  src/components/Message.vue
  src/service/MessageService.js
  src/store.js
Labels: 3. to review, bug, regression

#1294 Fix babel dependencies
  .babelrc
  package-lock.json
  package.json
Labels: 3. to review, bug, dependencies

#1292 Fix missing incoming envelopes from background sync
  src/store.js
Labels: 3. to review, bug, regression

#1296 Handle message loading errors and revive crash reporter
  lib/Http/JSONErrorResponse.php
  lib/Http/Middleware/ErrorMiddleware.php
  package-lock.json
  package.json
  src/components/Error.vue
  src/components/Message.vue
  src/crashreport.js
  src/http/ErrorResponseParser.js
  src/service/MessageService.js
  src/util/CrashReport.js
Labels: 3. to review, bug, enhancement

#1304 Do not add changed messages to unified inbox
  src/store.js
Labels: 3. to review, bug, regression

#1303 Show subfolders in sidebar
  src/mixins/SidebarItems.js
  src/store.js
Labels: 3. to review

#1308 Add forwarding of messages
  src/ReplyBuilder.js
  src/components/Message.vue
  src/components/NewMessageDetail.vue
  src/store.js
Labels: 3. to review

#1311 Add back button unblock blocked external content
  src/components/MessageHTMLBody.vue
Labels: 3. to review, enhancement

#1316 Remove dead sync service
  src/service/backgroundsyncservice.js
Labels: 3. to review, technical debt

#1315 Remove dead attachment service code
  src/service/_attachmentservice.js
Labels: 3. to review, technical debt

#1317 Fix outdated message flashing when navigation away
  src/components/Message.vue
Labels: 3. to review, bug

#1318 Fix typo in attachments button
  src/components/MessageAttachments.vue
Labels: 3. to review, bug

#1250 Use multiselects for the recipient selection
  css/mail.scss
  lib/Service/AutoCompletion/AutoCompleteService.php
  lib/Service/ContactsIntegration.php
  lib/Service/GroupsIntegration.php
  package-lock.json
  package.json
  src/components/Address.vue
  src/components/Composer.vue
  src/service/AutocompleteService.js
  src/store.js
  src/tests/unit/components/Address.spec.js
  tests/Service/Autocompletion/AutoCompleteServiceTest.php
  tests/Service/ContactsIntegrationTest.php
  tests/Service/GroupsIntegrationTest.php
Labels: 3. to review, enhancement, help wanted

#1329 The routes.php can just return an array
  appinfo/routes.php
Labels: 3. to review

#1330 Use the actual constructed query in the AccountMapper
  lib/Db/MailAccountMapper.php
Labels: 4. to release, bug, technical debt

#1337 Add Nextcloud 16, drop 14 support and adjust build matrix
  .travis.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review, technical debt

#1339 Backport (forward port?) master changes to Vue branch
  .github/config.yml
  .github/lock.yml
  .github/no-response.yml
  .github/stale.yml
  .travis.yml
  appinfo/info.xml
  appinfo/routes.php
  composer.json
  composer.lock
  l10n/en_GB.js
  l10n/en_GB.json
  l10n/eu.js
  l10n/eu.json
  l10n/hu.js
  l10n/hu.json
  l10n/ja.js
  l10n/ja.json
  l10n/lt_LT.js
  l10n/lt_LT.json
  l10n/zh_CN.js
  l10n/zh_CN.json
  lib/Db/MailAccountMapper.php
Labels: 3. to review, technical debt

#1332 Move the Alias/AliasMapper to the QBMapper
  lib/Db/Alias.php
  lib/Db/AliasMapper.php
  lib/Service/MailTransmission.php
  tests/Service/MailTransmissionTest.php
Labels: 2. developing, enhancement, technical debt

#1344 Add keyboard shortcuts page
  src/components/AppSettingsMenu.vue
  src/router.js
  src/views/KeyboardShortcuts.vue
Labels: 3. to review, enhancement

#1345 Hide CC/BCC by default
  src/components/Composer.vue
Labels: 3. to review, bug, regression
