Repository nextcloud/mail, pull requests merged in 2018-03, with the labels that each got.

#814 Update empty-folder.html
  js/templates/empty-folder.html
  js/tests/views/emptyfolderview_spec.js
Labels: 3. to review

#801 Fix stretching of non-square avatars
  css/mail.scss
Labels: 3. to review, bug, design

#797 Add port to redirect urls
  lib/Service/HtmlPurify/TransformURLScheme.php
Labels: 3. to review

#798 Message view cleared, when last message is deleted from a folder
  js/controller/foldercontroller.js
  js/templates/empty-message.html
  js/views/emptymessageview.js
  js/views/foldercontent.js
Labels: 3. to review, bug

#817 Fix to update counter on message delete
  js/controller/foldercontroller.js
Labels: 3. to review, bug

#826 Add Babel
  .babelrc.json
  js/webpack.base.config.js
  package-lock.json
  package.json
Labels: 3. to review, enhancement

#788 Generate a automatically prefilled GitHub issue templates for errors in debug mode
  js/controller/accountcontroller.js
  js/controller/foldercontroller.js
  js/crashreport.js
  js/routecontroller.js
  js/service/folderservice.js
  js/views/accountsettings.js
  js/views/messageattachmentsview.js
  js/views/messageattachmentview.js
  js/views/messagesitem.js
  js/views/setupview.js
  package-lock.json
  package.json
  templates/index.php
Labels: 3. to review, enhancement

#837 Switch back to original handlebars loader package
  package-lock.json
  package.json
Labels: 3. to review, bug, technical debt

#810 Sending to nextcloud groups
  .gitignore
  lib/AppInfo/Application.php
  lib/Controller/AccountsController.php
  lib/Service/AutoCompletion/AutoCompleteService.php
  lib/Service/Group/IGroupService.php
  lib/Service/Group/NextcloudGroupService.php
  lib/Service/GroupsIntegration.php
  tests/Controller/AccountsControllerTest.php
  tests/Service/Autocompletion/AutoCompleteServiceTest.php
  tests/Service/Group/NextcloudGroupServiceTest.php
  tests/Service/GroupsIntegrationTest.php
Labels: 3. to review, enhancement

#831 Sets focus on subject field for mailto links
  js/views/composerview.js
  js/views/foldercontent.js
Labels: 3. to review, design, enhancement, papercut

#850 Update npm lock file
  package-lock.json
Labels: 3. to review

#854 Switch to new Scrutinizer analysis
  .scrutinizer.yml
Labels: 3. to review, enhancement, technical debt

#852 Fix logging of already handled exceptions
  lib/Http/Middleware/ErrorMiddleware.php
  tests/Http/Middleware/ErrorMiddlewareTest.php
Labels: 3. to review, bug

#851 Fix no sender null check
  lib/Model/IMAPMessage.php
  tests/Model/IMAPMessageTest.php
Labels: 3. to review, bug

#857 Remove duplicated function
  js/views/helper.js
Labels: 3. to review, technical debt
