Repository nextcloud/mail, pull requests merged in 2018-05, with the labels that each got.

#893 Release 0.8.0
  CHANGELOG.md
Labels: 3. to review

#908 Add issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 3. to review, enhancement

#909 Add question template
  .github/ISSUE_TEMPLATE/question.md
Labels: 3. to review, enhancement

#916 dont encrypt the password multiple times when trying to auto detect smtp details
  lib/Service/AutoConfig/SmtpConnectivityTester.php
Labels: 3. to review, bug

#923 let urllinker handle html escaping for plain text mails instead of doing it beforehand
  lib/Model/IMAPMessage.php
  lib/Service/Html.php
  tests/Service/HtmlTest.php
Labels: 3. to review, bug
