Repository nextcloud/mail, pull requests merged in 2019-09, with the labels that each got.

#1971 Move away from string-based ID column as that causes problems on update
  .travis.yml
  appinfo/info.xml
  lib/Db/Mailbox.php
  lib/IMAP/MailboxSync.php
  lib/Migration/Version0161Date20190902103559.php
  lib/Migration/Version0161Date20190902103701.php
  package-lock.json
  tests/Db/MailboxMapperTest.php
Labels: 4. to release, bug, priority

#1970 Persist the mailbox special use as well
  lib/Db/Mailbox.php
  lib/IMAP/MailboxSync.php
  lib/Migration/Version0161Date20190902114635.php
  lib/Service/MailManager.php
  tests/Service/MailManagerTest.php
Labels: 4. to release, enhancement

#1986 Require Nextcloud 17 or 18
  .travis.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review

#1987 Improve error handling of the message sync
  lib/Contracts/IMailManager.php
  lib/Service/MailManager.php
Labels: 3. to review, technical debt

#1968 Clean up the code responsible for deleting a message
  lib/Account.php
  lib/AppInfo/Application.php
  lib/Contracts/IMailManager.php
  lib/Controller/MessagesController.php
  lib/Db/Mailbox.php
  lib/Db/MailboxMapper.php
  lib/Events/BeforeMessageDeletedEvent.php
  lib/IMAP/MailboxSync.php
  lib/IMAP/MessageMapper.php
  lib/Listener/MessageDeleteTrashCreatorListener.php
  lib/Mailbox.php
  lib/Service/MailManager.php
  tests/Controller/MessagesControllerTest.php
  tests/Db/MailboxMapperTest.php
  tests/IMAP/MessageMapperTest.php
  tests/Service/MailManagerTest.php
Labels: 3. to review, technical debt

#1991 Do not use lodash for undefined checks
  src/ReplyBuilder.js
  src/components/AccountForm.vue
  src/components/Avatar.vue
  src/components/Composer.vue
  src/components/ComposerAttachments.vue
  src/components/EnvelopeList.vue
  src/components/FolderContent.vue
  src/components/Message.vue
  src/components/NewMessageDetail.vue
  src/store/actions.js
  src/util/undefined.js
Labels: 3. to review, technical debt

#2007 Filter out empty MX'es
  lib/Service/AutoConfig/MxRecord.php
Labels: 3. to review, bug, priority, regression

#1997 Refactor send message and save draft logic
  lib/Account.php
  lib/AppInfo/Application.php
  lib/AppInfo/BootstrapSingleton.php
  lib/Contracts/IMailTransmission.php
  lib/Controller/AccountsController.php
  lib/Events/DraftSavedEvent.php
  lib/Events/MessageSentEvent.php
  lib/Events/SaveDraftEvent.php
  lib/IMAP/MessageMapper.php
  lib/Listener/AddressCollectionListener.php
  lib/Listener/DeleteDraftListener.php
  lib/Listener/DraftMailboxCreatorListener.php
  lib/Listener/FlagRepliedMessageListener.php
  lib/Listener/SaveSentMessageListener.php
  lib/Listener/TrashMailboxCreatorListener.php
  lib/Mailbox.php
  lib/Model/NewMessageData.php
  lib/Model/RepliedMessageData.php
  lib/Service/MailTransmission.php
  tests/Integration/Framework/ImapTest.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Listener/AddressCollectionListenerTest.php
  tests/Listener/DeleteDraftListenerTest.php
  tests/Listener/DraftMailboxCreatorListenerTest.php
  tests/Listener/FlagRepliedMessageListenerTest.php
  tests/Listener/SaveSentMessageListenerTest.php
  tests/Listener/TrashMailboxCreatorListenerTest.php
  tests/Service/MailTransmissionTest.php
Labels: 4. to release, technical debt

#2021 Do not show the <> around email if no name given
  src/components/Composer.vue
Labels: 3. to review, bug

#2033 Cache IMAP clients to lower number of connections
  lib/IMAP/IMAPClientFactory.php
Labels: 3. to review, enhancement, technical debt

#2032 Clean up HTML message loading (a bit)
  lib/Account.php
  lib/Contracts/IMailManager.php
  lib/Contracts/IMailTransmission.php
  lib/Controller/AccountsController.php
  lib/Controller/MessagesController.php
  lib/Events/MessageSentEvent.php
  lib/IMAP/MessageMapper.php
  lib/Listener/FlagRepliedMessageListener.php
  lib/Model/IMAPMessage.php
  lib/Model/IMessage.php
  lib/Model/Message.php
  lib/Model/NewMessageData.php
  lib/Model/RepliedMessageData.php
  lib/Model/ReplyMessage.php
  lib/Service/MailManager.php
  lib/Service/MailTransmission.php
  tests/Controller/AccountsControllerTest.php
  tests/Controller/MessagesControllerTest.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Listener/FlagRepliedMessageListenerTest.php
  tests/Model/IMAPMessageTest.php
  tests/Model/MessageTest.php
  tests/Model/RepliedMessageTest.php
  tests/Model/ReplyMessageTest.php
  tests/Service/MailTransmissionTest.php
Labels: 3. to review, technical debt

#2039 Include the HTML body in the JSON message data
  lib/Controller/MessagesController.php
  lib/Model/IMAPMessage.php
  tests/Model/IMAPMessageTest.php
Labels: 3. to review, technical debt

#2036 Flag drafts as draft
  lib/IMAP/MessageMapper.php
  lib/Service/MailTransmission.php
Labels: 3. to review, bug, regression

#2020 Show recipients in envelopes' list when displaying a 'sent' folder
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
Labels: 4. to release, enhancement

#2051 Fix invalid envelope avatar display name
  src/components/Envelope.vue
Labels: 3. to review, bug, regression
