Repository nextcloud/mail, pull requests merged in 2019-03, with the labels that each got.

#1575 Fix account deletion with Vue front-end
  lib/Db/AliasMapper.php
  lib/Service/AccountService.php
  lib/Service/AliasesService.php
  src/components/Envelope.vue
  src/mixins/SidebarItems.js
  src/service/AccountService.js
  src/store.js
Labels: 3. to review, bug, enhancement

#1574 Fix the used property for account colors: name -> email
  src/components/Envelope.vue
  src/mixins/SidebarItems.js
Labels: 3. to review, bug

#1323 Support PHP 7.3
  .travis.yml
  appinfo/info.xml
Labels: 3. to review, enhancement, priority

#1577 Split Vuex store into modules
  src/store/actions.js
  src/store/constants.js
  src/store/index.js
  src/store/mutations.js
Labels: 3. to review, technical debt

#1507 Add account settings page
  lib/Controller/AccountsController.php
  package-lock.json
  package.json
  src/components/AccountForm.vue
  src/service/AccountService.js
  src/store/actions.js
  src/store/actions.js.orig
  src/store/mutations.js
  src/views/AccountSettings.vue
  tests/Controller/AccountsControllerTest.php
Labels: 4. to release, enhancement, priority

#1582 Add liniting config
  .eslintrc.js
  package.json
Labels: 3. to review, enhancement, technical debt

#1584 Apply lint:autofix on store modules
  src/store/actions.js
  src/store/index.js
  src/store/mutations.js
Labels: 4. to release, technical debt

#1583 Apply lint:autofix on js services
  src/service/AccountService.js
  src/service/AttachmentService.js
  src/service/AutocompleteService.js
  src/service/AvatarService.js
  src/service/DAVService.js
  src/service/FolderService.js
  src/service/MessageService.js
  src/service/NotificationService.js
  src/service/PreferenceService.js
  src/service/aliasesservice.js
Labels: 4. to release, technical debt

#1576 Fix Vue design regressions in navigation
  package-lock.json
  package.json
  src/components/Navigation.vue
  src/mixins/SidebarItems.js
  src/views/AccountSettings.vue
  src/views/Home.vue
  src/views/KeyboardShortcuts.vue
Labels: 4. to release, bug, design, regression

#1586 Apply lint:autofix on all views
  src/App.vue
  src/views/AccountSettings.vue
  src/views/Home.vue
  src/views/KeyboardShortcuts.vue
  src/views/Setup.vue
Labels: 3. to review, technical debt

#1587 Apply lint:autofix on all components
  src/components/AccountForm.vue
  src/components/Address.vue
  src/components/AddressList.vue
  src/components/AppSettingsMenu.vue
  src/components/Avatar.vue
  src/components/Composer.vue
  src/components/ComposerAttachments.vue
  src/components/EmptyFolder.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/Error.vue
  src/components/FolderContent.vue
  src/components/Loading.vue
  src/components/Message.vue
  src/components/MessageAttachment.vue
  src/components/MessageAttachments.vue
  src/components/MessageHTMLBody.vue
  src/components/MessagePlainTextBody.vue
  src/components/Moment.vue
  src/components/Navigation.vue
  src/components/NewMessageDetail.vue
Labels: 3. to review, technical debt

#1588 Apply lint:autofix on util modules
  src/util/CrashReport.js
  src/util/ErrorMessageFactory.js
  src/util/HtmlHelper.js
  src/util/undefined.js
Labels: 3. to review, enhancement, technical debt

#1589 Apply lint:autofix on all tests
  src/tests/setup.js
  src/tests/unit/ReplyBuilder.spec.js
  src/tests/unit/components/Address.spec.js
  src/tests/unit/util/HtmlHelper.spec.js
Labels: 3. to review, technical debt

#1591 Fix initial loading of home component
  src/views/Home.vue
Labels: 3. to review, bug

#1592 Show upload progress for local attachments
  src/components/ComposerAttachments.vue
  src/service/AttachmentService.js
Labels: 3. to review, enhancement

#1593 Fix some design issues on the account settings page
  src/views/AccountSettings.vue
Labels: design, enhancement

#1629 Add lint to travis pipeline
  .travis.yml
Labels: 4. to release, enhancement, technical debt

#1630 Show the setup page if no accounts are configured
  src/views/Home.vue
Labels: bug, regression

#1631 Fetch the folders of a newly created account
  src/store/actions.js
Labels: 4. to release, bug, regression
