Repository nextcloud/mail, pull requests merged in 2019-10, with the labels that each got.

#2057 Add missing debug log to \OCA\Mail\IMAP\IMAPClientFactory::getClient
  lib/IMAP/IMAPClientFactory.php
Labels: 3. to review, bug

#2063 Remove unused fromEmail field from IMAP message json
  lib/Model/IMAPMessage.php
Labels: 3. to review, technical debt

#2062 Remove unused message size field
  lib/Model/IMAPMessage.php
Labels: 3. to review, technical debt

#2061 Remove unused date fields from message response
  lib/Model/IMAPMessage.php
Labels: 4. to release, technical debt

#2060 Remove unused \OCA\Mail\Account::listMailboxes
  lib/Account.php
Labels: 4. to release, technical debt

#2069 Use the new @nextcloud npm packages
  package-lock.json
  package.json
  src/ReplyBuilder.js
  src/components/ComposerAttachments.vue
  src/components/Message.vue
  src/components/MessageAttachment.vue
  src/components/Moment.vue
  src/l10n/MailboxTranslator.js
  src/logger.js
  src/main.js
  src/router.js
  src/service/AccountService.js
  src/service/AttachmentService.js
  src/service/AutocompleteService.js
  src/service/AvatarService.js
  src/service/DAVService.js
  src/service/FolderService.js
  src/service/MessageService.js
  src/service/NotificationService.js
  src/service/PreferenceService.js
  src/store/index.js
  src/util/ErrorMessageFactory.js
Labels: 4. to release, technical debt

#2070 Add bundle analyzer
  package-lock.json
  package.json
  webpack.common.js
Labels: 3. to review, technical debt

#2073 Fix webpack build off CI
  webpack.common.js
Labels: 3. to review, bug, technical debt

#2056 Remove \OCA\Mail\Account::createMailbox
  lib/Account.php
  tests/IMAP/AccountTest.php
Labels: 2. developing, technical debt

#2058 Refactor imap search
  lib/AppInfo/BootstrapSingleton.php
  lib/Contracts/IMailSearch.php
  lib/Controller/MessagesController.php
  lib/Db/Mailbox.php
  lib/IMAP/Search/FullScanSearchStrategy.php
  lib/IMAP/Search/ISearchStrategy.php
  lib/IMAP/Search/ImapSortSearchStrategy.php
  lib/IMAP/Search/SearchFilterStringParser.php
  lib/IMAP/Search/SearchStrategyFactory.php
  lib/Mailbox.php
  lib/SearchMailbox.php
  lib/Service/IMailBox.php
  lib/Service/MailManager.php
  lib/Service/MailSearch.php
  tests/Controller/MessagesControllerTest.php
  tests/IMAP/Search/SearchFilterStringParserTest.php
  tests/IMAP/Search/SearchStrategyFactoryTest.php
  tests/Service/MailSearchTest.php
Labels: 4. to release, technical debt

#2090 Do not fetch headers if we don't use them
  lib/Attachment.php
  lib/IMAP/MessageMapper.php
  lib/Model/IMAPMessage.php
  lib/Service/MailSearch.php
Labels: 3. to review, enhancement

#1988 Add CKEditor as WYSIWYG editor
  appinfo/info.xml
  appinfo/routes.php
  lib/Controller/AccountsController.php
  lib/Db/MailAccount.php
  lib/Migration/Version0180Date20190927124207.php
  lib/Model/NewMessageData.php
  lib/Service/AccountService.php
  lib/Service/MailTransmission.php
  package-lock.json
  package.json
  src/components/Composer.vue
  src/components/EditorSettings.vue
  src/components/NewMessageDetail.vue
  src/components/TextEditor.vue
  src/main.js
  src/service/AccountService.js
  src/store/actions.js
  src/tests/unit/util/HtmlHelper.spec.js
  src/views/AccountSettings.vue
  tests/Controller/AccountsControllerTest.php
  tests/Db/MailAccountMapperTest.php
  tests/Db/MailAccountTest.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  webpack.common.js
Labels: 2. developing, bounty, enhancement, feature:editor, priority

#2107 Set target branch to stable17
  .travis.yml
Labels: 3. to review, enhancement

#2112 Pimp Address.php
  lib/Address.php
Labels: 3. to review, technical debt

#2108 Do not show stats for unified inbox and handle errors
  src/components/NavigationFolder.vue
Labels: 4. to release, bug

#2114 Remove aliasesservice.js
  src/service/aliasesservice.js
Labels: 4. to release, technical debt

#2116 Migrate to @nextcloud/vue 1.0.0
  package-lock.json
  package.json
  src/components/AppDetailsToggle.vue
  src/components/Avatar.vue
  src/components/Composer.vue
  src/components/EditorSettings.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/FolderContent.vue
  src/components/Message.vue
  src/components/MessageAttachment.vue
  src/components/Navigation.vue
  src/components/NavigationAccount.vue
  src/components/NavigationAccountExpandCollapse.vue
  src/components/NavigationFolder.vue
  src/components/NewMessageDetail.vue
  src/components/NoMessageSelected.vue
  src/util/AccountColor.js
  src/views/AccountSettings.vue
  src/views/Home.vue
  src/views/KeyboardShortcuts.vue
  src/views/Setup.vue
Labels: 3. to review, dependencies, enhancement

#2113 Start move to IMAPClientFactory
  lib/Account.php
  lib/Service/AutoConfig/ImapConnector.php
  tests/IMAP/AbstractTest.php
  tests/Service/Autoconfig/ImapConnectorTest.php
Labels: 4. to release, technical debt

#2111 Remove getAccount from MessagesController
  lib/Controller/MessagesController.php
  lib/Service/AccountService.php
  tests/Controller/MessagesControllerTest.php
Labels: 3. to review, technical debt

#2120 Move over some code over to lodash/fp
  src/ReplyBuilder.js
  src/service/AvatarService.js
  src/service/NotificationService.js
Labels: 4. to release, enhancement

#2122 Move more functions to lodash/fp
  src/components/Composer.vue
  src/components/ComposerAttachments.vue
  src/components/FolderContent.vue
  src/imap/MailboxSorter.js
  src/store/index.js
Labels: 3. to review, enhancement, technical debt

#2124 Move over the final lodash to lodash/fp
  src/store/actions.js
  src/store/mutations.js
Labels: 4. to release, enhancement, technical debt

#2123 Design details
  src/components/NavigationAccountExpandCollapse.vue
  src/components/NavigationFolder.vue
  src/components/NoMessageSelected.vue
Labels: 3. to review, bug, design

#2121 Properly show resultst of stats
  src/components/NavigationFolder.vue
Labels: 3. to review, bug

#1967 Enh/user server response caching
  lib/Controller/AccountsController.php
  lib/Controller/AliasesController.php
  lib/Controller/AutoCompleteController.php
  lib/Controller/AvatarsController.php
  lib/Controller/FoldersController.php
  lib/Controller/LocalAttachmentsController.php
  lib/Controller/MessagesController.php
  lib/Controller/PageController.php
  lib/Controller/PreferencesController.php
  lib/Http/AvatarDownloadResponse.php
  lib/Http/CacheHeaders.php
  lib/Http/HtmlResponse.php
  lib/Http/JSONErrorResponse.php
  lib/Http/JSONResponse.php
  lib/Http/Middleware/ErrorMiddleware.php
  lib/Http/ProxyDownloadResponse.php
  tests/Controller/AccountsControllerTest.php
  tests/Controller/AliasesControllerTest.php
  tests/Controller/AutoconfigControllerTest.php
  tests/Controller/AvatarControllerTest.php
  tests/Controller/FoldersControllerTest.php
  tests/Controller/LocalAttachmentsControllerTest.php
  tests/Controller/MessagesControllerTest.php
  tests/Controller/PreferencesControllerTest.php
  tests/Http/Middleware/ErrorMiddlewareTest.php
Labels: 3. to review, technical debt

#2119 Improve design of account settings, move signature and writing mode up
  src/components/AccountForm.vue
  src/components/EditorSettings.vue
  src/components/SignatureSettings.vue
  src/views/AccountSettings.vue
Labels: 3. to review, design, enhancement

#2126 Fix layout of message list until we move to component
  css/mail.scss
  src/components/Avatar.vue
  src/components/Envelope.vue
Labels: 3. to review, bug, design

#2133 Deprecate account IMAP connection method
  lib/Account.php
Labels: 3. to review, technical debt

#2143 Fix type of avatar size property
  src/components/Avatar.vue
Labels: 4. to release, bug

#2144 Remove unused reply body
  src/components/Message.vue
Labels: 4. to release, technical debt

#2145 Add block quote formatting to the HTML editor
  package-lock.json
  package.json
  src/components/TextEditor.vue
Labels: 3. to review

#2146 Do not use side effects for reply and forward message data
  src/components/Message.vue
  src/components/MessageHTMLBody.vue
  src/components/NewMessageDetail.vue
  src/store/mutations.js
Labels: 3. to review, bug, regression

#2149 Fix usage of lodash's flatMapDeep in background sync
  src/store/actions.js
Labels: 3. to review, bug, regression

#2152 Switch to @nextcloud/browserslist-config
  package-lock.json
  package.json
Labels: 4. to release, technical debt

#2151 Fix missing parent constructor call
  lib/Http/HtmlResponse.php
Labels: 3. to review, bug, technical debt

#2147 Allow formatted replies
  src/ReplyBuilder.js
  src/components/Composer.vue
  src/components/EditorSettings.vue
  src/components/NewMessageDetail.vue
  src/components/TextEditor.vue
  src/tests/unit/util/HtmlHelper.spec.js
  src/util/HtmlHelper.js
Labels: 3. to review, bug

#2150 Fix showing external images
  src/components/MessageHTMLBody.vue
Labels: 3. to review, bug, regression

#2153 Improve redirect check
  lib/Controller/ProxyController.php
  src/autoredirect.js
  tests/Controller/ProxyControllerTest.php
  webpack.common.js
Labels: 3. to review, enhancement

#2155 Fix missing account display name and email prefill
  lib/AppInfo/Application.php
  lib/Controller/PageController.php
  package-lock.json
  package.json
  src/views/Setup.vue
  tests/Controller/PageControllerTest.php
Labels: 3. to review, regression

#2156 Add missing account setup feedback
  src/components/AccountForm.vue
  src/service/AccountService.js
  src/views/Setup.vue
Labels: 2. developing, bug, regression

#2130 Improve animation on EnvelopeList when you delete an email
  src/components/EnvelopeList.vue
Labels: 2. developing, design, enhancement

#2158 Clean up unused Karma config
  karma.conf.js
Labels: 3. to review, technical debt

#2159 Fix redirection on (first) account setup
  src/store/actions.js
  src/views/Home.vue
  src/views/Setup.vue
Labels: 3. to review, bug, regression

#2162 Fix marking another message as unread/read
  src/components/Envelope.vue
Labels: 4. to release, bug, regression

#2160 Account settings should be a form
  src/components/AccountForm.vue
Labels: 3. to review, bug, regression

#2165 Remove oudated js readme
  src/README.md
Labels: 3. to review, technical debt

#2166 Add missing Navigation when adding another account
  src/views/Setup.vue
Labels: 3. to review, bug, regression

#2163 Fix encoding issues of the folder display name
  lib/Folder.php
  src/components/FolderContent.vue
  src/components/NoMessageSelected.vue
  src/l10n/MailboxTranslator.js
  src/tests/unit/l10n/MailboxTranslator.spec.js
  tests/FolderTest.php
Labels: 3. to review, bug, regression

#2168 Fix folder info, stats and mark as read
  src/components/NavigationFolder.vue
Labels: 4. to release, bug, regression

#2167 Fix line breaks in plain text message
  lib/Service/Html.php
  tests/Service/HtmlTest.php
Labels: 3. to review, bug, regression

#2131 Composer design improvements
  src/components/Composer.vue
  src/components/Envelope.vue
Labels: 3. to review, design, enhancement

#2180 Better layout for reading and writing mails
  src/components/Composer.vue
  src/components/Message.vue
  src/components/MessageHTMLBody.vue
  src/components/TextEditor.vue
  src/views/Home.vue
Labels: 3. to review, design, enhancement

#2179 Fix unnecessary line breaks in quoted reply text
  lib/Service/Html.php
  src/components/MessagePlainTextBody.vue
  tests/Service/HtmlTest.php
Labels: 3. to review, bug, regression

#2190 Fix ckeditor
  package-lock.json
  package.json
Labels: 3. to review, priority, technical debt

#2191 Allow HTML signatures
  src/components/Composer.vue
  src/components/SignatureSettings.vue
  src/components/TextEditor.vue
  src/util/HtmlHelper.js
Labels: 3. to review, bug, enhancement

#2194 Fix loggin drafts promise errors
  src/components/Composer.vue
Labels: 3. to review, bug

#2193 Fix HTML handling when switching from plain text to HTML mode
  src/components/Composer.vue
  src/components/TextEditor.vue
Labels: 3. to review, bug

#2192 Fix removed reply to email
  src/ReplyBuilder.js
  src/tests/unit/ReplyBuilder.spec.js
Labels: 3. to review, bug, regression

#2196 Update CKEditor to v15
  package-lock.json
  package.json
  src/service/DAVService.js
  webpack.common.js
Labels: 3. to review

#2127 Fix groups expansion on umlauts
  lib/Service/GroupsIntegration.php
  src/components/Composer.vue
  tests/Service/GroupsIntegrationTest.php
Labels: 3. to review, bug

#2207 Add GitHub action linters
  .github/workflows/lint.yml
  .travis.yml
Labels: 3. to review
