Repository nextcloud/mail, pull requests merged in 2019-04, with the labels that each got.

#1642 Fix opening a message mobile
  package-lock.json
  package.json
  src/components/AppDetailsToggle.vue
  src/components/EnvelopeList.vue
  src/components/FolderContent.vue
  src/components/NoMessageSelected.vue
  src/views/Home.vue
Labels: 3. to review, bug, priority

#1633 Catch UID parsing errors
  src/util/EnvelopeUidParser.js
Labels: 4. to release, bug, technical debt

#1645 Do not show the "return" icon on the mobile envelope list
  src/components/FolderContent.vue
Labels: 3. to review, bug, regression

#1644 Disable fragile outlook.com integration test
  tests/Service/Autoconfig/IspDbTest.php
Labels: 3. to review, technical debt

#1646 Fix linting errors in the uid parser module
  src/tests/unit/util/EnvelopeUidParser.spec.js
Labels: 4. to release, technical debt

#1656 Require Nextcloud 16
  .travis.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 4. to release

#1594 Release v0.12.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1657 Add support for signatures
  appinfo/routes.php
  lib/Controller/AccountsController.php
  lib/Db/MailAccount.php
  lib/Migration/Version0130Date20190408134101.php
  lib/Service/AccountService.php
  src/components/Composer.vue
  src/components/SignatureSettings.vue
  src/service/AccountService.js
  src/store/actions.js
  src/views/AccountSettings.vue
  tests/Controller/AccountsControllerTest.php
  tests/Db/MailAccountTest.php
  tests/Service/AccountServiceTest.php
Labels: 4. to release, bounty, enhancement, feature parity

#1664 Fix setting the signature outside of Vuex
  src/components/SignatureSettings.vue
  src/store/actions.js
Labels: 3. to review, bug

#1666 Add the Mailvelope hint (again)
  src/components/AppSettingsMenu.vue
Labels: 4. to release, enhancement

#1667 Smal cleanup of the AccountsController
  lib/Controller/AccountsController.php
  tests/Controller/AccountsControllerTest.php
Labels: 3. to review, technical debt

#1668 Small cleanup of AccountService
  lib/Service/AccountService.php
  tests/Service/AccountServiceTest.php
Labels: 3. to review, technical debt

#1669 Replace the legacy appstore target in Makefile with the Krankerl command
  .travis.yml
  Makefile
Labels: 3. to review, bug, technical debt

#1672 Release v0.11.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1671 Rearrange Travis CI jobs
  .travis.yml
  composer.json
Labels: 3. to review, enhancement, technical debt

#1675 Remove actions.js.orig
  src/store/actions.js.orig
Labels: 4. to release, technical debt

#1674 Some more Controller cleanup
  lib/Controller/AliasesController.php
  lib/Controller/AutoCompleteController.php
  lib/Controller/AvatarsController.php
Labels: 4. to release, technical debt

#1676 Release v0.13.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1678 Make compatible with Nextcloud 17
  .travis.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review, enhancement

#1695 Translate folder names on the client-side
  lib/Folder.php
  lib/IMAP/FolderMapper.php
  lib/Service/FolderNameTranslator.php
  lib/Service/MailManager.php
  package-lock.json
  src/components/Navigation.vue
  src/l10n/MailboxTranslator.js
  src/store/index.js
  src/tests/setup.js
  src/tests/unit/l10n/MailboxTranslator.spec.js
  tests/FolderTest.php
  tests/Service/FolderNameTranslatorTest.php
  tests/Service/MailManagerTest.php
Labels: 3. to review, enhancement, technical debt

#1697 Move navigation account and folder to separate components
  src/components/Navigation.vue
  src/components/NavigationAccount.vue
  src/components/NavigationAccountExpandCollapse.vue
  src/components/NavigationFolder.vue
Labels: 4. to release, technical debt

#1698 Make it possible to create a new folder
  lib/Contracts/IMailManager.php
  lib/Controller/FoldersController.php
  lib/IMAP/FolderMapper.php
  lib/Service/MailManager.php
  src/components/NavigationAccount.vue
  src/service/FolderService.js
  src/store/actions.js
  src/store/mutations.js
  tests/Controller/FoldersControllerTest.php
  tests/IMAP/FolderMapperTest.php
  tests/Service/MailManagerTest.php
Labels: 3. to review, bounty, enhancement

#1699 Release v0.14.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1705 Make it possible to create subfolders and show folder stats
  appinfo/routes.php
  lib/Contracts/IMailManager.php
  lib/Controller/FoldersController.php
  lib/IMAP/FolderMapper.php
  lib/IMAP/FolderStats.php
  lib/Service/MailManager.php
  package-lock.json
  src/components/NavigationFolder.vue
  src/service/FolderService.js
  tests/Controller/FoldersControllerTest.php
  tests/IMAP/FolderMapperTest.php
  tests/Service/MailManagerTest.php
Labels: 3. to review, enhancement

#1714 Add dependabot badge
  README.md
Labels: 4. to release
