Repository nextcloud/mail, pull requests merged in 2019-05, with the labels that each got.

#1733 Remove JSCS
  .jscsrc
  Gruntfile.js
Labels: 4. to release, technical debt

#1739 Make it possible to mark a folder as read
  appinfo/routes.php
  lib/Contracts/IMailManager.php
  lib/Controller/FoldersController.php
  lib/IMAP/FolderMapper.php
  lib/IMAP/MessageMapper.php
  lib/Service/MailManager.php
  src/components/NavigationFolder.vue
  src/service/FolderService.js
  src/store/actions.js
Labels: 3. to review, bounty, enhancement, feature parity

#1751 Release v0.15.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1755 Fix caching of webpack chunks
  webpack.common.js
Labels: 3. to review, bug, priority

#1756 Release v0.15.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1759 Add nextcloud eslint linting
  .eslintrc.js
  package-lock.json
  package.json
  src/components/AccountForm.vue
  src/components/Message.vue
  src/imap/MailboxSorter.js
Labels: 3. to review

#1760 Update tar and fstream to resolve vulnerabilities
  package-lock.json
Labels: 3. to review, bug, security

#1782 Fix npm package name
  package-lock.json
  package.json
Labels: 3. to review
