Repository nextcloud/mail, pull requests merged in 2019-01, with the labels that each got.

#1440 Fix build matrix to not build with server master and php7.0
  .travis.yml
Labels: 3. to review, priority, technical debt

#1442 Fix address tooltip to show the actual address and not the label
  src/components/Address.vue
Labels: 3. to review, enhancement

#1411 Delete aliases when deleting account in account service
  lib/Db/AliasMapper.php
  lib/Service/AccountService.php
  lib/Service/AliasesService.php
  tests/Service/AccountServiceTest.php
Labels: 3. to review, bug

#1444 Fix font of expand/collapse action in accounts sidebar
  css/mail.scss
  src/mixins/SidebarItems.js
Labels: 3. to review, design, enhancement

#1443 Fix the wording of the "Seen" action on envelopes
  src/components/Envelope.vue
Labels: 3. to review, design

#1447 Fix navigation on envelope navigation
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
Labels: 3. to review, bug, regression

#1445 Fix the envelope delete shortcut
  src/components/EnvelopeList.vue
Labels: 3. to review, bug, regression

#1446 Fix reply recipient and own address logic
  src/components/Message.vue
Labels: 3. to review, bug, regression

#1448 Fix invalid int type hint for multipart part ids
  lib/Model/IMAPMessage.php
Labels: 3. to review, bug, regression

#1451 Add phan as composer dev dependency and add a composer script
  composer.json
  composer.lock
Labels: 3. to review, technical debt

#1453 Simplify the bug report issue template
  .github/ISSUE_TEMPLATE/bug.md
Labels: 3. to review, enhancement

#1452 Fix keyboard shortcuts
  src/components/Composer.vue
  src/components/EnvelopeList.vue
  src/views/Home.vue
  src/views/KeyboardShortcuts.vue
Labels: 3. to review, bug, regression

#1455 Fix slow account loading by using serialized data
  src/main.js
  src/service/AccountService.js
  src/views/Home.vue
Labels: 3. to review, bug, regression

#1456 Extract app content component
  package-lock.json
  package.json
  src/components/FolderContent.vue
  src/mixins/SidebarItems.js
  src/views/AccountSettings.vue
  src/views/Home.vue
  src/views/KeyboardShortcuts.vue
  src/views/Setup.vue
Labels: 3. to review, enhancement

#1475 Fixes for dark theme
  css/mail.scss
  src/components/Composer.vue
  src/components/Message.vue
Labels: 2. developing, bug, design

#1488 Load account folders with the page and add error handling
  lib/Controller/PageController.php
  src/components/FolderContent.vue
  src/main.js
  src/mixins/SidebarItems.js
  src/views/Home.vue
  tests/Controller/PageControllerTest.php
Labels: 3. to review

#1489 Fix string typehint that causes issues when the user logged out
  lib/Controller/PageController.php
Labels: 3. to review, bug

#1490 Pass components data via props instead of indirection via store
  src/components/EnvelopeList.vue
  src/components/FolderContent.vue
  src/views/Home.vue
Labels: 3. to review, technical debt

#1491 Add envelope search
  src/components/EnvelopeList.vue
  src/components/FolderContent.vue
  src/service/MessageService.js
  src/store.js
Labels: 3. to review, enhancement
