Repository nextcloud/mail, pull requests merged in 2019-11, with the labels that each got.

#2212 Switch to babel.config.js and @babel/preset-env
  .babelrc
  babel.config.js
  package-lock.json
  package.json
  webpack.common.js
Labels: 4. to release, bug, regression

#2211 relocate toggle arrow button
  src/components/AppDetailsToggle.vue
Labels: 3. to review, design

#2219 👌 IMPROVE: navigation settings styling improvement (spacing etc.)
  src/components/AppSettingsMenu.vue
Labels: 3. to review, design, enhancement

#2223 👌 IMPROVE: don't show popover for addresses without a display name/label
  src/components/Address.vue
Labels: 3. to review, design, enhancement

#2215 Fall back to attachment name from content type if it's not set in con…
  lib/Attachment.php
Labels: 3. to review, bug

#2226 👌 IMPROVE: put composer attachment buttons into three dot menu
  src/components/Composer.vue
  src/components/ComposerAttachments.vue
Labels: 3. to review, feature:editor

#2247 Feature/noissue/plain text vs rich text checkbox
  src/components/Composer.vue
Labels: 4. to release, design, enhancement, feature:editor

#2251 Fix flagges shown as subfolder on some accounts
  src/imap/MailboxHierarchy.js
  src/tests/unit/imap/MailboxHierarchy.spec.js
Labels: 3. to review, bug, regression

#2249 Focus on the "To" field when writing a new message.
  src/components/Composer.vue
Labels: 3. to review, bug

#2248 Label the unified inbox as "All inboxes"
  src/l10n/MailboxTranslator.js
  src/store/index.js
Labels: 4. to release, bug, regression

#2246 Show recipient avatar in folders of type "Sent"
  src/components/Envelope.vue
Labels: 4. to release, bug

#2220 🐛 FIX: various horizontal scrolling issues on mobile
  css/mobile.scss
  src/components/Composer.vue
  src/components/FolderContent.vue
Labels: 3. to review, design

#2203 Test against php beta & nightly
  .travis.yml
Labels: 4. to release

#2268 Fix ical import
  lib/Controller/MessagesController.php
  src/service/DAVService.js
Labels: 4. to release, bug, regression

#2267 Add php7.4 support
  .github/workflows/lint.yml
  .travis.yml
  appinfo/info.xml
  lib/Service/Attachment/AttachmentStorage.php
Labels: 3. to review, enhancement

#2271 Fix unexpected linebreaks in mails, responsive text flow, fix #2181
  src/util/HtmlHelper.js
Labels: 3. to review, design, enhancement

#2272 Patch out version check on nightly builds
  .travis.yml
Labels: 3. to review, enhancement

#2275 Drop php 7.1 support
  .travis.yml
  appinfo/info.xml
Labels: 3. to review, technical debt

#2289 Drop php7.1 from composer config as well
  composer.json
  composer.lock
Labels: 3. to review
