Repository nextcloud/mail, pull requests merged in 2020-07, with the labels that each got.

#3337 Store the `references`, `in-reply-to` and the thread root id
  appinfo/info.xml
  lib/Db/Message.php
  lib/Db/MessageMapper.php
  lib/IMAP/MessageMapper.php
  lib/Migration/Version1050Date20200624101359.php
  lib/Model/IMAPMessage.php
Labels: 3. to review, enhancement, feature:threading

#3353 Make sure all commands return an int
  lib/Command/CleanUp.php
  lib/Command/CreateAccount.php
  lib/Command/DiagnoseAccount.php
  lib/Command/ExportAccount.php
  lib/Command/SyncAccount.php
  lib/Command/TrainAccount.php
Labels: 3. to review, bug

#3355 Implement the jwz threading algorithm
  lib/IMAP/Threading/Container.php
  lib/IMAP/Threading/Message.php
  lib/IMAP/Threading/ThreadBuilder.php
  tests/Unit/IMAP/Threading/ContainerTest.php
  tests/Unit/IMAP/Threading/MessageTest.php
  tests/Unit/IMAP/Threading/ThreadBuilderTest.php
Labels: 3. to review, enhancement, feature:threading

#3356 Add real-world test for a linear message thread
  tests/Unit/IMAP/Threading/ThreadBuilderTest.php
Labels: 3. to review, enhancement

#2125 Build message threads after each sync and store thread root ID for later reference
  lib/AppInfo/Application.php
  lib/Db/MessageMapper.php
  lib/Events/SynchronizationEvent.php
  lib/IMAP/Threading/DatabaseMessage.php
  lib/Listener/AccountSynchronizedThreadUpdaterListener.php
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: 3. to review, enhancement

#3357 Do not combine threads with identical subjects
  lib/IMAP/Threading/ThreadBuilder.php
  tests/Unit/IMAP/Threading/ThreadBuilderTest.php
Labels: 3. to review, enhancement

#3307 Fix folder creation design
  src/components/NavigationAccount.vue
  src/components/NavigationFolder.vue
  src/store/actions.js
  src/store/mutations.js
Labels: enhancement

#3338 Revive aliases feature
  lib/Db/Alias.php
  lib/Service/MailTransmission.php
  src/components/AliasSettings.vue
  src/components/Composer.vue
  src/components/SignatureSettings.vue
  src/service/AliasService.js
  src/store/actions.js
  src/store/mutations.js
  src/views/AccountSettings.vue
Labels: 4. to release, enhancement

#3369 Clean up mix up of ID, UID and UUID
  lib/Db/Message.php
  lib/Model/IMAPMessage.php
  src/components/Address.vue
  src/components/Composer.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  src/components/MailboxMessage.vue
  src/components/Message.vue
  src/components/MessageAttachment.vue
  src/components/MessageAttachments.vue
  src/components/Navigation.vue
  src/components/NewMessageDetail.vue
  src/router.js
  src/service/MessageService.js
  src/store/actions.js
  src/store/getters.js
  src/store/mutations.js
  src/store/normalization.js
  src/tests/unit/store/actions.spec.js
  src/tests/unit/store/normalization.spec.js
  src/tests/unit/util/EnvelopeUidParser.spec.js
  src/util/EnvelopeUidParser.js
  src/views/Home.vue
  tests/Unit/Model/IMAPMessageTest.php
Labels: 3. to review, technical debt

#3367 Add a REST resource to fetch a thread
  appinfo/routes.php
  lib/Contracts/IMailManager.php
  lib/Controller/MessagesController.php
  lib/Db/MessageMapper.php
  lib/Service/MailManager.php
  tests/Unit/Service/MailManagerTest.php
Labels: 3. to review, enhancement, feature:threading
