Repository nextcloud/mail, pull requests merged in 2020-12, with the labels that each got.

#4160 Switch to vue2 package of the CKEditor
  package-lock.json
  package.json
  src/components/TextEditor.vue
Labels: 3. to review, technical debt

#4159 Adds caching for MessageController's getBody function
  lib/Controller/MessagesController.php
Labels: 3. to review, enhancement

#4163 Prevent Vue from making the CKEditor instance reactive
  src/components/TextEditor.vue
Labels: 3. to review, bug, priority:high, regression

#4173 Update changelog for 1.7.1, 1.6.2 and 1.5.4
  CHANGELOG.md
Labels: 3. to review

#4047 Fix the back arrow to work properly
  src/components/AppDetailsToggle.vue
  src/components/Thread.vue
  src/views/Home.vue
Labels: 3. to review, bug, regression

#4170 Fixes an issue where the reply button of the ThreadEnvelopes would not reply to the correct message
  src/components/ThreadEnvelope.vue
Labels: 3. to review, backport-request, bug, priority:medium

#4103 Remember trusted senders
  appinfo/info.xml
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/Contracts/ITrustedSenderService.php
  lib/Controller/MessagesController.php
  lib/Controller/TrustedSendersController.php
  lib/Db/TrustedSender.php
  lib/Db/TrustedSenderMapper.php
  lib/Migration/Version1080Date20201119084820.php
  lib/Service/TrustedSenderService.php
  src/components/Message.vue
  src/components/MessageHTMLBody.vue
  src/service/TrustedSenderService.js
  tests/Integration/Db/TrustedSenderMapperTest.php
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Service/TrustedSenderServiceTest.php
Labels: 3. to review, enhancement

#4177 Fix attachment icon and wording
  src/components/Composer.vue
Labels: 3. to review, enhancement

#4086 Require vendor autoloader in class definition
  lib/AppInfo/Application.php
Labels: 4. to release, technical debt

#4161 Automaticaly sync mailbox on opening
  src/components/Mailbox.vue
Labels: 3. to review, enhancement

#4185 Use consistent input vector size for the importance classifier
  lib/Service/Classification/FeatureExtraction/CompositeExtractor.php
  lib/Service/Classification/FeatureExtraction/IExtractor.php
  lib/Service/Classification/FeatureExtraction/ImportantMessagesExtractor.php
  lib/Service/Classification/FeatureExtraction/ReadMessagesExtractor.php
  lib/Service/Classification/FeatureExtraction/RepliedMessagesExtractor.php
  lib/Service/Classification/FeatureExtraction/SentMessagesExtractor.php
  lib/Service/Classification/ImportanceClassifier.php
Labels: 3. to review, backport-request, bug, priority:medium

#4205 Use a Github action for integration tests
  .github/workflows/lint.yml
  .github/workflows/package.yml
  .github/workflows/test.yml
  .nextcloudignore
  .scrutinizer.yml
  .travis.yml
  Makefile
  codecov.yml
  lib/Account.php
  tests/Integration/Framework/ImapTest.php
  tests/Integration/Framework/ImapTestAccount.php
  tests/Integration/IMAP/AbstractTest.php
  tests/Integration/IMAP/IMAPClientFactoryTest.php
  tests/Integration/Service/FolderMapperIntegrationTest.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Integration/TestCase.php
Labels: 3. to review

#4206 Syncs Sents mailbox after sending an email (when it's the mailbox currently open)
  src/components/Composer.vue
Labels: 3. to review, enhancement

#4207 Remove "All inboxes" if one account is setup
  src/components/NavigationMailbox.vue
Labels: 3. to review, design, enhancement

#4212 forwarding a message from a threadEnvelope's forward menu action doesn't forward the correct message
  src/components/ThreadEnvelope.vue
Labels: 3. to review, backport-request, bug

#4215 Fix mark as favorite from ThreadEnvelope
  src/components/ThreadEnvelope.vue
Labels: 3. to review, bug, regression

#4216 Change folder into mailbox
  src/components/EmptyMailbox.vue
  src/components/MailboxPicker.vue
  src/components/NavigationAccount.vue
  src/components/NavigationAccountExpandCollapse.vue
  src/components/NavigationMailbox.vue
Labels: 3. to review, bug

#4130 Change account settings into modal
  appinfo/routes.php
  lib/Controller/PageController.php
  src/components/AccountForm.vue
  src/components/AccountSettings.vue
  src/components/AliasSettings.vue
  src/components/EditorSettings.vue
  src/components/NavigationAccount.vue
  src/components/SignatureSettings.vue
  src/router.js
  src/views/AccountSettings.vue
Labels: 2. developing, design, enhancement

#4224 Fix to #4218
  src/components/ThreadEnvelope.vue
Labels: 3. to review, bug

#4244 Bump CKEditor to v24
  package-lock.json
  package.json
Labels: 3. to review, 4. to release, dependencies

#4235 Makes links highlighted in the ckeditor
  src/components/TextEditor.vue
Labels: 3. to review, backport-request, enhancement

#4237 Opens mailto: links in Mail
  lib/Service/Html.php
  lib/Service/HtmlPurify/TransformHTMLLinks.php
Labels: 3. to review, enhancement

#3998 Allow admins to limit the size of attachements
  doc/admin.md
  lib/Controller/PageController.php
  package-lock.json
  package.json
  src/components/Composer.vue
  src/components/ComposerAttachments.vue
  src/main.js
  src/service/FileService.js
  templates/index.php
  tests/Unit/Controller/PageControllerTest.php
Labels: 3. to review, enhancement, priority:medium

#3950 Add original attachments when forwarding a mail
  lib/IMAP/MessageMapper.php
  lib/Model/IMAPMessage.php
  lib/Model/IMessage.php
  lib/Model/Message.php
  lib/Service/MailTransmission.php
  src/components/Composer.vue
  src/components/ComposerAttachments.vue
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Unit/Model/MessageTest.php
  tests/Unit/Service/MailTransmissionTest.php
Labels: 3. to review, enhancement, priority:medium

#4253 Always show sender in avatar header, even on very small screens
  src/components/RecipientBubble.vue
  src/components/Thread.vue
Labels: 3. to review, bug

#4257 Fix Webpack issue with CKEditor's dynamic translation imports
  babel.config.js
  src/components/TextEditor.vue
  src/tests/unit/components/Address.spec.js
Labels: 3. to review, bug, regression

#4251 Add forward as attachment
  lib/IMAP/MessageMapper.php
  lib/Model/IMAPMessage.php
  lib/Model/IMessage.php
  lib/Model/Message.php
  lib/Service/MailManager.php
  lib/Service/MailTransmission.php
  src/components/Composer.vue
  src/components/EnvelopeList.vue
  tests/Unit/Service/MailTransmissionTest.php
Labels: 3. to review, enhancement, feature parity, priority:medium

#4280 Fix single reply and forward actions
  src/components/ThreadEnvelope.vue
Labels: 4. to release, backport-request, bug, priority:high, regression

#4284 Revive js unit tests and add CI check
  .github/workflows/test.yml
  babel.config.js
  package-lock.json
  package.json
  src/tests/unit/store/actions.spec.js
  src/tests/unit/util/text.spec.js
  src/util/text.js
Labels: 3. to review, bug, technical debt
