Repository nextcloud/mail, pull requests merged in 2020-10, with the labels that each got.

#3247 Set file picker to copy mode.
  src/components/MessageAttachment.vue
  src/components/MessageAttachments.vue
Labels: 4. to release, bug

#3687 Do not navigate when clicking an envelope's menu
  src/components/Envelope.vue
  src/components/MessageAttachments.vue
Labels: 4. to release, bug, priority:high, regression

#3688 Update changelog for v1.5.0
  CHANGELOG.md
Labels: 3. to review

#3692 Migrate controllers to the PSR logger interface
  lib/Controller/AccountsController.php
  lib/Controller/MessagesController.php
  lib/Controller/PageController.php
  tests/Unit/Controller/AccountsControllerTest.php
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Controller/PageControllerTest.php
Labels: 4. to release, enhancement, technical debt

#3694 Migrate middlewares to the PSR logger interface
  lib/Http/Middleware/ErrorMiddleware.php
  lib/Http/Middleware/ProvisioningMiddleware.php
  tests/Unit/Http/Middleware/ErrorMiddlewareTest.php
  tests/Unit/Http/Middleware/ProvisioningMiddlewareTest.php
Labels: 4. to release, enhancement, technical debt

#3717 Migrate \OCA\Mail\IMAP\* to the logger interface
  lib/IMAP/MessageMapper.php
  lib/IMAP/PreviewEnhancer.php
  lib/IMAP/Search/Provider.php
  tests/Unit/IMAP/MessageMapperTest.php
Labels: 4. to release, enhancement, technical debt

#3719 Migrate listeners to the PSR logger
  lib/Listener/AddressCollectionListener.php
  lib/Listener/FlagRepliedMessageListener.php
  lib/Listener/InteractionListener.php
  lib/Listener/MessageCacheUpdaterListener.php
  lib/Listener/NewMessageClassificationListener.php
  lib/Listener/UserDeletedListener.php
  tests/Unit/Listener/AddressCollectionListenerTest.php
  tests/Unit/Listener/FlagRepliedMessageListenerTest.php
Labels: 3. to review, technical debt

#3718 Migrate \OCA\Mail\Integration\* to the PSR logger
  lib/Command/SyncAccount.php
  lib/Integration/KItinerary/ItineraryExtractor.php
  lib/Integration/Psr/LoggerAdapter.php
  tests/Integration/KItinerary/ItineraryExtractorTest.php
Labels: 3. to review, technical debt

#3695 Replace btoa function by proper base64 encoder
  package-lock.json
  package.json
  src/components/ThreadEnvelope.vue
  src/main.js
  webpack.common.js
Labels: 2. developing, bug

#3728 Fix displaying of mails with empty from field
  src/components/ThreadEnvelope.vue
Labels: 3. to review, bug

#3731 Fix translation of delete account dialogue
  src/components/NavigationAccount.vue
Labels: 3. to review, backport-request, bug

#3734 Bump CKEditor to v23
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#3720 Migrate remaining usage of ILogger to the PSR logger interface
  lib/Command/DiagnoseAccount.php
  lib/Command/TrainAccount.php
  lib/Listener/InteractionListener.php
  lib/Migration/MakeItineraryExtractorExecutable.php
  lib/Service/AutoCompletion/AddressCollector.php
  lib/Service/AutoConfig/ConnectivityTester.php
  lib/Service/AutoConfig/ImapConnectivityTester.php
  lib/Service/AutoConfig/ImapConnector.php
  lib/Service/AutoConfig/IspDb.php
  lib/Service/AutoConfig/IspDbConfigurationDetector.php
  lib/Service/AutoConfig/MxRecord.php
  lib/Service/AutoConfig/SmtpConnectivityTester.php
  lib/Service/Classification/PersistenceService.php
  lib/Service/ItineraryService.php
  lib/Service/MailTransmission.php
  lib/Service/Provisioning/Manager.php
  lib/Service/Search/MailSearch.php
  lib/Service/SetupService.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Service/ItineraryServiceTest.php
  tests/Unit/Service/Autocompletion/AddressCollectorTest.php
  tests/Unit/Service/Autoconfig/ConnectivityTesterTest.php
  tests/Unit/Service/Autoconfig/ImapConnectivityTesterTest.php
  tests/Unit/Service/Autoconfig/ImapConnectorTest.php
  tests/Unit/Service/Autoconfig/IspDbTest.php
  tests/Unit/Service/Autoconfig/MxRecordTest.php
  tests/Unit/Service/Autoconfig/SmtpConnectivityTesterTest.php
  tests/Unit/Service/MailTransmissionTest.php
  tests/Unit/Service/Search/MailSearchTest.php
  tests/Unit/Service/SetupServiceTest.php
Labels: 3. to review, technical debt

#3735 Fix the overlapping of the threads
  src/components/Thread.vue
Labels: 3. to review, backport-request, bug

#3749 Add psalm auto-generated return types
  lib/Cache/Cache.php
  lib/Command/SyncAccount.php
  lib/Service/CleanupService.php
  lib/Service/MailTransmission.php
  lib/Service/SetupService.php
Labels: 3. to review, technical debt

#3748 Update the min php version to 7.3
  .travis.yml
  composer.json
  composer.lock
Labels: 3. to review, technical debt

#3754 Fix import of wrong class in mail transmission code
  lib/Service/MailTransmission.php
Labels: 4. to release, bug

#3755 Fix some obvious errors reported by Psalm, take 1
  lib/Contracts/IMailManager.php
  lib/Db/MessageMapper.php
  lib/Service/CleanupService.php
  lib/Service/ItineraryService.php
Labels: 3. to review, bug, technical debt

#3753 Update psalm config and add a workflow
  .github/workflows/static-analysis.yml
  composer.json
  composer.lock
  psalm.xml
Labels: 3. to review, technical debt

#3750 Fix nullable return types reported by Psalm
  lib/IMAP/Threading/Container.php
  lib/Service/AutoConfig/IspDbConfigurationDetector.php
Labels: 3. to review, technical debt

#3751 Fix invalid falsable returns detected by Psalm
  lib/Service/Avatar/AddressbookSource.php
  lib/Service/ContactsIntegration.php
Labels: 3. to review, bug, technical debt

#3761 Fix saving aliases
  src/service/AliasService.js
Labels: 4. to release, backport-request, bug

#3757 Fix remaining psalm errors, add baseline and CI test matrix for all Nextcloud versions
  .github/workflows/static-analysis.yml
  lib/BackgroundJob/CleanupJob.php
  lib/Command/CreateAccount.php
  lib/Contracts/IMailManager.php
  lib/Contracts/IMailTransmission.php
  lib/Controller/AccountsController.php
  lib/Controller/MailboxesController.php
  lib/Controller/MessagesController.php
  lib/Controller/SettingsController.php
  lib/Db/MessageMapper.php
  lib/Mailbox.php
  lib/Model/IMAPMessage.php
  lib/Model/IMessage.php
  lib/Model/Message.php
  lib/Service/AccountService.php
  lib/Service/AutoCompletion/AddressCollector.php
  lib/Service/AutoConfig/SmtpConnectivityTester.php
  lib/Service/Avatar/Downloader.php
  lib/Service/Classification/FeatureExtraction/ImportantMessagesExtractor.php
  lib/Service/Classification/FeatureExtraction/ReadMessagesExtractor.php
  lib/Service/Classification/FeatureExtraction/RepliedMessagesExtractor.php
  lib/Service/Html.php
  lib/Service/HtmlPurify/TransformURLScheme.php
  lib/Service/MailManager.php
  lib/Service/MailTransmission.php
  psalm.xml
  tests/Unit/Controller/MessagesControllerTest.php
  tests/psalm-baseline.xml
Labels: 3. to review, technical debt

#3779 Fix psalm error 3
  composer.json
  lib/Account.php
  lib/Attachment.php
  lib/Contracts/IAvatarService.php
  lib/Controller/AccountsController.php
  lib/Controller/AvatarsController.php
  lib/Db/LocalAttachmentMapper.php
  lib/Db/MailboxMapper.php
  lib/Http/JsonResponse.php
  lib/IMAP/MailboxSync.php
  lib/IMAP/MessageMapper.php
  lib/Model/IMAPMessage.php
  lib/Model/IMessage.php
  lib/Model/NewMessageData.php
  lib/Service/AccountService.php
  lib/Service/Attachment/AttachmentStorage.php
  lib/Service/AutoConfig/SmtpServerDetector.php
  lib/Service/Avatar/Cache.php
  lib/Service/AvatarService.php
  lib/Service/Classification/ImportanceClassifier.php
  lib/Service/Classification/PersistenceService.php
  lib/Service/MailManager.php
  lib/Service/MailTransmission.php
  lib/Service/SetupService.php
  tests/Unit/Service/AvatarServiceTest.php
Labels: 3. to review, technical debt

#3781 Set Psalm to error level 4 and update baseline file
  composer.json
  composer.lock
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review, technical debt

#3782 Fix psalm errors part 4
  lib/IMAP/Sync/Response.php
  lib/Model/NewMessageData.php
Labels: 3. to review

#3795 Fix test class name and file name mismatch
  tests/Unit/Controller/AutoCompleteControllerTest.php
  tests/Unit/Service/Autoconfig/IspDbTest.php
  tests/Unit/Service/Avatar/GravatarSourceTest.php
Labels: 3. to review, technical debt

#3801 Migrate phpunit's `at` to consecutive call assertions
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/IMAP/MessageMapperTest.php
  tests/Unit/Listener/DeleteDraftListenerTest.php
  tests/Unit/Listener/SaveSentMessageListenerTest.php
  tests/Unit/Service/Autocompletion/AddressCollectorTest.php
Labels: 4. to release, technical debt

#3804 Bump christophwurst/nextcloud_testing from 0.10.0 to 0.11.0
  composer.json
  composer.lock
Labels: 4. to release, dependencies

#3807 Update psalm baseline to reflect fixed issues
  tests/psalm-baseline.xml
Labels: 4. to release, technical debt

#3803 Mark immutable classes as immutable
  lib/Address.php
  lib/AddressList.php
  lib/Model/NewMessageData.php
  lib/Model/RepliedMessageData.php
  lib/Service/Avatar/Avatar.php
  lib/Service/MailTransmission.php
  tests/AddressListTest.php
  tests/AddressTest.php
  tests/Unit/Listener/AddressCollectionListenerTest.php
  tests/Unit/Listener/InteractionListenerTest.php
  tests/Unit/Model/MessageTest.php
Labels: 4. to release, technical debt

#3697 #3696 made message-frame height auto to use the remaining space
  src/components/MessageHTMLBody.vue
Labels: 4. to release, backport-request, bug

#3560 Catch more errors in sync function to recover from "Mailbox does not support mod-sequences" error on partial sync
  lib/Exception/MailboxDoesNotSupportModSequencesException.php
  lib/IMAP/Sync/Synchronizer.php
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: 0. to triage

#3828 OCA.Search is deprecated
  src/components/MailboxThread.vue
Labels: 3. to review

#3843 Make menus automaticaly close after clicking on an action button
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/ThreadEnvelope.vue
Labels: 4. to release, enhancement

#3756 Show important/starred/read status inside a thread
  src/components/ThreadEnvelope.vue
Labels: 3. to review, design, enhancement

#3832 fix a bug when navigating away from a draft that's not yet loaded
  src/components/NewMessageDetail.vue
Labels: 3. to review

#3849 Update the authors list after v1.5
  appinfo/info.xml
Labels: 2. developing, backport-request, enhancement

#3846 Change font colour for add mail account
  src/components/AppSettingsMenu.vue
Labels: 4. to release, bug, design

#3817 Some more Psalm fixes
  lib/Address.php
  lib/Listener/AccountSynchronizedThreadUpdaterListener.php
  lib/Service/AutoConfig/MxRecord.php
  lib/Service/Avatar/FaviconSource.php
  lib/Service/Avatar/GravatarSource.php
  lib/Service/SetupService.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Unit/Service/MailTransmissionTest.php
Labels: 4. to release, technical debt

#3850 Backport l10n update to stable1.5
  l10n/cs.js
  l10n/cs.json
  l10n/de.js
  l10n/de.json
  l10n/de_DE.js
  l10n/de_DE.json
  l10n/es.js
  l10n/es.json
  l10n/fr.js
  l10n/fr.json
  l10n/gl.js
  l10n/gl.json
  l10n/it.js
  l10n/it.json
  l10n/pl.js
  l10n/pl.json
  l10n/pt_BR.js
  l10n/pt_BR.json
  l10n/sl.js
  l10n/sl.json
  l10n/tr.js
  l10n/tr.json
  l10n/zh_CN.js
  l10n/zh_CN.json
Labels: 3. to review, enhancement

#3852 Change account settings button colour, to fit the theme
  src/components/AccountForm.vue
  src/components/AliasSettings.vue
  src/components/Composer.vue
  src/components/SignatureSettings.vue
Labels: 4. to release, backport-request, bug, design

#3855 Make sure the e-mail is valid UTF-8
  lib/Address.php
Labels: 3. to review, bug

#3591 Move mails
  lib/Service/MailManager.php
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/MoveModal.vue
  src/components/ThreadEnvelope.vue
  src/service/MessageService.js
  src/store/actions.js
  src/views/Home.vue
Labels: 2. developing, enhancement, priority:medium

#3861 Clean up the move modal, reuse design for the mailbox picker
  package-lock.json
  package.json
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/MailboxPicker.vue
  src/components/MoveModal.vue
  src/components/ThreadEnvelope.vue
Labels: 3. to review, enhancement, technical debt

#3862 Fix the move modal
  src/components/MailboxPicker.vue
Labels: 3. to review, bug

#3871 Make the deserialized thread root ID nullable
  lib/Command/Thread.php
Labels: 3. to review, backport-request, bug

#3877 Convert reply button to a link
  src/components/ThreadEnvelope.vue
Labels: 3. to review, enhancement

#3896 Fix moving multiple envelopes
  src/components/EnvelopeList.vue
Labels: 3. to review, bug

#3899 Update changelog for v1.5.1
  CHANGELOG.md
Labels: 3. to review, backport-request, enhancement

#3876 Improve source modal scroll bar
  src/components/ThreadEnvelope.vue
Labels: 3. to review, design, enhancement, papercut

#3905 Use composer v1 on Github CI
  .github/workflows/lint.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
Labels: 3. to review, backport-request, bug, priority:high, technical debt

#3901 Remove traling space characters from text strings
  src/components/EnvelopeList.vue
Labels: 3. to review, bug

#3907 GitHub actions integration tests
  .github/workflows/lint.yml
  .github/workflows/package.yml
  .github/workflows/test.yml
  .nextcloudignore
  .scrutinizer.yml
  .travis.yml
  Makefile
  codecov.yml
  lib/Account.php
  lib/IMAP/MailboxSync.php
  tests/Integration/Framework/ImapTest.php
  tests/Integration/Framework/ImapTestAccount.php
  tests/Integration/IMAP/AbstractTest.php
  tests/Integration/IMAP/IMAPClientFactoryTest.php
  tests/Integration/Service/FolderMapperIntegrationTest.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Integration/TestCase.php
Labels: 3. to review, enhancement, priority:high, technical debt

#3913 Sort phpunit tests by defect
  composer.json
  tests/phpunit.integration.xml
  tests/phpunit.unit.xml
Labels: 3. to review, priority:low, technical debt

#3783 Type the QB mappers with the entity template
  .github/workflows/static-analysis.yml
  composer.json
  composer.lock
  lib/Db/AliasMapper.php
  lib/Db/ClassifierMapper.php
  lib/Db/CollectedAddressMapper.php
  lib/Db/LocalAttachmentMapper.php
  lib/Db/MailAccountMapper.php
  lib/Db/MailboxMapper.php
  lib/Db/MessageMapper.php
Labels: 3. to review, priority:low, technical debt
