Repository nextcloud/mail, pull requests merged in 2020-04, with the labels that each got.

#2841 Do not pass the UID twice when sending a mail
  lib/Contracts/IMailTransmission.php
  lib/Controller/AccountsController.php
  lib/Service/MailTransmission.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Unit/Controller/AccountsControllerTest.php
  tests/Unit/Service/MailTransmissionTest.php
Labels: 4. to release, technical debt

#2843 Fix routing for the reply and forward actions
  src/components/Message.vue
Labels: 3. to review, bug, regression

#2838 Abstract text into an object with known format
  src/ReplyBuilder.js
  src/components/Composer.vue
  src/components/NewMessageDetail.vue
  src/components/SignatureSettings.vue
  src/components/TextEditor.vue
  src/service/MessageService.js
  src/tests/unit/ReplyBuilder.spec.js
  src/tests/unit/util/HtmlHelper.spec.js
  src/tests/unit/util/text.spec.js
  src/util/HtmlHelper.js
  src/util/text.js
Labels: 3. to review, technical debt

#2846 Fix missing In-Reply-To header for replies
  src/components/Composer.vue
  src/components/NewMessageDetail.vue
Labels: 3. to review, bug, regression

#2854 Move reply handling to where we know the account
  src/components/Composer.vue
  src/components/NewMessageDetail.vue
Labels: 3. to review, technical debt

#2851 Fix URLs of embedded images
  lib/Controller/MessagesController.php
Labels: 3. to review, bug, regression

#2872 Fix missing padding-top of composer
  src/components/Composer.vue
Labels: 3. to review, bug, design, regression

#2849 Improve logging when the sent folder can't be created
  lib/Listener/SaveSentMessageListener.php
  tests/Unit/Listener/SaveSentMessageListenerTest.php
Labels: 4. to release, enhancement

#2871 Fix signature settings layout, simplify HTML
  src/components/SignatureSettings.vue
Labels: 4. to release, bug, design

#2873 Lower the memory footprint of the initial message cache sync
  lib/Command/SyncAccount.php
  lib/IMAP/MessageMapper.php
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: 3. to review, enhancement

#2877 Fix format for aliases
  src/components/Composer.vue
Labels: 4. to release

#2874 Fix handling of plain/html replies in plain/html
  src/components/Composer.vue
  src/components/NewMessageDetail.vue
Labels: 3. to review, bug, priority, regression

#2878 Add individually sync'ed new messages to the unified mailbox
  src/store/mutations.js
  src/tests/unit/store/mutations.spec.js
Labels: 3. to review, bug, feature:unified inbox, priority, regression

#2892 Force action menu to be shown even with one element
  src/components/NavigationFolder.vue
Labels: 4. to release, bug

#2889 Do not trigger scroll event on page load
  src/components/MailboxMessage.vue
Labels: 3. to review, bug

#2893 Do not navigate from a message to just the folder
  src/components/Message.vue
  src/views/Home.vue
Labels: 3. to review, bug

#2905 Migrate from OCP.Toast to @nextcloud/dialogs
  src/components/itinerary/EventReservation.vue
  src/components/itinerary/FlightReservation.vue
  src/components/itinerary/TrainReservation.vue
Labels: 3. to review, technical debt

#2906 Update changelong
  CHANGELOG.md
Labels: 4. to release

#2907 Add php cs fixer action
  .github/workflows/lint.yml
  composer.json
Labels: 4. to release, technical debt

#2912 Fix handling of service exceptions
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: 3. to review, bug, priority

#2916 In cron always sync mailboxes before sync'ing their messages
  lib/BackgroundJob/SyncJob.php
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: 3. to review, bug

#2914 Break the recursion when fetching the next page
  src/store/actions.js
Labels: 3. to review, bug, priority, regression

#2920 Fix lower bound when fetching a range of IMAP messages for the sync
  lib/IMAP/MessageMapper.php
  lib/Service/Sync/ImapToDbSynchronizer.php
  tests/Unit/IMAP/MessageMapperTest.php
Labels: 4. to release, bug, priority

#2928 Update the screenshot
  appinfo/info.xml
  screenshots/mail.png
Labels: 3. to review, enhancement

#2955 Limit the size of recipient labels
  lib/Db/MessageMapper.php
Labels: 4. to release, bug

#2935 Make it possible to clear the message cache as user
  appinfo/routes.php
  lib/Controller/FoldersController.php
  lib/Service/Sync/ImapToDbSynchronizer.php
  lib/Service/Sync/SyncService.php
  src/components/NavigationFolder.vue
  src/service/MessageService.js
Labels: 3. to review, enhancement

#2934 Sync mailbox not just inbox
  src/components/Mailbox.vue
Labels: 2. developing, enhancement

#2958 Do not sync accounts that are provisioned and have no password set
  lib/BackgroundJob/SyncJob.php
Labels: 3. to review, backport-request, bug

#2962 Generate coverage data in github actions
  .github/workflows/test.yml
Labels: 4. to release, technical debt

#2796 Make it possible to mark messages important
  appinfo/info.xml
  img/important.svg
  lib/AppInfo/BootstrapSingleton.php
  lib/Db/Message.php
  lib/Db/MessageMapper.php
  lib/Events/NewMessagesSynchronized.php
  lib/Listener/NewMessageClassificationListener.php
  lib/Migration/Version1040Date20200422130220.php
  lib/Migration/Version1040Date20200422142920.php
  lib/Model/IMAPMessage.php
  lib/Service/Classification/AClassifier.php
  lib/Service/Classification/MessageClassifier.php
  lib/Service/Classification/OftenContactedSenderClassifier.php
  lib/Service/Classification/OftenImportantSenderClassifier.php
  lib/Service/Classification/OftenReadSenderClassifier.php
  lib/Service/Classification/OftenRepliedSenderClassifier.php
  lib/Service/Classification/SafeRatio.php
  lib/Service/Sync/ImapToDbSynchronizer.php
  package-lock.json
  package.json
  src/components/Envelope.vue
  src/store/actions.js
  tests/Unit/Service/Classification/ClassifierTest.php
  webpack.common.js
Labels: 3. to review, enhancement

#2978 Fix the namespace of UidValidityChangedException
  lib/Exception/UidValidityChangedException.php
  lib/IMAP/Sync/Synchronizer.php
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: 3. to review, backport-request, bug

#2648 Add priority inbox "light"
  lib/Contracts/IMailSearch.php
  lib/Controller/MessagesController.php
  lib/Db/MessageMapper.php
  lib/Service/Search/MailSearch.php
  lib/Service/Sync/SyncService.php
  src/components/Mailbox.vue
  src/components/MailboxMessage.vue
  src/components/NavigationFolder.vue
  src/components/SectionTitle.vue
  src/i18n/MailboxTranslator.js
  src/service/MessageService.js
  src/store/actions.js
  src/store/constants.js
  src/store/index.js
  src/store/mutations.js
  tests/Unit/Service/Search/MailSearchTest.php
Labels: 2. developing, enhancement

#2984 Make it possible to filter messages for the important flag
  lib/Db/MessageMapper.php
  lib/Service/Search/FilterStringParser.php
Labels: 4. to release, enhancement

#2985 Add priority section
  src/components/MailboxMessage.vue
Labels: 4. to release, enhancement

#2979 Fix UID validity change logic
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: 3. to review, backport-request, bug

#2980 Log the progress of an incomplete sync
  lib/IMAP/MessageMapper.php
  lib/Service/Sync/ImapToDbSynchronizer.php
  tests/Unit/IMAP/MessageMapperTest.php
Labels: 3. to review, backport-request, enhancement

#2972 Use all available group services
  lib/AppInfo/BootstrapSingleton.php
  lib/Service/GroupsIntegration.php
  tests/Unit/Service/GroupsIntegrationTest.php
Labels: 3. to review, backport-request, bug, regression

#3008 Change important section to allow favorites too
  src/components/MailboxMessage.vue
Labels: 3. to review, bug

#3011 Change the space between priority section
  src/components/EnvelopeList.vue
Labels: 4. to release, design, enhancement

#3013 Fix endless initial sync due to empty partial page
  lib/IMAP/MessageMapper.php
Labels: 3. to review, backport-request, bug

#3010 Drop Nextcloud 17 support
  .travis.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review
