Repository nextcloud/mail, pull requests merged in 2020-01, with the labels that each got.

#2446 base64_encode $folderId
  lib/Model/IMAPMessage.php
Labels: 4. to release

#2214 Show itinerary info
  .eslintrc.js
  composer.json
  composer.lock
  lib/Controller/MessagesController.php
  lib/IMAP/MessageMapper.php
  lib/Integration/KItinerary/ItineraryExtractor.php
  lib/Integration/Psr/LoggerAdapter.php
  lib/Model/IMAPMessage.php
  lib/Service/ItineraryService.php
  package-lock.json
  package.json
  src/components/Itinerary.vue
  src/components/Message.vue
  src/components/itinerary/CalendarImport.vue
  src/components/itinerary/EventReservation.vue
  src/components/itinerary/FlightReservation.vue
  src/components/itinerary/TrainReservation.vue
  src/service/DAVService.js
  tests/Integration/KItinerary/ItineraryExtractorTest.php
  tests/Service/ItineraryServiceTest.php
  tests/Unit/Controller/MessagesControllerTest.php
Labels: 3. to review, enhancement, priority

#2448 Run lint for all PRs
  .github/workflows/lint.yml
Labels: bug, technical debt

#2450 Simplify logger creation
  package-lock.json
  package.json
  src/logger.js
Labels: 3. to review, enhancement

#2452 Fix 'tain' typo
  src/components/itinerary/TrainReservation.vue
Labels: 4. to release, bug

#2474 Fix vanishing newlines of plaintext drafts
  lib/Model/IMAPMessage.php
  src/components/NewMessageDetail.vue
  src/components/TextEditor.vue
Labels: 3. to review, bug, regression

#2483 Always update account display name
  lib/Service/Provisioning/Manager.php
Labels: 3. to review, bug

#2479 Focus editor in replies and forwdared messagess
  src/components/Composer.vue
  src/components/TextEditor.vue
Labels: 3. to review, bug

#2414 Feature contact group send
  lib/AppInfo/Application.php
  lib/AppInfo/BootstrapSingleton.php
  lib/Service/Group/ContactsGroupService.php
  tests/Unit/Service/Group/ContactsGroupServiceTest.php
Labels: 4. to release, enhancement

#2486 Add lines into texteditor
  src/ReplyBuilder.js
  src/tests/unit/ReplyBuilder.spec.js
Labels: 3. to review, bug, priority

#2485 Fix focus of composer body for reply and forwards
  src/components/TextEditor.vue
Labels: 3. to review, bug, regression

#2484 Add hint for autoconfig
  doc/admin.md
Labels: 3. to review

#2518 Return full exception trace
  lib/Http/Middleware/ErrorMiddleware.php
  tests/Unit/Http/Middleware/ErrorMiddlewareTest.php
Labels: 4. to release

#2523 Add Nextcloud 19 support
  .travis.yml
  appinfo/info.xml
Labels: 3. to review

#2521 remove mark all as read from All Inboxes
  src/components/NavigationFolder.vue
Labels: 3. to review, bug

#2520 hide subfolder for all inboxes
  src/components/NavigationFolder.vue
Labels: 3. to review, bug

#2527 disable send button when to, cc, bcc is empty
  src/components/Composer.vue
Labels: 4. to release, bug

#2528 Also allow Throwable in ErrorMiddleware
  lib/Http/Middleware/ErrorMiddleware.php
Labels: 3. to review, bug

#2533 Change Copy/Blind Copy into CC/BCC
  src/components/Composer.vue
Labels: 4. to release, bug

#2529 Do not fail when no CATEGORY is set on contacts
  lib/Service/Group/ContactsGroupService.php
Labels: 4. to release, bug, feature:integration

#2539 Add mailto: protocol handler
  src/components/AppSettingsMenu.vue
Labels: 2. developing, bug, priority, regression

#2534 Make the itinerary extractor executable in a repair step
  appinfo/info.xml
  lib/Migration/MakeItineraryExtractorExecutable.php
Labels: 3. to review

#2541 Show embedded messages as attachments
  lib/Attachment.php
  lib/Controller/MessagesController.php
  lib/Model/IMAPMessage.php
  src/components/Composer.vue
  src/components/MessageAttachment.vue
  src/components/MessageAttachments.vue
  tests/Unit/Controller/MessagesControllerTest.php
Labels: 3. to review, bug, priority

#2543 Preserve recipient input when focus is lost
  src/components/Composer.vue
Labels: 3. to review, bug

#2454 Uses ReplyBuilder.js to compute the list of recipients when replying to a email.
  src/ReplyBuilder.js
  src/components/NewMessageDetail.vue
  src/tests/unit/ReplyBuilder.spec.js
Labels: 3. to review

#2561 Update Krankerl to v0.12.1
  .travis.yml
Labels: 3. to review, enhancement, technical debt

#2544 Use .nextcloudignore to exclude packaged files
  .nextcloudignore
  krankerl.toml
Labels: 3. to review, technical debt

#2490 Fix creating a new mailbox
  lib/Service/MailManager.php
  src/components/NavigationAccount.vue
  src/components/NavigationFolder.vue
  src/store/actions.js
  src/store/mutations.js
Labels: 4. to release, bug, regression

#2403 Fix automatic provisioning (for new users)
  lib/Http/Middleware/ProvisioningMiddleware.php
  tests/Unit/Http/Middleware/ProvisioningMiddlewareTest.php
Labels: 3. to review

#2565 Fix packaging ignore config
  .nextcloudignore
Labels: 3. to review, bug, priority

#2563 Update Krankerl to v0.12.2
  .travis.yml
Labels: 4. to release, technical debt

#2560 Update Travis base image to Xenial
  .travis.yml
Labels: 3. to review, technical debt

#2568 Fix saving an embedded message to Files
  lib/Controller/MessagesController.php
Labels: 3. to review, bug

#2366 Use php7.4 instead of the snapshot
  .travis.yml
Labels: 3. to review, enhancement, technical debt

#2571 Add plural form for email
  src/components/NavigationFolder.vue
Labels: 3. to review, bug

#2573 Fix saving all attachments to files
  src/components/MessageAttachments.vue
Labels: 3. to review, bug

#2575 Pass a real octal num to chmod
  lib/Migration/MakeItineraryExtractorExecutable.php
Labels: 4. to release

#2581 Add translated default string for unnamed
  src/components/MessageAttachment.vue
Labels: 3. to review, bug
