Repository nextcloud/mail, pull requests merged in 2020-08, with the labels that each got.

#3292 Log level for training classifier changed
  lib/Service/Classification/ImportanceClassifier.php
Labels: 3. to review, backport-request, bug

#3428 Bump CKEditor to v21
  package-lock.json
  package.json
Labels: 3. to review, dependencies, enhancement

#2730 Add delete action for folders
  appinfo/routes.php
  lib/Contracts/IMailManager.php
  lib/Controller/FoldersController.php
  lib/IMAP/FolderMapper.php
  lib/Service/MailManager.php
  src/components/NavigationFolder.vue
  src/service/FolderService.js
  src/store/actions.js
  src/store/mutations.js
  src/tests/unit/store/mutations.spec.js
Labels: 4. to release, enhancement

#3388 Implement dashboard panel
  img/newsletter.svg
  lib/AppInfo/Application.php
  lib/Dashboard/MailWidget.php
  lib/Listener/DashboardPanelListener.php
  package-lock.json
  package.json
  src/main-dashboard.js
  src/views/Dashboard.vue
  webpack.common.js
Labels: 4. to release, enhancement

#3438 Move some usage of the old Folder to the more versatile Mailbox
  lib/Contracts/IMailManager.php
  lib/Controller/FoldersController.php
  lib/Controller/PageController.php
  lib/Db/Mailbox.php
  lib/Folder.php
  lib/IMAP/FolderMapper.php
  lib/IMAP/MailboxSync.php
  lib/Service/MailManager.php
  tests/FolderTest.php
  tests/Unit/Controller/FoldersControllerTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/IMAP/FolderMapperTest.php
  tests/Unit/Service/MailManagerTest.php
Labels: 3. to review, technical debt

#3452 Show setup button if no accounts are set up
  src/views/Dashboard.vue
Labels: 4. to release, bug

#3437 Fix l10n extraction from wrapped translation text
  src/components/MailboxMessage.vue
Labels: 3. to review, backport-request, bug

#3460 Disable tooltip on dashboard avatar
  src/components/Avatar.vue
  src/views/Dashboard.vue
Labels: 3. to review, bug

#3461 Fix accessibility problems
  src/components/MailboxMessage.vue
  src/components/MessageHTMLBody.vue
Labels: 3. to review, enhancement

#3433 Add a unified search provider
  lib/AppInfo/Application.php
  lib/Contracts/IMailSearch.php
  lib/Db/MessageMapper.php
  lib/Search/Provider.php
  lib/Service/Search/FilterStringParser.php
  lib/Service/Search/MailSearch.php
  lib/Service/Search/SearchQuery.php
  tests/Unit/Service/Autoconfig/SmtpServerDetectorTest.php
Labels: 3. to review, enhancement, feature:integration

#3482 Fix the pagination in the unified search
  lib/Search/Provider.php
Labels: bug

#3480 Bump christophwurst/nextcloud to v20.0.0 Beta 1
  composer.json
  composer.lock
Labels: 4. to release, technical debt

#3485 Add missing comma to Avatar component
  src/components/Avatar.vue
Labels: 3. to review, technical debt

#3484 Fix leftover usage of mailbox.id when mailbox.name is required
  src/components/NavigationMailbox.vue
  src/imap/MailboxSorter.js
  src/tests/unit/i18n/MailboxTranslator.spec.js
  src/tests/unit/imap/MailboxHierarchy.spec.js
  src/tests/unit/imap/MailboxPrefix.spec.js
  src/tests/unit/imap/MailboxSorter.spec.js
Labels: 3. to review, bug

#3488 Do not compare apples and pears during the mailbox sync
  lib/Service/Sync/SyncService.php
Labels: 3. to review, bug, regression

#3487 Fix favorite/important ranking and typos
  src/components/Envelope.vue
  src/components/Message.vue
  src/components/NavigationAccount.vue
  src/components/NavigationMailbox.vue
Labels: 4. to release, design, papercut
