Repository nextcloud/mail, pull requests merged in 2020-05, with the labels that each got.

#3020 Don't mark as important in archive, draft, junk, sent or trash
  lib/Listener/NewMessageClassificationListener.php
Labels: 3. to review, bug, feature:priority inbox

#3007 Change emptycontent on mail
  src/components/EmptyMailboxSection.vue
  src/components/Mailbox.vue
  src/components/MailboxMessage.vue
Labels: 3. to review, enhancement, feature:priority inbox

#3027 Fix query in often contacted sender classifier
  lib/Service/Classification/OftenContactedSenderClassifier.php
Labels: 3. to review, bug

#3056 Update CKEditor to v19
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#2729 Add confirmation when deleting account
  src/components/NavigationAccount.vue
Labels: 3. to review, enhancement

#3002 Safari 100% height in message
  src/components/Composer.vue
  src/components/Message.vue
  src/components/MessageHTMLBody.vue
Labels: 3. to review, backport-request

#3028 Fix the missing translation from settings
  src/components/AppSettingsMenu.vue
Labels: 4. to release, bug

#3068 Make loading spinner not move all messages
  src/components/EnvelopeList.vue
Labels: 3. to review, design, enhancement

#3075 Allow Nextcloud 20
  .travis.yml
  appinfo/info.xml
Labels: 3. to review

#3077 Fix onsistency of "important" icon
  css/mail.scss
  src/components/Envelope.vue
  src/components/MailboxMessage.vue
  src/components/NavigationFolder.vue
Labels: 3. to review, bug, design, feature:priority inbox

#3078 Fix vertical space between sections in priority inbox
  src/components/Mailbox.vue
Labels: 4. to release, design, enhancement, feature:priority inbox

#3009 Delete all user's accounts when the user is deleted
  lib/AppInfo/BootstrapSingleton.php
  lib/Listener/UserDeletedListener.php
Labels: 3. to review, bug

#3072 Optimize the background sync logic
  src/components/Mailbox.vue
  src/store/actions.js
Labels: 3. to review, enhancement, papercut

#3098 Make priority inbox sections collapsible
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  src/components/MailboxMessage.vue
Labels: 3. to review, design, feature:priority inbox

#3067 Add mark as junk on emails
  lib/Controller/MessagesController.php
  lib/Db/Message.php
  lib/Model/IMAPMessage.php
  lib/Service/MailManager.php
  src/components/Envelope.vue
  src/components/Message.vue
  src/store/actions.js
  src/store/actions.js.orig
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Service/MailManagerTest.php
Labels: 4. to release, enhancement, feature parity

#3097 Add background database cleanup
  appinfo/info.xml
  lib/BackgroundJob/CleanupJob.php
  lib/Command/CleanUp.php
  lib/Db/AliasMapper.php
  lib/Db/CollectedAddressMapper.php
  lib/Db/MailboxMapper.php
  lib/Db/MessageMapper.php
  lib/Service/CleanupService.php
Labels: 4. to release, backport-request, enhancement

#3052 Fix mailvelope integration by switching to the API version
  css/mail.scss
  src/components/AppSettingsMenu.vue
  src/components/Composer.vue
  src/components/MailvelopeEditor.vue
  src/components/Message.vue
  src/components/MessageEncryptedBody.vue
  src/components/NewMessageDetail.vue
  src/crypto/mailvelope.js
  src/crypto/pgp.js
  src/tests/unit/crypto/mailvelope.spec.js
  src/tests/unit/crypto/pgp.spec.js
Labels: 3. to review, backport-request, bug

#3107 Fix div by zero in important messages feature extractor
  lib/Service/Classification/FeatureExtraction/ImportantMessagesExtractor.php
Labels: 3. to review, bug

#3105 Mozartize the favicon lib
  composer.json
  composer.lock
  lib/Service/Avatar/FaviconSource.php
  tests/Integration/Service/Avatar/FaviconSourceTest.php
  tests/Unit/Service/Avatar/FaviconSourceTest.php
Labels: 3. to review, technical debt

#3104 Exclude lib/Vendor/ from php-cs-fixer runs
  .php_cs.dist
Labels: 3. to review, technical debt

#3108 Fix updating a prop
  src/components/EnvelopeList.vue
Labels: 3. to review, bug

#3109 Fix deleting a message from the priority inbox
  src/components/NavigationFolder.vue
  src/i18n/MailboxTranslator.js
  src/store/actions.js
  src/store/index.js
  src/store/mutations.js
  src/tests/unit/store/mutations.spec.js
Labels: 3. to review, bug

#3113 Mozartize the Gravatar lib
  composer.json
  composer.lock
  lib/Service/Avatar/GravatarSource.php
Labels: 3. to review, enhancement

#3137 Fix user data cleanup after user deletion
  lib/Listener/UserDeletedListener.php
Labels: 3. to review, backport-request, bug

#3117 Add kitinerary-sys adapter
  composer.json
  composer.lock
  lib/Integration/KItinerary/ItineraryExtractor.php
  tests/Integration/KItinerary/ItineraryExtractorTest.php
Labels: 4. to release, enhancement, feature:integration

#3136 Updated the hard app reset instructions.
  doc/developer.md
Labels: 4. to release

#3128 Work around the cold start problem by falling back to rules
  lib/Db/StatisticsDao.php
  lib/Service/Classification/AClassifier.php
  lib/Service/Classification/FeatureExtraction/SentMessagesExtractor.php
  lib/Service/Classification/ImportanceClassifier.php
  lib/Service/Classification/ImportanceRulesClassifier.php
  lib/Service/Classification/MessageClassifier.php
  lib/Service/Classification/OftenContactedSenderClassifier.php
  lib/Service/Classification/OftenImportantSenderClassifier.php
  lib/Service/Classification/OftenReadSenderClassifier.php
  lib/Service/Classification/OftenRepliedSenderClassifier.php
  lib/Service/Classification/SafeRatio.php
  tests/Unit/Service/Classification/ClassifierTest.php
Labels: 4. to release, enhancement

#3116 Show only subscribed folders
  appinfo/info.xml
  lib/Controller/AccountsController.php
  lib/Db/MailAccount.php
  lib/IMAP/FolderMapper.php
  lib/Migration/Version1040Date20200515080614.php
  src/components/NavigationAccount.vue
  src/components/NavigationAccountExpandCollapse.vue
  src/components/NavigationFolder.vue
  src/store/actions.js
  src/store/index.js
  src/store/mutations.js
  tests/Integration/Db/MailAccountTest.php
Labels: 4. to release, enhancement

#2619 Actions on multiple message
  lib/Service/Sync/ImapToDbSynchronizer.php.orig
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/service/MessageService.js.orig
  src/store/actions.js
Labels: 4. to release, enhancement

#3133 Fix l10n extraction in app settings
  src/components/AppSettingsMenu.vue
Labels: 3. to review, bug, regression

#3142 Fix folder mapper tests
  tests/Unit/IMAP/FolderMapperTest.php
Labels: 3. to review, technical debt

#3141 Add important AND favorite to the same section
  src/components/MailboxMessage.vue
Labels: 4. to release, regression

#3074 Open inbox when clicking on account item
  src/components/Navigation.vue
  src/components/NavigationAccount.vue
Labels: 2. developing, enhancement

#3110 Fix sync'ing with many known UIDs
  lib/IMAP/Sync/Synchronizer.php
  tests/Unit/IMAP/Sync/SynchronizerTest.php
Labels: 4. to release, bug

#3160 Fix usage of wrong constant for sync new
  lib/IMAP/Sync/Synchronizer.php
Labels: 3. to review, bug

#3155 Migrate from php-ml to rubix/ml
  appinfo/info.xml
  composer.json
  composer.lock
  lib/Db/ClassifierMapper.php
  lib/Service/Classification/ImportanceClassifier.php
  lib/Service/Classification/PersistenceService.php
Labels: 3. to review, enhancement, priority

#3156 Add search by subject
  lib/Db/MessageMapper.php
Labels: 3. to review, enhancement

#3164 Widen the mail_messages message_id column
  appinfo/info.xml
  lib/Migration/Version1040Date20200529124657.php
Labels: 4. to release, bug

#3161 Fix navigating back from small screens
  src/views/Home.vue
Labels: 4. to release, backport-request, regression

#3162 Escape the subject search term for the LIKE clause
  lib/Db/MessageMapper.php
Labels: 3. to review, bug
