Repository nextcloud/mail, pull requests merged in 2020-06, with the labels that each got.

#3166 Fix invalid prop
  src/components/NavigationAccount.vue
Labels: 4. to release, bug, regression

#3140 Add tooltip for important filter
  src/components/MailboxMessage.vue
Labels: 4. to release

#3165 Downgrade mochapack
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#3176 Catch importance classification exception during sync
  lib/Listener/NewMessageClassificationListener.php
  lib/Service/Classification/ImportanceClassifier.php
  lib/Service/Classification/PersistenceService.php
Labels: 3. to review, bug

#2923 Fix/925/isp autoconfiguration server
  lib/Service/AutoConfig/IspDb.php
  lib/Service/AutoConfig/IspDbConfigurationDetector.php
  tests/Unit/Service/Autoconfig/IspDbTest.php
Labels: 4. to release, bug

#3129 Paginate all priority inbox sections
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  src/components/MailboxMessage.vue
  src/store/actions.js
Labels: 3. to review, enhancement, feature:priority inbox, priority

#3180 Remove bountysource references
  .github/FUNDING.yml
  README.md
Labels: 3. to review

#3181 Remove the BootstrapSingleton
  lib/AppInfo/Application.php
  lib/AppInfo/BootstrapSingleton.php
Labels: 3. to review, technical debt

#3158 Display account quota
  appinfo/routes.php
  lib/Contracts/IMailManager.php
  lib/Controller/AccountsController.php
  lib/Http/JsonResponse.php
  lib/Service/AccountService.php
  lib/Service/MailManager.php
  lib/Service/Quota.php
  src/components/NavigationAccount.vue
  src/service/AccountService.js
  tests/Unit/Controller/AccountsControllerTest.php
Labels: 3. to review, enhancement

#3198 Fix CKEditor for stable1.4
  package-lock.json
  package.json
Labels: 3. to review, bug, priority, regression

#3215 Fix CKEditor 19 on master
  package-lock.json
  package.json
Labels: 3. to review, bug, dependencies, priority, technical debt

#3208 Fix formatting when it is checked individually from the account default
  src/components/Composer.vue
Labels: 3. to review, blocked

#3218 Update Changelog for v1.4.0
  CHANGELOG.md
Labels: 3. to review, backport-request

#3221 Also catch throwable's during account sync
  lib/Listener/NewMessageClassificationListener.php
Labels: 3. to review

#3227 Show unread messages in bold
  src/components/Envelope.vue
Labels: 3. to review, backport-request, bug, design

#3228 Fix icon color in dark theme
  css/mail.scss
  img/inbox.svg
  img/trash.svg
Labels: 3. to review, backport-request, bug, design

#3233 Fix "tab" typo in translation
  src/components/MessageHTMLBody.vue
Labels: 4. to release, bug

#3234 Fix inconsistend wording Spam vs Junk
  src/components/Message.vue
Labels: 4. to release, backport-request

#3263 Make the importance classifier training more debuggable
  lib/BackgroundJob/TrainImportanceClassifierJob.php
  lib/Command/TrainAccount.php
  lib/Service/Classification/ImportanceClassifier.php
  lib/Support/ConsoleLoggerDecorator.php
Labels: 3. to review, backport-request

#3269 Make sure a sender exists AND it has an email
  lib/Service/Classification/ImportanceClassifier.php
  lib/Service/Classification/ImportanceRulesClassifier.php
Labels: 3. to review, backport-request, bug

#3290 Add action menu for new created folders
  src/components/NavigationFolder.vue
Labels: 3. to review, backport-request, bug

#3300 Add the missing `References` header for sent messages
  lib/Service/MailTransmission.php
Labels: 3. to review, backport-request, bug

#3331 Add more debug logging to classification persistance
  lib/Service/Classification/PersistenceService.php
Labels: 3. to review, backport-request
