Repository nextcloud/mail, pull requests merged in 2020-11, with the labels that each got.

#3820 Store special mailboxes as preference of the account
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Contracts/IMailManager.php
  lib/Contracts/IMailTransmission.php
  lib/Controller/AccountsController.php
  lib/Db/MailAccount.php
  lib/Db/MailboxMapper.php
  lib/Events/MailboxesSynchronizedEvent.php
  lib/Events/MessageSentEvent.php
  lib/Exception/DraftsMailboxNotSetException.php
  lib/Exception/SentMailboxNotSetException.php
  lib/Exception/TrashMailboxNotSetException.php
  lib/IMAP/MailboxSync.php
  lib/Listener/DeleteDraftListener.php
  lib/Listener/DraftMailboxCreatorListener.php
  lib/Listener/MailboxesSynchronizedSpecialMailboxesUpdater.php
  lib/Listener/SaveSentMessageListener.php
  lib/Listener/TrashMailboxCreatorListener.php
  lib/Migration/Version1060Date20201015084952.php
  lib/Service/Classification/ImportanceClassifier.php
  lib/Service/MailManager.php
  lib/Service/MailTransmission.php
  package-lock.json
  package.json
  src/components/AccountDefaultsSettings.vue
  src/components/Composer.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  src/components/MailboxInlinePicker.vue
  src/components/Navigation.vue
  src/components/ThreadEnvelope.vue
  src/errors/NoDraftsMailboxConfiguredError.js
  src/errors/NoSentMailboxConfiguredError.js
  src/errors/NoTrashMailboxConfiguredError.js
  src/errors/convert.js
  src/main.js
  src/service/MessageService.js
  src/views/AccountSettings.vue
  tests/Integration/Db/MailAccountTest.php
  tests/Integration/Db/MailboxMapperTest.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Unit/IMAP/MailboxSyncTest.php
  tests/Unit/Listener/DeleteDraftListenerTest.php
  tests/Unit/Listener/DraftMailboxCreatorListenerTest.php
  tests/Unit/Listener/SaveSentMessageListenerTest.php
  tests/Unit/Listener/TrashMailboxCreatorListenerTest.php
  tests/Unit/Service/MailManagerTest.php
  tests/Unit/Service/MailTransmissionTest.php
Labels: 3. to review, enhancement, feature parity, priority:high

#3912 [stable1.5] Use a Github action for integration tests
  .github/workflows/lint.yml
  .github/workflows/package.yml
  .github/workflows/test.yml
  .nextcloudignore
  .scrutinizer.yml
  .travis.yml
  Makefile
  codecov.yml
  lib/Account.php
  tests/Integration/Framework/ImapTest.php
  tests/Integration/Framework/ImapTestAccount.php
  tests/Integration/IMAP/AbstractTest.php
  tests/Integration/IMAP/IMAPClientFactoryTest.php
  tests/Integration/Service/FolderMapperIntegrationTest.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Integration/TestCase.php
Labels: 3. to review, priority:high

#3902 Fix css being shown as text in reply
  package-lock.json
  package.json
  src/components/TextEditor.vue
Labels: 4. to release, bug

#3943 Revert partial update of CKEditor to v23.1
  package-lock.json
  package.json
Labels: bug, dependencies, priority:high, regression

#3947 Remove --hide-modules flag from build script
  package.json
Labels: 3. to review, technical debt

#3914 Update the Makefile docker test image
  Makefile
Labels: 4. to release, technical debt

#3563 Show avatars in search results
  lib/Search/Provider.php
Labels: 4. to release, filter:search

#3946 Build a dev version for a dev build, not a production version
  Makefile
Labels: 3. to review, technical debt

#3910 Run sync once after moving envelopes
  src/components/MoveModal.vue
Labels: 3. to review, bug

#3915 Fix redirect after moving thread envelope
  src/components/MoveModal.vue
  src/components/Thread.vue
  src/components/ThreadEnvelope.vue
Labels: 3. to review, bug

#3957 Run tests, static analysis and packaging workflows for all PRs
  .github/workflows/package.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
Labels: 3. to review, priority:high, technical debt

#3955 Clean up badges
  README.md
Labels: 3. to review, technical debt

#3953 Fix potentially duplicate keys in navigation by scoping the key
  src/components/Navigation.vue
Labels: 4. to release, bug, priority:high

#3879 Fix to cannot save several attachments to Files
  lib/Controller/MessagesController.php
  src/service/AttachmentService.js
  tests/Unit/Controller/MessagesControllerTest.php
Labels: 4. to release, backport-request, bug, priority:high

#3825 Fixes an issue where forwarded messages' body isn't built properly
  src/components/Composer.vue
Labels: 4. to release, backport-request, priority:high

#3945 Rename $id to $uid to prevent ambiguity
  lib/Mailbox.php
  lib/Service/IMailBox.php
Labels: 3. to review, priority:low, technical debt

#3962 Drop the unused IMailBox interface
  lib/Mailbox.php
  lib/Service/IMailBox.php
Labels: 3. to review, technical debt

#3963 Remove the composer intall from the Makefile
  Makefile
Labels: 3. to review, bug

#3964 Remove dead methods from the Mailbox class
  lib/Account.php
  lib/Mailbox.php
  tests/Integration/IMAP/AbstractTest.php
Labels: 3. to review, technical debt

#3954 Select multiple envelopes at once using shift
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
Labels: 3. to review, enhancement

#3989 Revert partial update of CKEditor to v23.1 again
  package-lock.json
  package.json
Labels: 3. to review, priority:high, regression

#3969 Catch no account in envelope and console log spam
  src/components/Envelope.vue
Labels: 3. to review, bug, priority:high

#3966 Fix seen vs unseen mixup
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  src/components/ThreadEnvelope.vue
  src/store/actions.js
  tests/Unit/Controller/MessagesControllerTest.php
Labels: 3. to review, bug, priority:high

#3986 Prevent account settings reuse when account changes
  src/views/AccountSettings.vue
Labels: 3. to review, bug, priority:high

#3985 Update changelog for v1.6.0
  CHANGELOG.md
Labels: 3. to review, enhancement, priority:high

#3992 Update changelog for v1.5.2
  CHANGELOG.md
Labels: 3. to review, backport-request, enhancement

#4002 Link to user and dev docs as well on the app store
  appinfo/info.xml
Labels: 3. to review, backport-request, enhancement, priority:medium

#4001 Document how admins can collect troubleshoot information
  doc/admin.md
Labels: 3. to review, enhancement, priority:medium

#3965 Allow composing new messages based on existing ones
  src/components/Envelope.vue
  src/components/MailboxThread.vue
  src/components/NewMessageDetail.vue
  src/components/ThreadEnvelope.vue
Labels: 2. developing, enhancement, feature parity, priority:medium

#3995 Handle null email address before iconv conversion
  lib/Address.php
Labels: 3. to review, backport-request, bug, regression

#4003 Improve html message rendering
  lib/Service/Html.php
Labels: 2. developing, backport-request, bug

#4012 Bump CKEditor to v23.1
  package-lock.json
  package.json
Labels: 3. to review, dependencies, enhancement, priority:medium

#3904 Responsive mail iframe
  css/html-response.css
  lib/Controller/MessagesController.php
  lib/Http/HtmlResponse.php
  package-lock.json
  package.json
  src/components/Message.vue
  src/components/MessageHTMLBody.vue
  src/components/NewMessageDetail.vue
  src/components/Thread.vue
  src/components/ThreadEnvelope.vue
  src/html-response.js
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Http/HtmlResponseTest.php
  webpack.common.js
Labels: 2. developing, design, enhancement, priority:high

#4017 Drop php7.2 from CI and info.xml
  .github/workflows/lint.yml
  appinfo/info.xml
Labels: 3. to review, technical debt

#4015 Fix envelope timestamp overlap
  src/store/mutations.js
  src/tests/unit/store/mutations.spec.js
Labels: 2. developing, bug, priority:high

#4016 Clean up HTML response
  lib/Controller/MessagesController.php
  lib/Http/HtmlResponse.php
  psalm.xml
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Http/HtmlResponseTest.php
Labels: 3. to review, technical debt

#4043 Bump @nextcloud/vue to v3
  package-lock.json
  package.json
Labels: 3. to review, dependencies, enhancement

#3897 Add the posibility to move mailboxes
  src/components/MailboxPicker.vue
  src/components/MoveMailboxModal.vue
  src/components/NavigationMailbox.vue
Labels: 3. to review, enhancement

#4051 Remove the borders from cc bcc
  src/components/Composer.vue
Labels: 3. to review, bug, design

#4050 Fix auto manual account styling
  src/components/AccountForm.vue
Labels: 3. to review, bug, design, regression

#4046 Fix thread scrolling
  src/components/ThreadEnvelope.vue
Labels: 3. to review, bug, design, regression

#4044 Always show Mail search results first
  lib/Search/Provider.php
Labels: 3. to review, backport-request, bug, filter:search, priority:medium

#4058 Fix icon styling for reply button
  src/components/ThreadEnvelope.vue
Labels: 4. to release, bug, design

#3952 Store collapsed-folder settings
  lib/Controller/PageController.php
  src/components/NavigationAccountExpandCollapse.vue
  src/main.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  templates/index.php
  tests/Unit/Controller/PageControllerTest.php
Labels: 3. to review, enhancement, priority:medium

#4057 Store selection by envelope database id
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
Labels: 3. to review, bug, priority:high

#4065 Fix/3829 Saving Signatures
  src/components/SignatureSettings.vue
Labels: 3. to review, backport-request, bug, regression

#4096 Add troubleshooting for mysql insert errors
  doc/admin.md
Labels: 3. to review

#4100 Add debug logs for mailbox locking/unlocking
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: 3. to review, enhancement

#4099 Catch when iconv returns false
  lib/Address.php
Labels: 3. to review

#4049 Adds the ckeditor list plugin
  package-lock.json
  package.json
  src/components/TextEditor.vue
Labels: 4. to release, enhancement

#4105 Recommend gzip compression for exported threads data
  doc/admin.md
Labels: 3. to review

#3745 Prevent Thread's avatar header to overlap message's sender and subject.
  src/components/Thread.vue
Labels: 3. to review, bug, design

#4129 Add route for drafts
  appinfo/routes.php
  lib/Controller/PageController.php
Labels: 3. to review, bug

#4118 Fix previous drafts not being deleted from the cache
  lib/Listener/DeleteDraftListener.php
  src/components/NewMessageDetail.vue
  tests/Unit/Listener/DeleteDraftListenerTest.php
Labels: 3. to review, backport-request, bug, regression

#4128 Fix mailto route
  appinfo/routes.php
  lib/Controller/PageController.php
  tests/Unit/Controller/PageControllerTest.php
Labels: 2. developing, backport-request, bug

#4150 Bring back more php7.2 compatibility for some Nextcloud 20 instances
  .github/workflows/lint.yml
  lib/Http/HtmlResponse.php
  tests/Unit/Controller/MessagesControllerTest.php
Labels: 3. to review, bug, regression

#4048 Drag and Drop (revisited)
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/NavigationMailbox.vue
  src/components/SignatureSettings.vue
  src/directives/drag-and-drop/draggable-envelope/draggable-envelope.js
  src/directives/drag-and-drop/draggable-envelope/index.js
  src/directives/drag-and-drop/droppable-mailbox/droppable-mailbox.js
  src/directives/drag-and-drop/droppable-mailbox/index.js
  src/directives/drag-and-drop/styles/drag-and-drop.scss
  src/directives/drag-and-drop/styles/draggable-envelope.scss
  src/directives/drag-and-drop/styles/droppable-mailbox.scss
  src/directives/drag-and-drop/util/dragEventBus.js
  src/main.js
Labels: 4. to release, enhancement, feature parity, priority:medium

#4149 Handle special mailbox sync when they don't exist
  lib/Listener/MailboxesSynchronizedSpecialMailboxesUpdater.php
Labels: 3. to review, bug, priority:medium

#4136 Attachments: Allow selecting multiple Mail attachments (CTRL)
  src/components/ComposerAttachments.vue
Labels: 3. to review, enhancement, priority:low

#4154 Fix initializing the editor mode
  src/components/Composer.vue
Labels: 3. to review, backport-request, bug, priority:medium, regression
