Repository nextcloud/mail, pull requests merged in 2021-04, with the labels that each got.

#4896 Avoid double testing with pushes
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
Labels: 3. to review, enhancement

#4901 Fix updateEnvelope mutation
  src/store/mutations.js
Labels: 3. to review, backport-request, bug

#4903 Change `mail_accounts.provisioned` column to allow null
  lib/Db/Classifier.php
  lib/Db/MailAccount.php
  lib/Db/Mailbox.php
  lib/Db/Message.php
  lib/Db/Tag.php
  lib/Migration/Version0190Date20191118160843.php
  lib/Migration/Version1020Date20191002091035.php
  lib/Migration/Version1020Date20200206134751.php
  lib/Migration/Version1040Date20200422142920.php
  lib/Migration/Version1040Date20200506111214.php
  lib/Migration/Version1040Date20200515080614.php
  lib/Migration/Version1050Date20200923180030.php
  lib/Migration/Version1080Date20210108093802.php
  lib/Migration/Version1090Date20210127160127.php
  lib/Migration/Version1100Date20210406144257.php
  lib/Service/Classification/ImportanceClassifier.php
Labels: 2. developing, bug, priority:high

#4905 Use predefined query builder functions
  lib/Db/CollectedAddressMapper.php
  lib/Db/MessageMapper.php
Labels: 3. to review, technical debt

#4840 Rework duplicate entry handling for tags
  lib/Db/MessageMapper.php
  lib/Db/TagMapper.php
  lib/Migration/Version1100Date20210304143008.php
  lib/Migration/Version1100Date20210326103929.php
  lib/Service/Classification/ImportanceClassifier.php
  lib/Service/CleanupService.php
  lib/Service/Search/MailSearch.php
  lib/Service/Sync/SyncService.php
  tests/Unit/Service/Search/MailSearchTest.php
  tests/psalm-baseline.xml
Labels: 3. to review, enhancement, priority:high

#4895 Update dependabot-approve.yml to dependabot-approve-merge.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/dependabot-approve.yml
Labels: 3. to review, dependencies, enhancement

#4906 Chunk huge arrays to surpress Oracle IN() warning
  lib/Db/MessageMapper.php
  tests/psalm-baseline.xml
Labels: 3. to review, technical debt

#4899 Cleanup internal alias api
  lib/Controller/AliasesController.php
  lib/Service/AliasesService.php
  tests/Unit/Controller/AliasesControllerTest.php
  tests/Unit/Service/AliasesServiceTest.php
Labels: 4. to release, technical debt

#4912 Add an array_flat_map function
  composer.json
  lib/Db/MessageMapper.php
  lib/functions.php
  tests/Unit/FunctionsTest.php
Labels: 4. to release, enhancement

#4900 Only update direct dependencies for vendor-bin
  .github/dependabot.yml
Labels: 3. to review, technical debt

#4902 Normalize envelope tags in vuex store
  lib/Controller/MessagesController.php
  src/components/Envelope.vue
  src/components/MenuEnvelope.vue
  src/components/ThreadEnvelope.vue
  src/service/MessageService.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  src/tests/unit/store/mutations.spec.js
Labels: 4. to release, technical debt

#4910 Split migrations for backport
  lib/Migration/Version1096Date20210407150016.php
  lib/Migration/Version1100Date20210406144257.php
  lib/Migration/Version1100Date20210409091311.php
Labels: 4. to release, backport-request, priority:high

#4944 Add filtered routes for draft and thread
  appinfo/routes.php
  lib/Controller/PageController.php
Labels: 3. to review, backport-request, bug

#4953 Remove Jans test (for now)
  tests/Integration/Service/AvatarServiceIntegrationTest.php
Labels: 4. to release, bug

#4952 Fix/filter forwarded and nonjunk tag
  lib/Model/IMAPMessage.php
Labels: 4. to release, bug

#4898 Signatures for aliases
  appinfo/info.xml
  appinfo/routes.php
  lib/Controller/AliasesController.php
  lib/Db/Alias.php
  lib/Db/AliasMapper.php
  lib/Migration/Version1100Date20210317164707.php
  lib/Service/AliasesService.php
  src/components/Composer.vue
  src/components/SignatureSettings.vue
  src/service/AliasService.js
  src/store/actions.js
  src/store/mutations.js
  tests/Integration/Db/AliasMapperTest.php
  tests/Unit/Controller/AliasesControllerTest.php
  tests/Unit/Service/AliasesServiceTest.php
Labels: 4. to release, enhancement

#4966 Exit early if no message ids are to be fixed
  lib/Migration/AddMissingMessageIds.php
Labels: 3. to review, backport-request

#4932 Move recipient delete to separate query
  lib/Db/MessageMapper.php
Labels: 3. to review

#4971 add option to place signature above quoted text
  lib/Controller/AccountsController.php
  lib/Db/MailAccount.php
  lib/Migration/Version1100Date20210421113423.php
  src/ReplyBuilder.js
  src/ckeditor/quote/QuotePlugin.js
  src/ckeditor/signature/InsertSignatureCommand.js
  src/components/Composer.vue
  src/components/SignatureSettings.vue
  src/components/TextEditor.vue
  src/store/index.js
  src/tests/unit/ReplyBuilder.spec.js
  src/util/text.js
  tests/Integration/Db/MailAccountTest.php
Labels: 3. to review, enhancement

#4510 Reloads the envelope list when user clicks on the folder they are currently in
  src/components/Mailbox.vue
Labels: 3. to review, bug

#4982 Correctly truncate multibyte strings to fit into the database
  lib/Db/MessageMapper.php
  lib/Model/IMAPMessage.php
Labels: 3. to review, backport-request, bug, php

#4988 Remove obsolete workflow lint/app-code-check
  .github/workflows/lint.yml
Labels: 3. to review, technical debt

#4969 Reintroduce unread counter in app navigation
  lib/Contracts/IMailManager.php
  lib/Controller/MailboxesController.php
  lib/Db/Mailbox.php
  lib/Folder.php
  lib/IMAP/FolderMapper.php
  lib/IMAP/MailboxStats.php
  lib/IMAP/MailboxSync.php
  lib/IMAP/Sync/Response.php
  lib/Service/MailManager.php
  lib/Service/Sync/SyncService.php
  src/components/NavigationMailbox.vue
  src/service/MessageService.js
  src/store/actions.js
  src/store/mutations.js
  tests/Unit/Controller/MailboxesControllerTest.php
  tests/Unit/IMAP/FolderMapperTest.php
  tests/Unit/IMAP/MailboxSyncTest.php
  tests/Unit/IMAP/Sync/ResponseTest.php
  tests/Unit/Service/MailManagerTest.php
  tests/Unit/Service/Sync/SyncServiceTest.php
Labels: 3. to review, enhancement, feature parity
