Repository nextcloud/mail, pull requests merged in 2021-05, with the labels that each got.

#5011 Fix reading missing mailbox stats
  lib/IMAP/MailboxSync.php
Labels: 4. to release, backport-request, bug

#5053 Drop node sass, use only sass
  package-lock.json
  package.json
Labels: 3. to review, bug

#4894 Show tags
  lib/Db/TagMapper.php
  package-lock.json
  package.json
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  src/service/MessageService.js
Labels: 3. to review, enhancement, priority:high

#5010 Add bg job for label sync
  lib/BackgroundJob/MigrateImportantJob.php
  lib/Db/MailboxMapper.php
  lib/IMAP/MessageMapper.php
  lib/Listener/DeleteDraftListener.php
  lib/Listener/FlagRepliedMessageListener.php
  lib/Migration/MigrateImportantFromImapAndDb.php
  lib/Migration/Version1100Date20210512142306.php
  lib/Service/MailManager.php
  lib/Service/Sync/SyncService.php
  tests/Integration/Framework/ImapTest.php
  tests/Integration/IMAP/MessageMapperTest.php
  tests/Integration/Migration/MigrateImportantFromImapAndDbTest.php
  tests/Unit/IMAP/MessageMapperTest.php
  tests/Unit/Job/TestMigrateImportantJob.php
  tests/Unit/Listener/DeleteDraftListenerTest.php
  tests/Unit/Listener/FlagRepliedMessageListenerTest.php
  tests/Unit/Migration/MigrateImportantFromImapAndDbTest.php
  tests/Unit/Service/MailManagerTest.php
Labels: 3. to review, enhancement

#5073 Load accounts and their settings via initial state
  lib/Controller/PageController.php
  src/main.js
  tests/Unit/Controller/PageControllerTest.php
Labels: 3. to review, technical debt

#4947 Chunking `in` statements for Oracle Compliance
  lib/Db/AliasMapper.php
  lib/Db/CollectedAddressMapper.php
  lib/Db/MailboxMapper.php
  lib/Db/MessageMapper.php
  lib/Db/TagMapper.php
  tests/psalm-baseline.xml
Labels: 4. to release, backport-request

#5075 Fix decoding emtpy account settings
  lib/Controller/PageController.php
Labels: 3. to review, bug, regression

#4968 Add multi account provisioning
  appinfo/info.xml
  appinfo/routes.php
  lib/BackgroundJob/SyncJob.php
  lib/BackgroundJob/TrainImportanceClassifierJob.php
  lib/Command/DeleteAccount.php
  lib/Controller/SettingsController.php
  lib/Db/MailAccount.php
  lib/Db/MailAccountMapper.php
  lib/Db/Provisioning.php
  lib/Db/ProvisioningMapper.php
  lib/Exception/ValidationException.php
  lib/Http/Middleware/ProvisioningMiddleware.php
  lib/Migration/AddSieveToProvisioningConfig.php
  lib/Migration/MigrateProvisioningConfig.php
  lib/Migration/ProvisionAccounts.php
  lib/Migration/Version1100Date20210419080523.php
  lib/Migration/Version1100Date20210419121734.php
  lib/Service/Provisioning/Config.php
  lib/Service/Provisioning/ConfigMapper.php
  lib/Service/Provisioning/Manager.php
  lib/Settings/AdminSettings.php
  src/components/settings/AdminSettings.vue
  src/components/settings/ProvisionPreview.vue
  src/components/settings/ProvisioningSettings.vue
  src/main-settings.js
  src/service/SettingsService.js
  tests/Integration/Db/MailAccountMapperTest.php
  tests/Integration/Db/MailAccountTest.php
  tests/Integration/Db/ProvisioningMapperTest.php
  tests/Unit/Controller/SettingsControllerTest.php
  tests/Unit/Http/Middleware/ProvisioningMiddlewareTest.php
  tests/Unit/Migration/AddSieveToProvisioningConfigTest.php
  tests/Unit/Migration/MigrateProvisioningConfigTest.php
  tests/Unit/Service/Provisioning/ConfigMapperTest.php
  tests/Unit/Service/Provisioning/ConfigTest.php
  tests/Unit/Service/Provisioning/ManagerTest.php
Labels: 4. to release, enhancement, priority:high

#5079 Fix the page controller test after #5075
  tests/Unit/Controller/PageControllerTest.php
Labels: 3. to review, technical debt

#5078 Fix loading tags and clean up related tests
  lib/Db/TagMapper.php
  tests/Integration/IMAP/MessageMapperTest.php
  tests/Integration/MailboxSynchronizationTest.php
Labels: 3. to review, priority:high, technical debt

#4829 Add UI for tag assignment
  lib/Controller/MessagesController.php
  lib/Controller/PageController.php
  src/components/Envelope.vue
  src/components/MenuEnvelope.vue
  src/components/TagModal.vue
  src/main.js
  src/service/MessageService.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  src/tests/unit/store/getters.spec.js
  src/tests/unit/store/mutations.spec.js
  tests/Unit/Controller/PageControllerTest.php
Labels: 4. to release, enhancement, feature parity

#5083 Add new personalized tags
  appinfo/routes.php
  lib/Controller/TagsController.php
  lib/Db/TagMapper.php
  lib/Model/IMAPMessage.php
  src/components/Envelope.vue
  src/components/TagModal.vue
  src/service/MessageService.js
  src/store/actions.js
Labels: 3. to review
