Repository nextcloud/mail, pull requests merged in 2021-07, with the labels that each got.

#5263 Fix infinite scoll loading, take II
  .github/workflows/lint.yml
  .github/workflows/package.yml
  package-lock.json
  package.json
  src/components/MailboxThread.vue
  src/directives/infinite-scroll.js
Labels: 4. to release, backport-request, bug, priority:high

#5267 [stable1.10] Fix infinite scoll loading, take II
  package-lock.json
  package.json
  src/components/MailboxThread.vue
  src/directives/infinite-scroll.js
Labels: 3. to review, bug, priority:high, regression

#5287 Add method exists check to migration and add occ command to migrate important tag
  appinfo/info.xml
  lib/Command/CreateTagMigrationJobEntry.php
  lib/Migration/Version1100Date20210512142306.php
  tests/psalm-baseline.xml
Labels: 4. to release, backport-request, bug

#5293 Add guide how to setup ldap, imap and provisioning
  doc/developer.md
  doc/ldap_ldapadmin.png
  doc/ldap_nc1.png
  doc/ldap_nc2.png
  doc/ldap_nc3.png
  doc/ldap_nc4.png
  doc/ldap_nc5.png
  doc/ldap_nc6.png
  doc/ldap_nc7.png
Labels: 3. to review, enhancement

#5311 Fix signature identation
  src/components/Thread.vue
Labels: 3. to review, bug

#5313 Bumb ckeditor 29
  package-lock.json
  package.json
Labels: 3. to review, dependencies, enhancement

#5292 Move userId to controller to fix tagging despite option disabled
  lib/AppInfo/Application.php
  lib/Contracts/IUserPreferences.php
  lib/Controller/PageController.php
  lib/Controller/PreferencesController.php
  lib/Listener/AddressCollectionListener.php
  lib/Listener/NewMessageClassificationListener.php
  lib/Service/AvatarService.php
  lib/Service/UserPreferenceService.php
  tests/Integration/Service/AvatarServiceIntegrationTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Controller/PreferencesControllerTest.php
  tests/Unit/Listener/AddressCollectionListenerTest.php
  tests/Unit/Service/AvatarServiceTest.php
  tests/Unit/Service/UserPreferenceServiceTest.php
Labels: 3. to review, bug

#5324 Improve ldap testing documentation
  doc/developer.md
Labels: 3. to review

#5329 Add html structure
  lib/Http/HtmlResponse.php
Labels: 3. to review, backport-request, bug

#5198 LDAP alias provisioning
  lib/Controller/AliasesController.php
  lib/Controller/SettingsController.php
  lib/Db/Alias.php
  lib/Db/AliasMapper.php
  lib/Db/Provisioning.php
  lib/Db/ProvisioningMapper.php
  lib/Migration/Version1101Date20210616141806.php
  lib/Service/AliasesService.php
  lib/Service/Provisioning/Manager.php
  lib/Settings/AdminSettings.php
  src/components/AccountSettings.vue
  src/components/AliasForm.vue
  src/components/AliasSettings.vue
  src/components/settings/ProvisioningSettings.vue
  src/service/AliasService.js
  src/store/actions.js
  src/store/mutations.js
  tests/Unit/Controller/AliasesControllerTest.php
  tests/Unit/Service/AliasesServiceTest.php
Labels: 3. to review, enhancement

#5328 Fix missing slash in sharing file generated url
  src/service/FileSharingService.js
Labels: 3. to review, bug, regression

#5336 Allow reply in quote block
  doc/ckeditor_inspector.png
  doc/developer.md
  src/ckeditor/quote/QuotePlugin.js
Labels: 3. to review, bug

#5338 [stable1.10] Pin mariadb to 10.5
  .github/workflows/test.yml
Labels: 3. to review, technical debt

#5339 Show inline attachments for plain text emails.
  lib/Model/IMAPMessage.php
Labels: 3. to review, bug

#5351 [stable1.9] Pin mariadb to 10.5
  .github/workflows/test.yml
Labels: 3. to review, technical debt

#5368 Fix calendar import
  src/service/DAVService.js
Labels: 3. to review, backport-request, bug

#5370 Add `$notjunk` flag to messages marked not junk and add `$junk` to messages marked junk
  src/store/actions.js
Labels: 3. to review, backport-request, bug, priority:high
