Repository nextcloud/mail, pull requests merged in 2021-12, with the labels that each got.

#5513 Move message composer into a modal
  css/mail.scss
  src/components/Composer.vue
  src/components/ComposerAttachments.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/MailboxThread.vue
  src/components/MenuEnvelope.vue
  src/components/Navigation.vue
  src/components/NewMessageDetail.vue
  src/components/NewMessageModal.vue
  src/components/RecipientBubble.vue
  src/views/Home.vue
Labels: enhancement, 2. developing, design

#5766 Collect `simpexml_load_string` errors and log them to debug
  lib/Service/AutoConfig/IspDb.php
Labels: bug, 3. to review

#5765 (Re)wrap message ID in '<>' brackets before inserting in the db
  lib/Db/Message.php
  tests/Integration/Db/MessageTest.php
Labels: bug, 3. to review, backport-request

#5770 [stable1.11] (Re)wrap message ID in '<>' brackets before inserting in the db
  lib/Db/Message.php
  tests/Integration/Db/MessageTest.php
Labels: bug, 3. to review

#5772 Drop Nextcloud 20 support
  .github/workflows/lint.yml
  .github/workflows/test.yml
  appinfo/info.xml
Labels: enhancement, 3. to review

#5783 Fetch LDAP provider factory on demand
  lib/Service/Provisioning/Manager.php
  tests/psalm-baseline.xml
Labels: bug, 4. to release, feature:integration, backport-request, regression

#5787 Upgrade static analysis from Nextcloud 20 to 21 min
  .github/workflows/static-analysis.yml
  composer.json
  composer.lock
Labels: 3. to review

#5788 Revert "Fetch LDAP provider factory on demand"
  lib/Service/Provisioning/Manager.php
  tests/psalm-baseline.xml
Labels: 3. to review

#5792 Fix save all attachments broken button
  src/components/MessageAttachments.vue
Labels: bug, 3. to review

#5777 Fix trusted domain regression
  src/components/MessageHTMLBody.vue
Labels: 3. to review, backport-request, regression

#5798 Fix initial sync stopping prematurely and endlessly
  lib/IMAP/MessageMapper.php
  tests/Unit/IMAP/MessageMapperTest.php
Labels: bug, 3. to review, priority:high, backport-request

#5808 Ckeditor31.1.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#5799 Fix MessageMapper mailbox_id type to be int
  lib/Db/MessageMapper.php
Labels: bug, 3. to review, backport-request

#5800 Add debug logs to the imap message mapper findByIds
  lib/IMAP/MessageMapper.php
  tests/Unit/IMAP/MessageMapperTest.php
Labels: 3. to review, backport-request

#5824 Add Psalm-generated return types
  lib/BackgroundJob/MigrateImportantJob.php
  lib/BackgroundJob/SyncJob.php
  lib/BackgroundJob/TrainImportanceClassifierJob.php
  lib/Cache/Cache.php
  lib/Controller/AliasesController.php
  lib/Controller/MailboxesController.php
  lib/Db/AliasMapper.php
  lib/Db/CollectedAddressMapper.php
  lib/Db/Message.php
  lib/Migration/AddMissingDefaultTags.php
  lib/Migration/FixBackgroundJobs.php
  lib/Migration/FixCollectedAddresses.php
  lib/Migration/MakeItineraryExtractorExecutable.php
  lib/Migration/ProvisionAccounts.php
  lib/Migration/Version0110Date20180825201241.php
  lib/Migration/Version0161Date20190902103701.php
  lib/Migration/Version0161Date20190902114635.php
  lib/Migration/Version1030Date20200228105714.php
  lib/Migration/Version1040Date20200422130220.php
  lib/Migration/Version1060Date20201015084952.php
  lib/Service/Search/SearchQuery.php
Labels: 4. to release, technical debt

#5825 Add Psalm-generated param types
  lib/Db/MessageMapper.php
  lib/IMAP/MessageMapper.php
  lib/Service/ContactsIntegration.php
Labels: 3. to review, technical debt

#5826 Update readme.md
  README.md
Labels: enhancement, 3. to review

#5828 Check for empty string in message id and reply to
  lib/Db/Message.php
  tests/Integration/Db/MessageTest.php
Labels: bug, 3. to review, feature:threading, backport-request

#5837 Add repair step to fix messages where `in_reply_to` has `<>` as content
  appinfo/info.xml
  lib/Command/RepairMailTheads.php
  lib/Db/MessageMapper.php
  tests/Integration/Db/MessageMapperTest.php
  tests/psalm-baseline.xml
Labels: bug, 3. to review, backport-request

#5840 Remove command to fix threads and make it a repair step instead.
  appinfo/info.xml
  lib/Migration/RepairMailTheads.php
Labels: bug, 3. to review, backport-request

#5846 Enforce issue templates, add links
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/question.md
Labels: 3. to review

#5848 Add the correct namespace
  appinfo/info.xml
  lib/Migration/RepairMailTheads.php
Labels: bug, 4. to release, backport-request

#5851 Add release automation
  .github/workflows/appstore-build-publish.yml
Labels: enhancement, 3. to review, backport-request

#5853 v.1.11.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#5854 Add composer 1 on appstore
  .github/workflows/appstore-build-publish.yml
Labels: backport-request

#5856 Catch unknown method during upgrade repair step
  lib/Migration/RepairMailTheads.php
Labels: bug, 4. to release, backport-request, regression

#5862 Use Parameters instead of Named Parameters for chunked queries
  lib/Db/AliasMapper.php
  lib/Db/MailboxMapper.php
  lib/Db/MessageMapper.php
  lib/Db/TagMapper.php
Labels: bug, 3. to review, backport-request

#5869 Update throws annotations in ProvisioningManager
  lib/Service/Provisioning/Manager.php
Labels: 3. to review, technical debt

#5843 Fix mark as spam display
  lib/Db/Message.php
  src/components/Envelope.vue
  src/components/MenuEnvelope.vue
  src/components/ThreadEnvelope.vue
  src/store/actions.js
  tests/Unit/Listener/MessageCacheUpdaterListenerTest.php
Labels: bug, 3. to review, backport-request

#5866 Chunk the recipients query
  lib/Db/MessageMapper.php
Labels: bug, 2. developing, backport-request

#5889 Rename master to main
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  appinfo/info.xml
Labels: enhancement, 3. to review

#5864 Fix column for account name too narrow
  appinfo/info.xml
  lib/Migration/Version1115Date20211216144446.php
Labels: bug, 4. to release, backport-request

#5899 Fix package workflow
  .github/workflows/package.yml
Labels: bug, 3. to review

#5890 [stable1.11] Fix mark as spam
  lib/Db/Message.php
  src/components/Envelope.vue
  src/components/MenuEnvelope.vue
  src/components/ThreadEnvelope.vue
  src/store/actions.js
  tests/Unit/Listener/MessageCacheUpdaterListenerTest.php
Labels: bug, 3. to review

#5902 Add check for account id on removing mailbox prefix
  src/store/mutations.js
Labels: bug, 3. to review

#5909 Update installation and contributors info in readme
  README.md
  doc/admin.md
Labels: 3. to review

#5910 Update info.xml authors with new maintainer and co-maintainers
  appinfo/info.xml
Labels: 3. to review

#5911 Release v1.11.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: enhancement, 3. to review
