Repository nextcloud/mail, pull requests merged in 2021-06, with the labels that each got.

#5101 Fix tagging UI
  src/components/TagModal.vue
Labels: 2. developing

#5107 Fix mark (un)important action on envelope list
  lib/Db/Message.php
  src/components/Envelope.vue
  src/components/MenuEnvelope.vue
  src/store/actions.js
Labels: 3. to review, bug

#5104 Refactor create and update tag
  lib/Contracts/IMailManager.php
  lib/Controller/MessagesController.php
  lib/Controller/TagsController.php
  lib/Service/MailManager.php
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Controller/TagsControllerTest.php
  tests/Unit/Service/MailManagerTest.php
Labels: 3. to review, bug

#5111 Do not run background syncs for disabled users
  lib/BackgroundJob/SyncJob.php
  tests/Unit/BackgroundJob/SyncJobTest.php
Labels: 3. to review, bug

#5135 Show tags inside threads
  src/components/ThreadEnvelope.vue
Labels: 3. to review, enhancement

#5137 Update Vue and vue-template-compiler to 2.6.14
  package-lock.json
  package.json
Labels: 3. to review, priority:high

#5080 Adds support for text/calendar attachment
  lib/Attachment.php
  lib/Model/IMAPMessage.php
Labels: 3. to review

#5152 Bump CKEditor from v27.1 to v28.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#5106 Only show each thread once per message list
  appinfo/routes.php
  lib/Contracts/IMailManager.php
  lib/Controller/MessagesController.php
  lib/Controller/ThreadController.php
  lib/Db/MessageMapper.php
  lib/Db/ThreadMapper.php
  lib/Service/MailManager.php
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  src/components/MenuEnvelope.vue
  src/components/MoveModal.vue
  src/components/Thread.vue
  src/service/ThreadService.js
  src/store/actions.js
  tests/Unit/Controller/ThreadControllerTest.php
  tests/Unit/Service/MailManagerTest.php
  tests/psalm-baseline.xml
Labels: 4. to release, enhancement

#5167 Added plural to string
  src/components/settings/AdminSettings.vue
Labels: 3. to review, bug

#5168 Replaced provisioned with new provisioningId
  src/components/AccountSettings.vue
Labels: 3. to review, bug

#5179 Add validation to account patching
  lib/Controller/AccountsController.php
  lib/Service/AccountService.php
Labels: 3. to review

#5175 Wrap Exceptions in ServiceException and remove Throwable exception
  lib/Listener/NewMessageClassificationListener.php
  lib/Service/Classification/PersistenceService.php
Labels: 4. to release, papercut

#5180 Removes a duplicate definition of 'page#index' route
  appinfo/routes.php
Labels: bug

#5183 Document MailboxSync::persist arguments
  lib/IMAP/MailboxSync.php
Labels: 3. to review

#5184 Cast Evolution Labels to our implementation
  lib/Db/Tag.php
  lib/Model/IMAPMessage.php
Labels: 3. to review, enhancement, feature parity

#5186 Specify which account had a sync error
  lib/IMAP/MailboxSync.php
Labels: 3. to review, enhancement

#5187 Lower the chunk size for IMAP syncs
  lib/IMAP/Sync/Synchronizer.php
  tests/Unit/IMAP/Sync/SynchronizerTest.php
Labels: 4. to release, bug

#5188 Remove account-settings, accounts and debug inputs
  templates/index.php
Labels: 4. to release, bug

#5195 Bump @nextcloud/vue to 4.0.2
  package-lock.json
  package.json
  src/components/MailboxThread.vue
Labels: 3. to review, dependencies

#5201 Implement resizable columns
  src/components/MailboxThread.vue
  src/components/Thread.vue
  src/components/ThreadEnvelope.vue
Labels: 3. to review

#5204 Change "add tag" to "edit tag"
  src/components/Envelope.vue
  src/components/TagModal.vue
Labels: 3. to review, enhancement

#5206 Tags do not have $
  lib/Model/IMAPMessage.php
  lib/Service/MailManager.php
  tests/Unit/Service/MailManagerTest.php
Labels: 4. to release, bug

#5174 Tag messages in classifier
  lib/Contracts/IMailManager.php
  lib/Db/MessageMapper.php
  lib/Db/TagMapper.php
  lib/Listener/NewMessageClassificationListener.php
  lib/Model/IMAPMessage.php
  lib/Service/MailManager.php
  lib/Service/Sync/ImapToDbSynchronizer.php
  tests/psalm-baseline.xml
Labels: 2. developing, enhancement

#5189 Sanitize urls in css style sheets
  composer.json
  composer.lock
  lib/Service/Html.php
  lib/Service/HtmlPurify/TransformStyleURLs.php
  src/components/MessageHTMLBody.vue
  tests/Unit/Service/HtmlTest.php
Labels: 3. to review, backport-request, bug, feature: HTML mails, security

#5218 Fix active state border
  src/components/Envelope.vue
Labels: 3. to review, bug

#5221 Handle missing fullname in contacts integration
  lib/Service/ContactsIntegration.php
Labels: 3. to review, bug

#5216 Fix reply icon on answered messages
  src/components/Envelope.vue
Labels: 3. to review, bug

#5223 Fix thread envelope active state background colour
  src/components/ThreadEnvelope.vue
Labels: 3. to review, bug

#5229 Test against nc 23
  .github/workflows/test.yml
Labels: 3. to review, enhancement

#5237 Fix thread max width
  src/views/Home.vue
Labels: 4. to release, bug, regression

#5238 Add needed props to AppContentDetails
  src/components/Mailbox.vue
  src/components/MailboxThread.vue
  src/views/Home.vue
Labels: 3. to review, backport-request, bug

#5252 Remove obsolete AppDetailsToggle component
  src/components/AppDetailsToggle.vue
Labels: 3. to review, backport-request, technical debt

#4946 Backport #4910 to 1.9
  lib/Db/MailAccount.php
  lib/Db/Mailbox.php
  lib/Db/Message.php
  lib/Migration/Version1096Date20210407150016.php
  lib/Service/Classification/ImportanceClassifier.php
Labels: 3. to review, backport-request
