Repository nextcloud/mail, pull requests merged in 2021-11, with the labels that each got.

#5687 Bump ckeditor and peers from 30.0.0 to 31.0.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#5668 Mark multiple messages as (not) important
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/store/actions.js
Labels: enhancement, 3. to review

#5698 Bump babel and peers from 7.15.8 to 7.16.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#5702 Force max-width for iframe content to fix some newsletters
  src/html-response.js
Labels: bug, 3. to review, backport-request

#5709 Fix text detection with null or undefined string
  src/util/text.js
Labels: bug, 3. to review, backport-request

#5571 Consider itinerary timezones when importing into the calendar
  src/components/itinerary/CalendarImport.vue
  src/components/itinerary/FlightReservation.vue
  src/components/itinerary/TrainReservation.vue
Labels: bug, 3. to review

#5715 Update to Nextcloud coding standard v1
  .gitignore
  .php-cs-fixer.dist.php
  lib/BackgroundJob/SyncJob.php
  lib/Db/TagMapper.php
  lib/Migration/Version1100Date20210419080523.php
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Listener/AddressCollectionListenerTest.php
  tests/Unit/Service/MailManagerTest.php
  tests/Unit/Service/MailTransmissionTest.php
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
Labels: 3. to review

#5718 Update version on master
  appinfo/info.xml
Labels: 4. to release

#5730 Fix composer regression
  src/components/TextEditor.vue
Labels: bug, 3. to review, backport-request, regression

#5733 Fix box-shadow for dark theme
  src/components/ThreadEnvelope.vue
Labels: enhancement, 4. to release

#5744 Fix iframe after printing
  src/components/MessageHTMLBody.vue
  src/components/Thread.vue
Labels: bug, 4. to release, backport-request
