Repository nextcloud/mail, pull requests merged in 2021-02, with the labels that each got.

#4441 Bump CKEditor to 25
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#4444 Backport recent l10n to stable1.8
  l10n/eu.js
  l10n/eu.json
  l10n/zh_HK.js
  l10n/zh_HK.json
Labels: 3. to review, enhancement

#4310 Show unread messages bold on dashboard
  src/components/Dashboard.vue
Labels: 3. to review, design, enhancement

#4382 Unify action menu icons
  src/components/MenuEnvelope.vue
  src/components/ThreadEnvelope.vue
Labels: 3. to review, design, enhancement

#4384 Fix text alignment on settings
  src/components/AppSettingsMenu.vue
Labels: 3. to review, bug, design

#4345 Fix plural action labels
  src/components/EnvelopeList.vue
Labels: 3. to review, enhancement

#4407 fixes an issue where attachment sent would not be the one selected
  src/components/ComposerAttachments.vue
Labels: 3. to review, backport-request, bug, priority:high

#4442 Makes sure email subject is valid UTF-8
  lib/Model/IMAPMessage.php
Labels: 3. to review, bug

#4468 Add a label to smtp host
  src/components/AccountForm.vue
Labels: 3. to review, enhancement

#4467 Add Nextcloud 22 compatibility
  .github/workflows/test.yml
  appinfo/info.xml
Labels: 3. to review

#4465 Fix filter expression
  lib/Service/Search/FilterStringParser.php
Labels: 3. to review, backport-request

#4473 Revert "Bump webdav from 3.6.2 to 4.0.0"
  package-lock.json
  package.json
Labels: 3. to review, bug, regression

#4474 Fix missing name of local attachments
  src/components/ComposerAttachments.vue
Labels: 3. to review, backport-request, blocked, bug, feature:editor, priority:high, regression

#4319 Allow php8
  .github/workflows/lint.yml
  .github/workflows/test.yml
  appinfo/info.xml
Labels: 3. to review, enhancement

#4453 Avoids using iconv with '//IGNORE' flag if possible
  lib/Address.php
  lib/Model/IMAPMessage.php
Labels: 3. to review, bug

#4406 Fix html signature format balloon
  src/components/SignatureSettings.vue
Labels: 3. to review, backport-request, bug

#4477 Run stable1.8 CI against Nextcloud 21, not master
  .github/workflows/lint.yml
  .github/workflows/package.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
Labels: 3. to review, enhancement

#4506 Run package on ubuntu 18.04
  .github/workflows/package.yml
  .github/workflows/test.yml
Labels: 3. to review, enhancement

#4245 Only use one AppDetailsToggle button and properly hide it if the navigation is open
  src/components/AppDetailsToggle.vue
  src/components/MailboxThread.vue
Labels: 3. to review, backport-request, bug

#4461 Fix wrong label for smtp user.
  src/components/settings/ProvisioningSettings.vue
Labels: 3. to review, bug

#4511 Add undo option for trusted senders
  src/components/TrustedSenders.vue
Labels: 3. to review

#4376 Fix the dark theme text color
  css/html-response.css
  src/components/MessageHTMLBody.vue
  src/html-response.js
Labels: 3. to review, bug

#4525 Change action ref from master to main
  .github/workflows/fixup.yml
Labels: 3. to review, enhancement

#4535 Makes "New message" button work again
  src/components/Navigation.vue
Labels: 3. to review, backport-request, bug, regression

#4539 Switch to a non-deprecated cache factory method
  tests/Integration/Service/AvatarServiceIntegrationTest.php
Labels: 3. to review, technical debt

#4531 Grammar fix
  src/components/NavigationAccountExpandCollapse.vue
Labels: 3. to review, bug

#4541 Add accountId to update account requests.
  src/components/AccountSettings.vue
Labels: 3. to review, bug

#4542 Fix envelopes not vanishing
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: 3. to review, bug

#4536 Download all attachments of an email as zip
  lib/Contracts/IMailManager.php
  lib/Controller/MessagesController.php
  lib/IMAP/MessageMapper.php
  lib/Service/MailManager.php
  src/components/Message.vue
  src/components/MessageAttachments.vue
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Service/MailManagerTest.php
Labels: 3. to review, enhancement

#4534 Avoid usage of Horde header query as it causes issues with php8
  lib/IMAP/MessageMapper.php
  lib/Model/IMAPMessage.php
  lib/Service/MailTransmission.php
Labels: 2. developing, bug, priority:high, regression

#4559 Make sure an account exists before updating it
  lib/Controller/AccountsController.php
Labels: 3. to review, backport-request, bug

#4556 Add delete command to OCC
  appinfo/info.xml
  lib/Command/DeleteAccount.php
  lib/Service/AccountService.php
  tests/Unit/Command/DeleteAccountTest.php
  tests/Unit/Service/AccountServiceTest.php
Labels: 3. to review, enhancement

#4318 ignore folders which cause errors on access
  lib/IMAP/FolderMapper.php
Labels: 2. developing, bug, priority:medium

#4288 Sometimes the MoveModal window wouldn't show up
  src/components/Envelope.vue
Labels: 3. to review, bug

#4565 Revert "Sometimes the MoveModal window wouldn't show up"
  src/components/Envelope.vue
Labels: 3. to review, bug, regression

#4562 l10n: Change of letters
  src/components/MessageAttachments.vue
Labels: 3. to review, bug

#4574 Add methods for important and favorite flag
  src/components/Envelope.vue
Labels: 3. to review, regression

#4575 Fix envelope list selection
  src/components/EnvelopeList.vue
Labels: 3. to review, bug

#4573 Download attachments without opening a new tab
  src/components/MessageAttachment.vue
Labels: 3. to review, enhancement

#4579 Add app navigation to account settings
  src/components/AccountSettings.vue
Labels: 4. to release, enhancement

#4583 Rework fetchThread Query
  lib/Db/MessageMapper.php
  tests/psalm-baseline.xml
Labels: 3. to review, enhancement

#4585 Fix link colour
  src/components/TextEditor.vue
Labels: 3. to review, design, enhancement

#4586 Hide mail server section if account is provisioned
  src/components/AccountSettings.vue
Labels: 3. to review, bug

#4577 Fix import for webdav
  src/service/FileService.js
Labels: 3. to review, bug

#4587 Always set a account name for provisioned accounts
  lib/Service/Provisioning/Manager.php
Labels: 3. to review, bug

#4594 Add logging section to admin docs
  doc/admin.md
Labels: 3. to review

#4591 fix inconsistent heading levels in changelog
  CHANGELOG.md
Labels: 3. to review

#4593 Save important flag to IMAP if permflags enabled
  lib/Db/MessageMapper.php
  lib/Listener/NewMessageClassificationListener.php
  lib/Model/IMAPMessage.php
  lib/Service/MailManager.php
  tests/Unit/Service/MailManagerTest.php
Labels: 3. to review, enhancement

#4597 Check if user exists before creating account
  lib/Command/CreateAccount.php
  tests/Unit/Command/CreateAccountTest.php
Labels: 3. to review, bug

#4472 Sieve
  .github/workflows/test.yml
  Makefile
  appinfo/info.xml
  appinfo/routes.php
  composer.json
  composer.lock
  doc/admin.md
  lib/Controller/SettingsController.php
  lib/Controller/SieveController.php
  lib/Db/MailAccount.php
  lib/Exception/CouldNotConnectException.php
  lib/Migration/AddSieveToProvisioningConfig.php
  lib/Migration/Version1090Date20210127160127.php
  lib/Service/Provisioning/Config.php
  lib/Service/Provisioning/Manager.php
  lib/Service/SetupService.php
  lib/Settings/AdminSettings.php
  lib/Sieve/SieveClientFactory.php
  lib/Sieve/SieveLogger.php
  src/components/AccountSettings.vue
  src/components/SieveAccountForm.vue
  src/components/SieveFilterForm.vue
  src/components/settings/ProvisionPreview.vue
  src/components/settings/ProvisioningSettings.vue
  src/errors/CouldNotConnectError.js
  src/errors/ManageSieveError.js
  src/errors/convert.js
  src/service/SieveService.js
  src/store/actions.js
  tests/Integration/Db/MailAccountTest.php
  tests/Integration/Sieve/SieveClientFactoryTest.php
  tests/Integration/Sieve/SieveLoggerTest.php
  tests/Unit/Controller/SettingsControllerTest.php
  tests/Unit/Controller/SieveControllerTest.php
  tests/Unit/Migration/AddSieveToProvisioningConfigTest.php
  tests/Unit/Service/Provisioning/ConfigTest.php
  tests/Unit/Service/Provisioning/ManagerTest.php
  tests/Unit/Service/Provisioning/TestConfig.php
  tests/Unit/Service/SetupServiceTest.php
Labels: 3. to review, enhancement, priority:high

#4513 Add trusted domain
  appinfo/info.xml
  lib/Contracts/ITrustedSenderService.php
  lib/Controller/TrustedSendersController.php
  lib/Db/TrustedSender.php
  lib/Db/TrustedSenderMapper.php
  lib/Migration/Version1090Date20210216154409.php
  lib/Service/TrustedSenderService.php
  src/components/MessageHTMLBody.vue
  src/components/TrustedSenders.vue
  src/service/TrustedSenderService.js
  tests/Integration/Db/TrustedSenderMapperTest.php
  tests/Unit/Service/TrustedSenderServiceTest.php
Labels: 4. to release, enhancement, priority:low
