Repository nextcloud/mail, pull requests merged in 2022-08, with the labels that each got.

#6867 Change opacity of settings icons and hover for a element
  src/components/AppSettingsMenu.vue
  src/components/Navigation.vue
Labels: 3. to review

#6952 Migrate icons to material design icons
  src/components/Envelope.vue
  src/components/MailboxPicker.vue
  src/components/MailboxThread.vue
  src/components/NavigationMailbox.vue
  src/components/NavigationOutbox.vue
Labels: 3. to review

#6948 Filter out range uids
  lib/IMAP/MessageMapper.php
  tests/Unit/IMAP/MessageMapperTest.php
Labels: bug, 3. to review, backport-request

#6955 Release 1.13.8-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6961 Update npm and node engines versions
  package.json
Labels: dependencies

#6950 Add envelope action links to download whole message
  appinfo/routes.php
  lib/Controller/MessagesController.php
  src/components/Envelope.vue
  src/components/MenuEnvelope.vue
  tests/Unit/Controller/MessagesControllerTest.php
Labels: enhancement, 3. to review, feature parity

#6964 Release 1.13.8
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
Labels: 3. to review

#6965 Integration test resetting message structure analyzation
  tests/Integration/Db/MessageMapperTest.php
Labels: 3. to review

#6849 Fix required MailboxInlinePicker value prop
  src/components/MailboxInlinePicker.vue
Labels: 3. to review, technical debt

#6774 Redesign the second column
  src/components/MailboxThread.vue
  src/components/Navigation.vue
  src/components/NewMessageButtonHeader.vue
  src/components/Outbox.vue
  src/components/ThreadEnvelope.vue
  src/views/Home.vue
Labels: 3. to review

#6966 Show message preview in envelope list
  lib/Db/Message.php
  src/components/Envelope.vue
  src/components/Imip.vue
  src/components/NavigationMailbox.vue
  src/components/imip/EventData.vue
  src/components/tags.js
Labels: enhancement, 4. to release, feature parity

#6971 Fix the new button and refresh icon style
  src/components/NewMessageButtonHeader.vue
Labels: 3. to review

#6985 Make new message button primary
  src/components/NewMessageButtonHeader.vue
Labels: 3. to review

#6988 Change the font size of PI section
  src/components/EmptyMailboxSection.vue
  src/components/MailboxThread.vue
  src/components/SectionTitle.vue
Labels: 3. to review

#6986 Move more message actions out of the actions menu
  src/components/MenuEnvelope.vue
  src/components/ThreadEnvelope.vue
Labels: 3. to review

#6984 Migrate account bullet colour to material design
  src/components/NavigationAccount.vue
Labels: 3. to review

#6990 Update @nextcloud/vue to 5.4.0
  package-lock.json
  package.json
Labels: 3. to review

#6991 Fix the button styling after vue update
  src/components/MailboxThread.vue
  src/components/NewMessageButtonHeader.vue
Labels: 3. to review

#6996 FIx padding for envelope list
  src/components/Envelope.vue
Labels: 3. to review

#6992 Shorten the relative time of envelopes
  src/components/Envelope.vue
  src/tests/unit/util/shortRelativeDatetime.spec.js
  src/util/shortRelativeDatetime.js
Labels: enhancement, 3. to review, design

#6951 Migrate admin settings to material design icon
  src/components/settings/AdminSettings.vue
  src/components/settings/AntiSpamSettings.vue
  src/components/settings/ProvisioningSettings.vue
Labels: 3. to review

#7007 Add textarea to global v-shortkey ignore list
  src/main.js
Labels: bug, 3. to review

#7011 Fix spreading of non-array event payload
  src/components/EnvelopeList.vue
Labels: bug, 4. to release, regression

#7012 Revert "Update vue to 5.4.0"
  package-lock.json
  package.json
Labels: bug, 3. to review, regression

#6989 Remove account color
  src/components/Envelope.vue
  src/components/OutboxMessageListItem.vue
Labels: 3. to review

#6963 Show mailbox counter if sub mailbox has unread messages
  src/components/NavigationMailbox.vue
  src/tests/unit/components/NavigationMailbox.vue.spec.js
Labels: enhancement, 4. to release

#6993 Hide has_cal tag
  src/components/tags.js
Labels: bug, 3. to review, papercut

#6947 Change the 'show image' styling
  src/components/MessageHTMLBody.vue
Labels: 4. to release

#7022 Show message actions only for expanded messages in thread
  src/components/ThreadEnvelope.vue
Labels: enhancement, 3. to review

#7021 Preview message content in the thread view
  src/components/Thread.vue
  src/components/ThreadEnvelope.vue
Labels: enhancement, 3. to review, design, feature parity

#6944 Change mail logo to material design icon
  img/LICENSES.md
  img/archive.png
  img/archive.svg
  img/drafts.png
  img/drafts.svg
  img/favicon-mask.svg
  img/favicon-notification.png
  img/favicon-notification.svg
  img/favicon-touch-notification.png
  img/favicon-touch-notification.svg
  img/favicon-touch.png
  img/favicon-touch.svg
  img/favicon.ico
  img/favicon.png
  img/favicon.svg
  img/forward.png
  img/forward.svg
  img/inbox.png
  img/inbox.svg
  img/junk.png
  img/junk.svg
  img/mail-notification.png
  img/mail-notification.svg
  img/mail.svg
  img/reply-all.png
  img/reply-all.svg
  img/reply.png
  img/reply.svg
  img/sent.png
  img/sent.svg
  img/trash.png
  img/trash.svg
Labels: enhancement, 4. to release, design

#7048 Mark avatar has immutable
  lib/Controller/AvatarsController.php
  tests/Unit/Controller/AvatarControllerTest.php
Labels: 3. to review

#7061 Bump @ckeditor/* from 34.2.0 to 35.0.1
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#6557 Implement __serialize for the Horde cache
  lib/Cache/Cache.php
Labels: 3. to review, technical debt

#6686 Fix contacts photo integration picking wrong PHOTO entry
  lib/Service/ContactsIntegration.php
Labels: bug, 4. to release

#7060 Upgrade to nc/vue6beta3
  package-lock.json
  package.json
  src/components/AccountSettings.vue
  src/components/AppSettingsMenu.vue
  src/components/AttachmentImageViewer.vue
  src/components/Avatar.vue
  src/components/Composer.vue
  src/components/Dashboard.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/EventModal.vue
  src/components/Imip.vue
  src/components/MailboxPicker.vue
  src/components/MailboxThread.vue
  src/components/MenuEnvelope.vue
  src/components/MessageAttachment.vue
  src/components/MessageHTMLBody.vue
  src/components/Navigation.vue
  src/components/NavigationAccount.vue
  src/components/NavigationAccountExpandCollapse.vue
  src/components/NavigationMailbox.vue
  src/components/NavigationOutbox.vue
  src/components/NewMessageButtonHeader.vue
  src/components/NewMessageModal.vue
  src/components/NoMessageSelected.vue
  src/components/Outbox.vue
  src/components/OutboxMessageListItem.vue
  src/components/RecipientBubble.vue
  src/components/RecipientListItem.vue
  src/components/SignatureSettings.vue
  src/components/TagModal.vue
  src/components/Thread.vue
  src/components/ThreadEnvelope.vue
  src/components/itinerary/CalendarImport.vue
  src/components/settings/AdminSettings.vue
  src/components/settings/AntiSpamSettings.vue
  src/components/settings/ProvisioningSettings.vue
  src/views/Home.vue
  src/views/KeyboardShortcuts.vue
  src/views/Setup.vue
Labels: 3. to review

#7069 Release v1.14.0-beta1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#7073 Fix sectiontitle font size and favotrite postition
  src/components/Envelope.vue
  src/components/SectionTitle.vue
Labels: 3. to review

#7081 Migrate composer attachment classes to BEM
  src/components/ComposerAttachment.vue
Labels: 4. to release, technical debt

#6995 Migrate icons to material design icons
  package-lock.json
  src/components/AccountForm.vue
  src/components/AccountSettings.vue
  src/components/AliasForm.vue
  src/components/AliasSettings.vue
  src/components/AppSettingsMenu.vue
  src/components/Composer.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/Loading.vue
  src/components/MailboxPicker.vue
  src/components/MailboxThread.vue
  src/components/MessageAttachment.vue
  src/components/MessageAttachments.vue
  src/components/MessageHTMLBody.vue
  src/components/NavigationAccount.vue
  src/components/NavigationMailbox.vue
  src/components/RecipientBubble.vue
  src/components/RecipientListItem.vue
  src/components/SieveAccountForm.vue
  src/components/SieveFilterForm.vue
  src/components/SignatureSettings.vue
  src/components/TagModal.vue
  src/components/Thread.vue
  src/components/ThreadEnvelope.vue
  src/components/TrustedSenders.vue
  src/components/itinerary/CalendarImport.vue
Labels: 3. to review

#7087 Add border to favorite icon
  src/components/Envelope.vue
  src/components/ThreadEnvelope.vue
Labels: enhancement, 4. to release, design

#7058 Replace the appnavigatiocounter to counterbubble
  src/components/NavigationMailbox.vue
Labels: 4. to release

#7100 Disable submit button on account settings when its loading
  src/components/AccountForm.vue
Labels: 3. to review

#7103 Overwrite z-index for CKEditor
  src/components/TextEditor.vue
Labels: bug, 4. to release

#7104 Catch invalid UTF-8 during message preview text insertion
  lib/Db/MessageMapper.php
Labels: bug, 3. to review

#7080 Remove unneccessary account check
  lib/Controller/OutboxController.php
  tests/Unit/Controller/OutboxControllerTest.php
Labels: 3. to review, performance 🚀

#7105 Make thread timestamp shorter
  src/components/Moment.vue
Labels: 3. to review

#7107 Assign dedicated Dependabot bump reviewers
  .github/dependabot.yml
Labels: 3. to review
