Repository nextcloud/mail, pull requests merged in 2022-11, with the labels that each got.

#7461 Add search box for outbox and PI
  src/components/Mailbox.vue
  src/components/MailboxThread.vue
  src/components/Outbox.vue
  src/components/SearchMessages.vue
Labels: 3. to review

#7512 Migrate Vuex actions from promises to async-await
  src/store/actions.js
Labels: 3. to review, technical debt

#7514 Fix server error accessing message routes anonymously
  lib/Controller/MessagesController.php
Labels: bug, 3. to review

#7518 Release v1.14.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7515 Catch expired session and reload the page
  src/App.vue
  src/http/sessionExpiryHandler.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  src/tests/unit/App.spec.js
  src/tests/unit/http/sessionExpiryHandler.spec.js
  src/tests/unit/store/getters.spec.js
Labels: bug, 4. to release

#7519 Add icon for load more on PI
  src/components/EnvelopeList.vue
Labels: enhancement, 4. to release, design

#7522 Update app screenshot to match Nextcloud 25 design
  screenshots/mail.png
Labels: enhancement, 3. to review, backport-request

#7523 Prevent trim'ing and strpos'ing null in integration tests
  tests/Integration/Framework/ImapTest.php
  tests/Integration/Framework/MessageBuilder.php
  tests/Integration/Framework/SimpleMessage.php
Labels: 3. to review, technical debt

#7524 Fix double scrollbar in thread view
  src/components/Thread.vue
Labels: bug, 3. to review, design, backport-request, regression

#7545 Fix copy to clipboard
  src/components/RecipientBubble.vue
Labels: bug, 3. to review, backport-request

#7553 Fix tests in shortRelativeDatetime.spec.js
  src/tests/unit/util/shortRelativeDatetime.spec.js
Labels: bug, 3. to review

#7555 Fix important and favorite icon position
  src/components/ThreadEnvelope.vue
Labels: 3. to review

#7558 Fix sending PGP messages as HTML
  src/components/Composer.vue
Labels: bug, 3. to review, backport-request

#7540 Fix envelope and message previews showing PGP ciphertext
  src/components/Envelope.vue
  src/components/ThreadEnvelope.vue
  src/crypto/pgp.js
  src/tests/unit/crypto/pgp.spec.js
Labels: bug, 3. to review, design, security

#7557 Fix provisioning config not saving
  src/components/settings/ProvisioningSettings.vue
Labels: bug, 3. to review, backport-request

#7568 Fix scrolling for long threads
  src/components/Thread.vue
Labels: bug, 3. to review

#7569 Improve the size of padding bottom on threads
  src/components/MessageAttachments.vue
  src/components/Thread.vue
Labels: enhancement, 3. to review, backport-request

#7572 Release v1.14.3-alpha.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7575 Fix broken encoding for outgoing messages
  lib/Service/MimeMessage.php
  tests/Unit/Service/MailTransmissionTest.php
  tests/Unit/Service/MimeMessageTest.php
  tests/data/mime-html-greek.txt
Labels: bug, 3. to review, backport-request

#7586 Don't decode content for preview twice
  lib/IMAP/MessageMapper.php
  lib/Migration/Version1140Date20221113205737.php
Labels: bug, 3. to review, backport-request

#7593 [stable1.14] Remove $isImipMessage argument
  lib/IMAP/MessageMapper.php
Labels: bug, 3. to review

#7591 Release v1.14.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7592 Fix saving provisioning and anti-spam settings
  src/components/settings/AntiSpamSettings.vue
  src/components/settings/ProvisioningSettings.vue
Labels: bug, 3. to review, backport-request

#7607 Show thread subject while loading thread messages
  src/components/Thread.vue
Labels: enhancement, 4. to release

#7609 Improve thread message loading screen
  src/components/MessageHTMLBody.vue
  src/components/Thread.vue
  src/components/ThreadEnvelope.vue
Labels: enhancement, 4. to release, design

#7612 Make HTML body loading a single step experience
  src/components/Message.vue
  src/components/MessageHTMLBody.vue
  src/components/ThreadEnvelope.vue
Labels: enhancement, 3. to review, design

#7613 Increase the clickable area on envelope thread
  src/components/ThreadEnvelope.vue
Labels: enhancement, 3. to review, design

#7618 Improve the animation of enevelope list skeleton
  src/components/LoadingSkeleton.vue
Labels: enhancement, 3. to review, design

#7621 Fix Undefined errorMessage in ThreadEnvelope
  src/components/ThreadEnvelope.vue
Labels: bug, 3. to review, backport-request

#7628 Dont collapse if threading has one message only
  src/components/Thread.vue
Labels: bug, 4. to release, design, backport-request

#7645 Fix XOAUTH2 auth via SMTP
  lib/SMTP/SmtpClientFactory.php
Labels: bug, 3. to review, feature:integration, backport-request

#7651 Revert "Fix XOAUTH2 auth via SMTP"
  lib/SMTP/SmtpClientFactory.php
Labels: 3. to review

#7653 Release 2.1.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7652 Fix XOAUTH2 auth via SMTP
  lib/SMTP/SmtpClientFactory.php
Labels: 3. to review, backport-request

#7643 Replace emptycontent div with EmptyContent vue component
  src/components/EmptyMailbox.vue
  src/components/NoMessageSelected.vue
  src/components/OutboxMessageContent.vue
Labels: bug, 3. to review, technical debt

#7654 Update changelog for 2.1.2 release
  CHANGELOG.md
Labels: 4. to release

#7657 Replace emptycontent div with EmptyContent vue component
  src/components/Composer.vue
  src/components/EmptyMailboxSection.vue
  src/components/Error.vue
Labels: bug, 3. to review, technical debt

#7664 Drop right border from navigation header
  src/components/NewMessageButtonHeader.vue
Labels: bug, 3. to review, design

#7617 Handle error when thread id is unknown
  src/components/Thread.vue
Labels: bug, 3. to review

#7663 Fix deprecated constructor null code
  tests/Unit/IMAP/MailboxSyncTest.php
  tests/Unit/Listener/SaveSentMessageListenerTest.php
  tests/Unit/Migration/MigrateImportantFromImapAndDbTest.php
Labels: 3. to review, technical debt

#7665 Fix scrolling for long threads on narrow screens
  src/components/MailboxThread.vue
  src/components/Thread.vue
Labels: bug, 3. to review, backport-request, regression

#7616 Disable provisioned accounts if using passwordless authentication
  lib/Controller/PageController.php
  lib/Http/Middleware/ProvisioningMiddleware.php
  src/components/Navigation.vue
  src/components/NavigationAccount.vue
  src/main.js
  src/store/actions.js
  src/tests/unit/store/actions.spec.js
  tests/Unit/Controller/PageControllerTest.php
Labels: bug, 3. to review, backport-request

#7676 Fix scrolling regressions for long threads
  src/components/MailboxThread.vue
  src/components/Thread.vue
Labels: bug, 3. to review, design

#7662 Remove dead code from DraftsJob
  lib/BackgroundJob/DraftsJob.php
Labels: 3. to review, technical debt

#7084 Respect share enumeration constraints on autocomplete
  lib/Service/AutoCompletion/AutoCompleteService.php
  lib/Service/ContactsIntegration.php
  tests/Unit/Service/Autocompletion/AutoCompleteServiceTest.php
  tests/Unit/Service/ContactsIntegrationTest.php
Labels: 3. to review

#7690 Remove loading icons when refreshing
  src/components/EnvelopeList.vue
Labels: enhancement, 4. to release, design

#7677 Show only existing mailboxes, not all subscribed mailboxes
  lib/IMAP/FolderMapper.php
  tests/Unit/IMAP/FolderMapperTest.php
Labels: bug, 4. to release

#7678 Fix dark theme loading envelopes and thread colour
  src/components/LoadingSkeleton.vue
  src/components/MessageLoadingSkeleton.vue
Labels: bug, 3. to review, design

#7697 Release 2.1.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7698 Update changelog for 2.1.3
  CHANGELOG.md
Labels: 4. to release

#7700 Revert "Show only existing mailboxes, not all subscribed mailboxes"
  lib/IMAP/FolderMapper.php
  tests/Unit/IMAP/FolderMapperTest.php
Labels: bug, 3. to review, backport-request, regression

#7703 Release v2.1.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7705 Release v1.14.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
