Repository nextcloud/mail, pull requests merged in 2022-03, with the labels that each got.

#6100 Update ckeditor to 32.0.0
  package-lock.json
  package.json
Labels: bug, 4. to release, priority:high, regression, dependencies

#5748 Fixes use mailbox.accountId as fallback when accountId isn't defined in Envelope.vue
  src/components/Envelope.vue
Labels: bug

#6098 Add primary action buttons and more actions menu
  src/components/Envelope.vue
  src/components/EnvelopePrimaryActions.vue
  src/components/MenuEnvelope.vue
Labels: bug, 4. to release, design, nextcloud-gmbh

#6030 Add database schema and layer for local mailboxes
  appinfo/info.xml
  lib/Db/LocalAttachment.php
  lib/Db/LocalAttachmentMapper.php
  lib/Db/LocalMessage.php
  lib/Db/LocalMessageMapper.php
  lib/Db/MessageMapper.php
  lib/Db/Recipient.php
  lib/Db/RecipientMapper.php
  lib/Migration/Version1120Date20220223094709.php
  tests/Integration/Db/LocalMessageMapperTest.php
  tests/Integration/Db/LocalMessageTest.php
  tests/Integration/Db/RecipientMapperTest.php
  tests/Integration/Db/RecipientTest.php
Labels: enhancement, 3. to review, feature: outbox

#5779 Add anti abuse detection
  doc/admin.md
  lib/AppInfo/Application.php
  lib/Events/BeforeMessageSentEvent.php
  lib/Listener/AntiAbuseListener.php
  lib/Service/AntiAbuseService.php
  lib/Service/MailTransmission.php
  tests/Unit/Service/AntiAbuseServiceTest.php
  tests/psalm-baseline.xml
Labels: enhancement, 4. to release

#6150 Fix index of next message to delete
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
Labels: bug, 3. to review, backport-request

#6159 Fix outbox PHP unit tests
  tests/Unit/Controller/PageControllerTest.php
Labels: 3. to review

#6160 Fix outbox ESLint errors
  src/components/NewMessageModal.vue
  src/main.js
Labels: 3. to review

#6158 Merge main into feature/outbox (again)
  composer.lock
  doc/admin.md
  l10n/el.js
  l10n/el.json
  l10n/fi.js
  l10n/fi.json
  lib/AppInfo/Application.php
  lib/Events/BeforeMessageSentEvent.php
  lib/Listener/AntiAbuseListener.php
  lib/Service/AntiAbuseService.php
  lib/Service/MailTransmission.php
  package-lock.json
  package.json
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  tests/Unit/Service/AntiAbuseServiceTest.php
  tests/psalm-baseline.xml
Labels: 4. to release, feature: outbox

#6169 Document how to debug slow IMAP/SMTP connections
  doc/admin.md
Labels: enhancement, 3. to review
