Repository nextcloud/mail, pull requests merged in 2022-10, with the labels that each got.

#7359 Move BG jobs to typed properties
  lib/BackgroundJob/CleanupJob.php
  lib/BackgroundJob/MigrateImportantJob.php
  lib/BackgroundJob/OutboxWorkerJob.php
  lib/BackgroundJob/SyncJob.php
  lib/BackgroundJob/TrainImportanceClassifierJob.php
Labels: enhancement, 3. to review, papercut

#7361 Move commands to typed properties
  lib/Command/AddMissingTags.php
  lib/Command/CleanUp.php
  lib/Command/CreateAccount.php
  lib/Command/CreateTagMigrationJobEntry.php
  lib/Command/DeleteAccount.php
  lib/Command/DiagnoseAccount.php
  lib/Command/ExportAccount.php
  lib/Command/ExportAccountThreads.php
  lib/Command/SyncAccount.php
  lib/Command/Thread.php
  lib/Command/TrainAccount.php
Labels: enhancement, 3. to review, papercut

#7363 Redirect to setup page if no accounts are configured
  src/App.vue
Labels: bug, 3. to review, backport-request

#7366 [stable1.14] Redirect to setup page if no accounts are configured
  src/App.vue
Labels: bug, 3. to review

#7338 Update Dependabot config for stable branch security updates
  .github/dependabot.yml
Labels: 3. to review, security

#7362 Move controllers to typed properties
  lib/Controller/AccountsController.php
  lib/Controller/AliasesController.php
  lib/Controller/AutoCompleteController.php
  lib/Controller/AvatarsController.php
  lib/Controller/ContactIntegrationController.php
  lib/Controller/LocalAttachmentsController.php
  lib/Controller/MailboxesController.php
  lib/Controller/MessagesController.php
  lib/Controller/OutboxController.php
  lib/Controller/PageController.php
  lib/Controller/PreferencesController.php
  lib/Controller/ProxyController.php
  lib/Controller/SettingsController.php
  lib/Controller/SieveController.php
  lib/Controller/TagsController.php
  lib/Controller/ThreadController.php
  lib/Controller/TrustedSendersController.php
Labels: enhancement, 3. to review

#7360 Move Cache to typed properties
  lib/Cache/Cache.php
Labels: enhancement, 3. to review

#7358 Add the option to disable the new account button
  appinfo/routes.php
  lib/Controller/AccountsController.php
  lib/Controller/PageController.php
  lib/Controller/SettingsController.php
  lib/Settings/AdminSettings.php
  src/components/AppSettingsMenu.vue
  src/components/settings/AdminSettings.vue
  src/main.js
  src/service/SettingsService.js
  src/views/Setup.vue
  tests/Unit/Controller/AccountsControllerTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Settings/AdminSettingsTest.php
Labels: enhancement, 2. developing

#7356 Update ::v-deep to :deep and fix style issue
  src/components/AccountForm.vue
  src/components/AccountSettings.vue
  src/components/AliasSettings.vue
  src/components/Composer.vue
  src/components/Dashboard.vue
  src/components/Envelope.vue
  src/components/EventModal.vue
  src/components/Imip.vue
  src/components/Mailbox.vue
  src/components/MailboxPicker.vue
  src/components/MailboxThread.vue
  src/components/MenuEnvelope.vue
  src/components/MessageHTMLBody.vue
  src/components/Navigation.vue
  src/components/NavigationAccountExpandCollapse.vue
  src/components/NavigationOutbox.vue
  src/components/NewMessageModal.vue
  src/components/Outbox.vue
  src/components/RecipientBubble.vue
  src/components/RecipientListItem.vue
  src/components/SignatureSettings.vue
  src/components/TagModal.vue
  src/components/TextEditor.vue
  src/components/ThreadEnvelope.vue
  src/components/TrustedSenders.vue
  src/views/Home.vue
  src/views/KeyboardShortcuts.vue
Labels: 3. to review, technical debt

#7371 Fix disabling the add account button
  lib/Controller/PageController.php
  src/components/AppSettingsMenu.vue
  src/views/Setup.vue
  tests/Unit/Controller/PageControllerTest.php
Labels: bug, 3. to review

#7373 Add loading state when the refresh icon is clicked
  src/components/NewMessageButtonHeader.vue
Labels: 3. to review

#7372 Fix keyboard button misaligment
  src/components/AppSettingsMenu.vue
Labels: 3. to review

#7355 Archiving messages
  appinfo/info.xml
  doc/user.md
  lib/Controller/AccountsController.php
  lib/Db/MailAccount.php
  lib/Listener/MailboxesSynchronizedSpecialMailboxesUpdater.php
  lib/Migration/Version2010Date20221002201527.php
  lib/Service/IMipService.php
  src/components/AccountDefaultsSettings.vue
  src/components/AccountSettings.vue
  src/components/Envelope.vue
  src/components/Mailbox.vue
  src/components/MailboxThread.vue
  src/components/ThreadEnvelope.vue
  tests/Integration/Db/MailAccountTest.php
Labels: enhancement, 4. to release

#7378 Fix missing visual drop target on nav mailboxes
  src/directives/drag-and-drop/styles/droppable-mailbox.scss
Labels: bug, 3. to review, design, regression

#7381 Bump league/flysystem from 2.0.8 to 2.5.0
  .github/workflows/lint.yml
  .github/workflows/package.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  composer.json
  composer.lock
Labels: bug, 3. to review, backport-request, dependencies

#7382 [stable2.0] Bump league/flysystem from 2.0.8 to 2.5.0
  .github/workflows/lint.yml
  .github/workflows/package.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  composer.json
  composer.lock
Labels: bug, 3. to review, dependencies

#7386 [stable1.14] Fix test workflow
  .github/workflows/test.yml
Labels: 3. to review, technical debt

#7383 [stable1.14] Bump league/flysystem from 2.0.8 to 2.5.0
  .github/workflows/lint.yml
  .github/workflows/package.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  composer.json
  composer.lock
Labels: bug, 3. to review, dependencies

#7388 Migrate back to rubix
  composer.json
  composer.lock
Labels: 3. to review, technical debt, backport-request

#7404 Release 1.14.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#7410 Release v2.0.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7411 Fast Forward changelog
  CHANGELOG.md
Labels: 3. to review

#7416 GH-7414: Fix schema definition for QuotePlugin
  src/ckeditor/quote/QuotePlugin.js
  src/components/SignatureSettings.vue
  src/tests/unit/components/QuotePlugin.spec.js
Labels: bug, 3. to review

#7421 Add account column/props for XOAUTH2 refresh tokens and their TTL
  appinfo/info.xml
  lib/Db/MailAccount.php
  lib/Migration/Version2100Date20221013143851.php
Labels: enhancement, 4. to release, feature:integration

#7422 Only test PRs, not pushes
  .github/workflows/package.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
Labels: 3. to review, technical debt, backport-request

#7418 Bump @nextcloud/vue to v6
  package-lock.json
  package.json
Labels: 3. to review

#7312 :bug: Remove the concatenation from query builder and
  lib/Db/MessageMapper.php
Labels: bug, 4. to release, backport-request

#7420 Allow changing an account's auth method via REST
  lib/Controller/AccountsController.php
  lib/Db/MailAccount.php
  lib/Service/SetupService.php
  tests/Unit/Controller/AccountsControllerTest.php
Labels: enhancement, 4. to release

#7419 Bump @nextcloud/vue to v7
  package-lock.json
  package.json
Labels: 3. to review, backport-request

#7428 Fix weird modal glitches on Firefox when toggling autoresponder
  src/components/AccountSettings.vue
Labels: bug, 4. to release, backport-request

#7308 Add skeleton for loading state
  src/components/LoadingSkeleton.vue
  src/components/Mailbox.vue
  src/components/Outbox.vue
Labels: enhancement, 4. to release

#7441 [stable2.0] Bump @nextcloud/vue to v7.0.0
  package-lock.json
  package.json
Labels: 4. to release

#7440 [stable2.0] Bump @nextcloud/vue to v7.0.1
  package-lock.json
  package.json
Labels: 0. Needs triage

#7442 Release v2.0.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7443 Specify postgres 14 in test workflows
  .github/workflows/test.yml
Labels: 3. to review, backport-request

#6546 Advanced message search
  css/mail.scss
  lib/Db/MessageMapper.php
  lib/Service/Search/FilterStringParser.php
  lib/Service/Search/SearchQuery.php
  src/components/Mailbox.vue
  src/components/MailboxThread.vue
  src/components/Navigation.vue
  src/components/NewMessageButtonHeader.vue
  src/components/SearchMessages.vue
Labels: enhancement, 3. to review

#7116 Hide important section when no important messages
  src/components/EmptyMailboxSection.vue
  src/components/MailboxThread.vue
Labels: 3. to review

#7455 Forward-port 2.0.1 and 2.0.2 and 2.0.3
  CHANGELOG.md
Labels: 3. to review

#7459 Release v2.1.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6908 Add an occ mail:account:update command
  appinfo/info.xml
  lib/Command/UpdateAccount.php
  tests/psalm-baseline.xml
Labels: enhancement, 2. developing

#7470 [stable1.14] Specify postgres 14 in test workflows
  .github/workflows/test.yml
Labels: 4. to release

#7471 [stable2.0] Specify postgres 14 in test workflows
  .github/workflows/test.yml
Labels: 4. to release

#7476 Fix handling of account update API response
  lib/Controller/AccountsController.php
  src/service/AccountService.js
Labels: bug, 3. to review, backport-request

#7485 Fix OOM during cache clean-up
  lib/Db/MessageMapper.php
Labels: 3. to review, backport-request, performance 🚀

#6720 Alias provisioning: Skip alias when identical to account email
  lib/Service/Provisioning/Manager.php
Labels: enhancement, 3. to review

#7493 Bump version to v2.2.0 Alpha 0
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7486 Fix transfer encoding issue
  lib/IMAP/MessageMapper.php
  lib/Migration/Version1140Date20221027171138.php
Labels: bug, 3. to review, feature: HTML mails
