Repository nextcloud/mail, pull requests merged in 2022-02, with the labels that each got.

#6004 Drop php 7.3 for test workflow on master
  .github/workflows/test.yml
Labels: 3. to review, technical debt

#6009 README.md has been extended
  README.md
Labels: 4. to release

#6006 Remove the autocomplete text after selecting recipient
  src/components/Composer.vue
Labels: enhancement, 3. to review

#6003 Migrate bug report template to a form
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug_report_form.yml
Labels: enhancement, 3. to review

#6022 allow to create submailbox inside of submailboxes
  src/components/NavigationMailbox.vue
Labels: enhancement, 3. to review

#6016 Fix bug form
  .github/ISSUE_TEMPLATE/bug_report_form.yml
Labels: enhancement, 4. to release

#6032 Fix missing loading indicator
  src/components/Composer.vue
Labels: 3. to review

#6043 Migrate feature request form
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement, 4. to release

#6044 Pointer cursor for quoted text clickability feedback
  src/components/MessagePlainTextBody.vue
Labels: enhancement, 3. to review

#4954 Revert "Remove Jans test (for now)"
  tests/Integration/Service/AvatarServiceIntegrationTest.php
Labels: 2. developing, needs info

#6052 Add outbox REST API stubs
  appinfo/routes.php
  lib/Controller/OutboxController.php
Labels: enhancement, 4. to release

#6049 Log slow MySQL queries on CI
  .github/workflows/test.yml
Labels: 3. to review, performance 🚀

#6053 Mark background jobs as time sensitive/insensitive
  lib/BackgroundJob/CleanupJob.php
  lib/BackgroundJob/MigrateImportantJob.php
  lib/BackgroundJob/SyncJob.php
  lib/BackgroundJob/TrainImportanceClassifierJob.php
Labels: 3. to review, performance 🚀

#6028 Fix missing account aliases for new accounts
  src/store/index.js
  src/store/mutations.js
  src/tests/unit/store/mutations.spec.js
Labels: bug, 4. to release, priority:high, backport-request

#6072 Make sure array_merge has at least one argument if DB returns no results
  lib/Db/MessageMapper.php
Labels: 4. to release, backport-request

#6075 Revert "Bump vue-loader from 15.9.7 to 17.0.0"
  package-lock.json
  package.json
Labels: bug, 4. to release, regression

#6066 Fix Psalm checks against server master with PHP7.3
  .github/workflows/static-analysis.yml
  lib/BackgroundJob/CleanupJob.php
  lib/BackgroundJob/SyncJob.php
  lib/BackgroundJob/TrainImportanceClassifierJob.php
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/mozart/composer.json
  vendor-bin/mozart/composer.lock
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
Labels: 3. to review, technical debt

#5992 Updating fixup.yml workflow from template
  .github/workflows/fixup.yml
Labels: dependencies
