Repository nextcloud/mail, pull requests merged in 2022-06, with the labels that each got.

#5494 Add threading to frontend
  src/components/Thread.vue
  src/store/getters.js
  src/store/mutations.js
  src/tests/unit/store/getters.spec.js
  src/tests/unit/store/mutations.spec.js
Labels: bug, enhancement, 2. developing

#6558 Add PHP8.2 to CI matrix
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: 3. to review

#6617 Migrate the left sidebar icons
  src/components/NavigationMailbox.vue
  src/components/NavigationOutbox.vue
Labels: enhancement, 4. to release

#6634 Fix losing the reply message ID when editing an outbox message
  src/components/Composer.vue
  src/components/NewMessageModal.vue
Labels: bug, 3. to review, priority:high, backport-request, feature:editor, feature: outbox

#6638 Ask Dependabot for stable1.12 security updates
  .github/dependabot.yml
Labels: 4. to release

#6602 Fix sending erroneous message repeatedly
  appinfo/info.xml
  lib/Contracts/ILocalMailboxService.php
  lib/Contracts/IMailTransmission.php
  lib/Controller/OutboxController.php
  lib/Db/LocalMessage.php
  lib/Db/LocalMessageMapper.php
  lib/Migration/Version1124Date20220531094751.php
  lib/Service/OutboxService.php
  src/components/OutboxMessageListItem.vue
  tests/Unit/Controller/OutboxControllerTest.php
Labels: bug, 4. to release, priority:high, backport-request, feature: outbox

#6663 Fix missing Composer.vue::initBody call after mount
  src/components/Composer.vue
Labels: bug, 3. to review, priority:high, backport-request, regression

#6665 Fix quoting forwarded messages
  src/components/NewMessageModal.vue
Labels: bug, 3. to review, backport-request, regression

#6674 Release v1.12.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6676 Release v1.13.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6677 Forward-port changelog
  CHANGELOG.md
Labels: 3. to review

#6680 Fix missing default value for `failed` of outbox messages
  lib/Controller/OutboxController.php
Labels: bug, 3. to review, priority:high, backport-request, feature: outbox

#6692 Release v1.13.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6693 Forward-port changelog
  CHANGELOG.md
Labels: 3. to review

#6544 Add attachments objects on message forward
  lib/Service/Attachment/AttachmentService.php
  src/store/actions.js
  tests/Unit/Service/Attachment/AttachmentServiceTest.php
Labels: bug, 4. to release

#6694 Turn off background/cli classification training of opt-ed out
  lib/BackgroundJob/TrainImportanceClassifierJob.php
  lib/Command/TrainAccount.php
Labels: bug, 3. to review, backport-request

#6372 Fix automatic email signature on the composer
  appinfo/info.xml
  lib/Controller/OutboxController.php
  lib/Db/LocalMessage.php
  lib/Migration/Version1124Date20220601084530.php
  src/components/Composer.vue
  src/components/NewMessageModal.vue
  tests/Unit/Controller/OutboxControllerTest.php
Labels: bug, 4. to release, priority:high, backport-request, regression

#6709 Release v1.12.6-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6733 Release 1.13.4
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release

#6732 Remove failing avatar integration test
  tests/Integration/Service/AvatarServiceIntegrationTest.php
Labels: bug, 3. to review, backport-request

#6736 Work around breaking server change and QB expressions
  lib/Db/MailboxMapper.php
Labels: 3. to review

#6735 Forward-port changelog
  CHANGELOG.md
Labels: 3. to review

#6689 Change sender position to be centered with the avatar and timestamps
  src/components/ThreadEnvelope.vue
Labels: bug, 4. to release, design, backport-request

#6696 Fix image preview when the menu is clicked
  src/components/MessageAttachment.vue
Labels: bug, 3. to review, design

#5981 Handle empty thread root id
  lib/Controller/MessagesController.php
  lib/Db/Message.php
  tests/Integration/Db/MessageTest.php
  tests/Unit/Controller/MessagesControllerTest.php
Labels: bug, 3. to review, feature:threading

#6746 chore: Set permissions for GitHub actions
  .github/workflows/lint.yml
  .github/workflows/package.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
Labels: 4. to release

#6671 Migrate reply and reply all icon to material design
  src/components/ThreadEnvelope.vue
Labels: 4. to release

#6749 Update Jest to version 28: @vue/vue2-jest, babel-jest, jest
  jest.config.js
  package-lock.json
  package.json
Labels: 3. to review

#6660 Improve the way attachment look
  src/components/ComposerAttachment.vue
  src/components/ComposerAttachments.vue
  src/service/AttachmentService.js
  src/service/FileService.js
Labels: enhancement, 3. to review, design

#6753 Migrate subtitle icons to material design
  src/components/Envelope.vue
Labels: 4. to release

#6286 Users can clear their mailboxes
  appinfo/routes.php
  lib/Contracts/IMailManager.php
  lib/Controller/MailboxesController.php
  lib/Service/MailManager.php
  src/components/NavigationMailbox.vue
  src/service/MailboxService.js
  src/store/actions.js
  src/store/mutations.js
Labels: enhancement, 3. to review

#6769 Restore ability to write mails in safari
  src/components/Composer.vue
Labels: bug, 3. to review, backport-request, regression

#6754 Change the opacity of left sidebar icons to fit the rest of the icons
  src/components/NavigationMailbox.vue
  src/components/NavigationOutbox.vue
Labels: 3. to review

#6778 Release v1.13.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6779 Fast forward changelog
  CHANGELOG.md
Labels: 3. to review

#6788 Add missing package-lock.json changes
  package-lock.json
Labels: 3. to review, technical debt

#6773 Fix download all as zip
  lib/IMAP/MessageMapper.php
Labels: bug, 3. to review

#6787 Fix not being able to edit drafts
  src/components/NewMessageModal.vue
Labels: bug, 3. to review, backport-request, regression

#6768 Revert "Users can clear their mailboxes"
  appinfo/routes.php
  lib/Contracts/IMailManager.php
  lib/Controller/MailboxesController.php
  lib/Service/MailManager.php
  src/components/NavigationMailbox.vue
  src/service/MailboxService.js
  src/store/actions.js
  src/store/mutations.js
Labels: 3. to review, discussion

#6799 Fix wrong initial value (NaN) for prop "checked"
  src/components/Composer.vue
Labels: bug, 4. to release

#6756 Migrate avatar icons for envelope list avatar and thread envelope avatar to material design
  src/components/Envelope.vue
  src/components/ThreadEnvelope.vue
  src/components/icons/JunkIcon.vue
Labels: 3. to review

#6751 ${var} is deprecated for php8.2
  lib/Support/PerformanceLoggerTask.php
Labels: bug, 3. to review

#6806 Release 1.12.8
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#6807 Release 1.13.6
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#6816 Include local messages table in app reset instructions
  doc/developer.md
Labels: 3. to review
