Repository nextcloud/mail, pull requests merged in 2022-07, with the labels that each got.

#6819 Add support for XOAUTH2
  appinfo/info.xml
  lib/Command/CreateAccount.php
  lib/Db/MailAccount.php
  lib/IMAP/IMAPClientFactory.php
  lib/Migration/Version1140Date20220701103556.php
  tests/Unit/Command/CreateAccountTest.php
Labels: enhancement, 4. to release, feature:integration, security

#6790 Migrate settings icon to material design icons
  src/components/AppSettingsMenu.vue
Labels: 4. to release

#6833 Fix account form styling
  src/components/AccountForm.vue
Labels: bug, 3. to review, design, regression

#6835 Update package-lock.json with latest changes
  package-lock.json
Labels: 3. to review, technical debt

#6831 Split auto config and account creation
  appinfo/routes.php
  lib/Controller/AccountsController.php
  lib/Controller/AutoConfigController.php
  lib/Service/AutoConfig/AutoConfig.php
  lib/Service/AutoConfig/Configuration.php
  lib/Service/AutoConfig/ConfigurationDetector.php
  lib/Service/AutoConfig/ImapConnectivityTester.php
  lib/Service/AutoConfig/ImapConnector.php
  lib/Service/AutoConfig/ImapServerDetector.php
  lib/Service/AutoConfig/IspDb.php
  lib/Service/AutoConfig/IspDbConfigurationDetector.php
  lib/Service/AutoConfig/MxRecord.php
  lib/Service/AutoConfig/ServerConfiguration.php
  lib/Service/AutoConfig/SmtpConnectivityTester.php
  lib/Service/AutoConfig/SmtpServerDetector.php
  lib/Service/SetupService.php
  src/components/AccountForm.vue
  src/components/AccountSettings.vue
  src/service/AccountService.js
  src/service/AutoConfigService.js
  src/tests/unit/components/AccountForm.vue.spec.js
  src/views/Setup.vue
  tests/Integration/Service/AutoConfig/MxRecordTest.php
  tests/Unit/Controller/AccountsControllerTest.php
  tests/Unit/Service/Autoconfig/AutoConfigTest.php
  tests/Unit/Service/Autoconfig/ConfigurationDetectorTest.php
  tests/Unit/Service/Autoconfig/ConfigurationTest.php
  tests/Unit/Service/Autoconfig/ImapConnectivityTesterTest.php
  tests/Unit/Service/Autoconfig/ImapConnectorTest.php
  tests/Unit/Service/Autoconfig/ImapServerDetectorTest.php
  tests/Unit/Service/Autoconfig/IspDbTest.php
  tests/Unit/Service/Autoconfig/ServerConfiguration.php
  tests/Unit/Service/Autoconfig/SmtpConnectivityTesterTest.php
  tests/Unit/Service/Autoconfig/SmtpServerDetectorTest.php
  tests/Unit/Service/SetupServiceTest.php
Labels: enhancement, 4. to release

#6848 Fix two-way binding for envelope unselect after delete
  src/components/Envelope.vue
Labels: bug, 3. to review

#6847 Fix Vue custom even casing
  src/components/AccountForm.vue
  src/components/AccountSettings.vue
  src/components/Composer.vue
  src/components/ComposerAttachments.vue
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  src/components/MailboxThread.vue
  src/components/NavigationMailbox.vue
  src/components/TextEditor.vue
  src/components/Thread.vue
  src/components/ThreadEnvelope.vue
  src/directives/drag-and-drop/draggable-envelope/draggable-envelope.js
  src/directives/drag-and-drop/droppable-mailbox/droppable-mailbox.js
  src/views/Setup.vue
Labels: 3. to review, technical debt

#6873 Fix performance logger message for vanished messages
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: 3. to review, backport-request

#6868 Print newly created account ID on CLI
  lib/Command/CreateAccount.php
Labels: enhancement, 3. to review

#6782 Support iMIP requests
  lib/Model/IMAPMessage.php
  src/components/Imip.vue
  src/components/Message.vue
  src/components/imip/EventData.vue
  src/util/eventAttendee.js
Labels: enhancement, 3. to review, feature:integration, feature:imip

#6880 Fix sync tokens missing highestmodseq
  lib/IMAP/IMAPClientFactory.php
Labels: bug, 3. to review, backport-request, performance 🚀, nextcloud-gmbh

#6879 👌 IMPROVE: hide system tags from UI
  src/components/Envelope.vue
  src/components/TagModal.vue
  src/components/ThreadEnvelope.vue
  src/components/tags.js
Labels: enhancement, 4. to release, design

#6897 Fix release date in changelog
  CHANGELOG.md
Labels: 3. to review

#6886 Debug log the account ID threads will be built for
  lib/Listener/AccountSynchronizedThreadUpdaterListener.php
Labels: enhancement, 3. to review

#6899 Release 1.13.7-RC.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#6900 Release 1.13.7-rc.1
  package-lock.json
  package.json
Labels: 3. to review

#6842 Bump webpack from v4 to v5
  .eslintrc.js
  package-lock.json
  package.json
  src/App.vue
  src/ReplyBuilder.js
  src/ckeditor/signature/InsertSignatureCommand.js
  src/components/AccountForm.vue
  src/components/Composer.vue
  src/components/Dashboard.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  src/components/NavigationMailbox.vue
  src/components/Outbox.vue
  src/components/OutboxMessageListItem.vue
  src/crypto/mailvelope.js
  src/crypto/pgp.js
  src/errors/MailboxLockedError.js
  src/errors/ManyRecipientsError.js
  src/errors/NoDraftsMailboxConfiguredError.js
  src/errors/NoSentMailboxConfiguredError.js
  src/errors/NoTrashMailboxConfiguredError.js
  src/errors/convert.js
  src/errors/match.js
  src/html-response.js
  src/main-settings.js
  src/main.js
  src/service/AccountService.js
  src/service/AliasService.js
  src/service/DAVService.js
  src/service/FileSharingService.js
  src/service/MailboxService.js
  src/service/MessageService.js
  src/service/NotificationService.js
  src/store/actions.js
  src/store/index.js
  src/store/mutations.js
  src/store/outbox/actions.js
  src/util/AccountColor.js
  src/util/ErrorMessageFactory.js
  src/util/calendarColor.js
  src/util/priorityInbox.js
  src/util/text.js
  src/util/wait.js
  webpack.common.js
  webpack.prod.js
Labels: 4. to release, dependencies

#6919 Release v1.13.7
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#6920 Fix conversion of imip data charset encoding
  lib/Model/IMAPMessage.php
Labels: bug, 3. to review, feature:imip

#6882 Migrate icons to material design icons
  src/components/AppSettingsMenu.vue
  src/components/Envelope.vue
  src/components/MailboxThread.vue
  src/components/NavigationAccount.vue
  src/components/NavigationMailbox.vue
  src/components/OutboxMessageListItem.vue
Labels: enhancement, 3. to review, design

#6872 Migrate icons to material design
  src/components/Dashboard.vue
  src/components/EmptyMailbox.vue
  src/components/NavigationAccount.vue
  src/components/NoMessageSelected.vue
  src/components/OutboxMessageContent.vue
  src/views/Setup.vue
Labels: enhancement, 4. to release, design

#6923 Add yaml section to .editorconfig
  .editorconfig
Labels: enhancement, 3. to review

#6936 Rename settings to mail settings
  src/components/Navigation.vue
Labels: enhancement, 3. to review, backport-request

#6932 Fix using usual text contrast for envelopes
  src/components/ThreadEnvelope.vue
Labels: bug, 3. to review, design, feature:threading

#6934 Downgrade ckeditor5-vue2 to 3.0.0
  package-lock.json
  package.json
Labels: bug, 3. to review, dependencies

#6871 Migrate composer action menu icons to material design icons + migrate to Vue buttons
  src/components/Composer.vue
Labels: 3. to review

#6870 Migrate to material design icons, the tag icons
  src/components/TagModal.vue
Labels: 3. to review
