Repository nextcloud/mail, pull requests merged in 2022-12, with the labels that each got.

#7710 Add toast when saving iMip response fails
  src/components/Imip.vue
Labels: bug, 3. to review, backport-request, feature:imip

#7715 Fix advanced search scrolling
  src/components/SearchMessages.vue
Labels: bug, 3. to review, design, backport-request

#7430 Add Google OAuth support
  appinfo/routes.php
  doc/admin.md
  lib/AppInfo/Application.php
  lib/Controller/GoogleIntegrationController.php
  lib/Controller/PageController.php
  lib/Events/BeforeImapClientCreated.php
  lib/IMAP/IMAPClientFactory.php
  lib/Integration/GoogleIntegration.php
  lib/Listener/OauthTokenRefreshListener.php
  lib/Service/AccountService.php
  lib/Settings/AdminSettings.php
  package-lock.json
  package.json
  src/components/AccountForm.vue
  src/components/AccountSettings.vue
  src/components/settings/AdminSettings.vue
  src/components/settings/GmailAdminOauthSettings.vue
  src/integration/google.js
  src/main-google-oauth-popup.js
  src/main.js
  src/service/GoogleIntegrationService.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  src/views/GoogleOauthDone.vue
  templates/google_oauth_done.php
  tests/Integration/IMAP/IMAPClientFactoryTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Settings/AdminSettingsTest.php
  webpack.common.js
Labels: 3. to review, feature:integration

#7688 Fix auto config routes for non-admins
  lib/Controller/AutoConfigController.php
Labels: bug, 3. to review, backport-request, regression, comp:setup

#7728 Fix dragover indicator being inherited to children
  src/directives/drag-and-drop/styles/droppable-mailbox.scss
Labels: bug, 4. to release, design, backport-request, regression

#7727 Release 2.2.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#7731 Bump main to 2.3-alpha0
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#7733 Update changelog for 2.2.0 and 2.1.4 release
  CHANGELOG.md
Labels: 3. to review

#7739 Fix risky ConfigurationTest
  tests/Unit/Service/Autoconfig/ConfigurationTest.php
Labels: 3. to review, technical debt

#7740 Fix mailbox cache sync scope of current mailbox
  lib/Db/MessageMapper.php
  lib/Service/Sync/SyncService.php
Labels: bug, 3. to review, backport-request

#7602 Replace vue-clipboard2 with navigation.clipboard api
  package-lock.json
  package.json
  src/components/RecipientBubble.vue
  src/main.js
Labels: 4. to release, technical debt

#7734 Read, cache and expose my ACL rights, if available
  appinfo/info.xml
  lib/Db/Mailbox.php
  lib/Folder.php
  lib/IMAP/FolderMapper.php
  lib/IMAP/MailboxStats.php
  lib/IMAP/MailboxSync.php
  lib/Migration/Version2300Date20221205160349.php
  tests/Unit/Controller/MailboxesControllerTest.php
  tests/Unit/IMAP/FolderMapperTest.php
  tests/Unit/IMAP/MailboxSyncTest.php
  tests/Unit/Service/Sync/SyncServiceTest.php
Labels: enhancement, 3. to review, feature: mailbox sharing

#7755 feat(autoresponder): implement subject placeholder
  src/components/OutOfOfficeForm.vue
  src/tests/data/sieve-vacation-on-subject-placeholder.txt
  src/tests/unit/util/outOfOffice.spec.js
  src/util/outOfOffice.js
Labels: enhancement, 4. to release

#7741 Verify S/MIME signatures
  composer.json
  lib/Contracts/IMailManager.php
  lib/Controller/MessagesController.php
  lib/Model/SMimeData.php
  lib/Service/MailManager.php
  lib/Service/SMimeService.php
  src/components/ThreadEnvelope.vue
  tests/Unit/Controller/MessagesControllerTest.php
Labels: enhancement, 3. to review, security

#7752 Show/hide actions depending on ACL
  src/components/NavigationMailbox.vue
  src/store/getters.js
  src/tests/unit/components/NavigationMailbox.vue.spec.js
Labels: enhancement, 4. to release

#7707 Show outbox only when there is content
  src/components/Navigation.vue
  src/components/NavigationOutbox.vue
Labels: enhancement, 3. to review

#7658 Fix deprecated constructor null message
  tests/Unit/Http/Middleware/ErrorMiddlewareTest.php
Labels: 3. to review, technical debt

#7721 Move OAuth access token into a dedicated column
  appinfo/info.xml
  lib/Db/MailAccount.php
  lib/IMAP/IMAPClientFactory.php
  lib/Integration/GoogleIntegration.php
  lib/Migration/Version2300Date20221215143450.php
  lib/SMTP/SmtpClientFactory.php
Labels: 3. to review, feature:integration

#7689 Show more messages on other section
  src/components/Mailbox.vue
  src/components/MailboxThread.vue
  src/components/SearchMessages.vue
Labels: bug, 3. to review, design

#6715 Add avatars in composer
  src/components/Composer.vue
  src/components/RecipientListItem.vue
Labels: enhancement, 3. to review

#6714 Fix recipients in users-bubble
  lib/Service/ContactsIntegration.php
Labels: bug, 3. to review

#7448 Reroute to priority mailbox when a mailbox is deleted
  src/components/NavigationMailbox.vue
Labels: bug, 4. to release

#7771 Remove unused repository in composer.json
  composer.json
Labels: 3. to review

#7797 fix(setup): Fix storing password when we don't expect one
  lib/Service/SetupService.php
  src/components/AccountForm.vue
Labels: bug, 3. to review

#7796 Validate remote hosts
  doc/admin.md
  lib/Controller/AccountsController.php
  lib/Controller/AutoConfigController.php
  lib/Controller/SieveController.php
  lib/Net/HostnameClassifier.php
  lib/Net/IpAddressClassifier.php
  lib/Validation/RemoteHostValidator.php
  psalm.xml
  tests/Unit/Controller/AccountsControllerTest.php
  tests/Unit/Controller/SieveControllerTest.php
  tests/Unit/Net/HostnameClassifierTest.php
  tests/Unit/Net/IpAddressClassifierTest.php
  tests/Unit/Validation/RemoteHostValidatorTest.php
Labels: bug, 3. to review, backport-request

#7801 Release v2.2.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#7802 Update changelog for 2.2.1 and 2.2.2 release
  CHANGELOG.md
Labels: 3. to review

#7803 [stable1.15] Drop Nextcloud 22 support
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  appinfo/info.xml
Labels: 3. to review

#7804 [stable1.15] Validate remote hosts
  doc/admin.md
  lib/Controller/AccountsController.php
  lib/Controller/AutoConfigController.php
  lib/Controller/SieveController.php
  lib/Net/HostnameClassifier.php
  lib/Net/IpAddressClassifier.php
  lib/Validation/RemoteHostValidator.php
  psalm.xml
  tests/Unit/Controller/AccountsControllerTest.php
  tests/Unit/Controller/SieveControllerTest.php
  tests/Unit/Net/HostnameClassifierTest.php
  tests/Unit/Net/IpAddressClassifierTest.php
  tests/Unit/Validation/RemoteHostValidatorTest.php
Labels: bug, 4. to release

#7805 feat(occ): Add ML prediction command
  appinfo/info.xml
  lib/Command/PredictImportance.php
  lib/Listener/NewMessageClassificationListener.php
  lib/Service/Classification/ImportanceClassifier.php
Labels: enhancement, 4. to release

#7807 ci: Use setup-nextcloud action
  .github/workflows/package.yml
  .github/workflows/test.yml
Labels: 3. to review, technical debt

#7811 fix: endless loop on mailbox initialization
  src/components/Mailbox.vue
Labels: bug, 4. to release, backport-request

#7813 chore(deps): Use conventional commits for bumps
  .github/dependabot.yml
Labels: 3. to review, technical debt

#7815 Revert "chore(deps): Use conventional commits for bumps"
  .github/dependabot.yml
Labels: 3. to review

#7832 chore: Drop dead Dependabot stableX bump config
  .github/dependabot.yml
Labels: 3. to review

#7839 chore: Use conventional commits for dependency bumps
  .github/dependabot.yml
Labels: 3. to review, dependencies
