Repository nextcloud/mail, pull requests merged in 2023-03, with the labels that each got.

#8169 Change delete button styling to icon only for s/mime certificates
  src/components/smime/SmimeCertificateModal.vue
Labels: enhancement, 3. to review

#8156 Fix missing mailboxes on new account
  lib/Controller/AccountsController.php
  tests/Unit/Controller/AccountsControllerTest.php
Labels: bug, 3. to review

#8173 Move import button of smime settings to the right
  src/components/smime/SmimeCertificateModal.vue
Labels: bug, 3. to review, design, feature:smime

#8171 feat(imap): Persist if mailbox is shared or not
  appinfo/info.xml
  lib/Db/Mailbox.php
  lib/IMAP/MailboxSync.php
  lib/Migration/Version3000Date20230301152454.php
  tests/Unit/IMAP/MailboxSyncTest.php
Labels: enhancement, 3. to review

#8176 Add empty content for smime certificate
  src/components/smime/SmimeCertificateModal.vue
Labels: enhancement, 4. to release, design

#8182 feat(acl): Use shared folder icon for shared mailboxes
  src/components/NavigationMailbox.vue
Labels: enhancement, 3. to review, design, feature: mailbox sharing

#8167 chore(smime): handle signature verification early
  lib/Controller/MessagesController.php
  lib/IMAP/ImapMessageFetcher.php
  tests/Integration/IMAP/ImapMessageFetcherIntegrationTest.php
  tests/data/signed-message.txt
  tests/data/smime-certs/imap.localhost.ca.crt
Labels: 4. to release, performance 🚀, feature:smime

#8180 Fix error when to mail is null
  src/components/Composer.vue
Labels: bug, 3. to review

#8184 [stable2.2] Fix error when to mail is null
  src/components/Composer.vue
Labels: bug, 3. to review

#8172 Improve S/MIME verification status icon and wording
  src/components/ThreadEnvelope.vue
Labels: enhancement, 3. to review, feature:smime

#8185 Release v3.0.0-beta.2
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8155 fix(attachments): fetch message once when saving attachments in files
  lib/Controller/MessagesController.php
  tests/Unit/Controller/MessagesControllerTest.php
Labels: enhancement, 3. to review, performance 🚀

#8201 fix: dashboard loading forever
  package-lock.json
  package.json
  webpack.common.js
Labels: bug, 4. to release, backport-request, regression

#8203 chore: don't throw when user denies notifications
  src/service/NotificationService.js
Labels: 3. to review

#8198 [stable3.0] chore(CI): Adjust testing matrix for Nextcloud 26
  .github/workflows/psalm-matrix.yml
  .github/workflows/test.yml
Labels: 3. to review, dependencies

#8190 chore(deps): Do not automerge @nextcloud/vue bumps
  renovate.json
Labels: 3. to review, dependencies

#8197 Bump 3.1.0-alpha.1
  appinfo/info.xml
  package-lock.json
  package.json
  renovate.json
Labels: 3. to review

#8196 fix: archiving messages via shortcut
  src/components/Envelope.vue
  src/components/Mailbox.vue
  src/components/ThreadEnvelope.vue
Labels: bug, 3. to review, backport-request

#8216 v3.0.0-rc.1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8209 feat: respect acl for MailboxInlinePicker
  src/components/MailboxInlinePicker.vue
Labels: enhancement, 3. to review, feature: mailbox sharing

#8237 chore(deps): Disable renovate PHP version bumps
  renovate.json
Labels: 3. to review, dependencies

#8236 chore(deps): Use OSV database for renovate bumps
  renovate.json
Labels: 3. to review, dependencies

#8170 Use NcRichText component from `@nextcloud/vue`
  package-lock.json
  package.json
  src/components/Composer.vue
Labels: bug, 3. to review, feature:composer

#8202 Fix composer margin on rich text
  src/components/TextEditor.vue
Labels: bug, 3. to review, backport-request, feature:editor, feature: HTML mails

#8245 Release v3.0.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8254 chore(deps): Fine-tune renovate security bumps
  renovate.json
Labels: 3. to review

#8253 chore(renovate): add dedicated group for jest packages
  renovate.json
Labels: 3. to review, dependencies

#8256 chore(deps): Use "fix" type for semantic vuln bumps
  renovate.json
Labels: 3. to review, dependencies

#8264 fix: downgrade nextcloud/vue to 7.8.0 to fix envelope list
  package-lock.json
  package.json
Labels: bug, 3. to review, regression, dependencies

#8268 fix(tags): Hide "Has Cal" tag
  src/components/tags.js
Labels: bug, 3. to review, feature:tags

#8271 [stable3.0] fix(deps): bump webpack to v5.76.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#8272 [stable2.2] fix(deps): bump webpack to v5.76.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#8275 fix(avatar): Validate favicon hosts
  lib/Service/Avatar/FaviconSource.php
  tests/Integration/Service/Avatar/FaviconSourceTest.php
  tests/Unit/Service/Avatar/FaviconSourceTest.php
Labels: bug, 3. to review, backport-request

#8279 [stable2.2] ci: Use server stable26 instead of master
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
Labels: 3. to review

#8280 feat(smime): show a warning when a signature is not verified
  src/components/Message.vue
Labels: enhancement, 3. to review, feature:smime

#8235 fix: Prefer text bodies over HTML bodies for message preview
  lib/IMAP/MessageMapper.php
Labels: bug, 4. to release, design, feature: HTML mails

#8285 Release v3.0.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8287 Release v2.2.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8293 chore(deps): Drop eslint-loader
  package-lock.json
  package.json
Labels: 3. to review, technical debt, dependencies

#8296 chore: fix ReturnTypeWillChange warning
  lib/IMAP/Threading/Container.php
Labels: 3. to review, technical debt

#8304 Improve PKCS12 compatibility
  lib/Service/SmimeService.php
  src/components/smime/SmimeCertificateModal.vue
  src/tests/data/user@imap.localhost.chain.p12
  src/tests/unit/util/pkcs12.spec.js
  src/util/pkcs12.js
  tests/Unit/Service/SmimeServiceTest.php
  tests/data/smime-certs/cn-only@imap.localhost.crt
  tests/data/smime-certs/cn-only@imap.localhost.key
Labels: bug, 3. to review, backport-request, feature:smime

#8305 Release v1.15.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#8297 Fix clickable area partially covering timestamp
  src/components/ThreadEnvelope.vue
Labels: bug, 3. to review

#8312 remove RemoteHostValidator duplicate
  lib/Controller/AccountsController.php
  lib/Controller/AutoConfigController.php
  lib/Controller/SieveController.php
  lib/Service/Avatar/FaviconSource.php
  lib/Validation/RemoteHostValidator.php
  tests/Integration/Service/Avatar/FaviconSourceTest.php
  tests/Unit/Controller/AccountsControllerTest.php
  tests/Unit/Controller/SieveControllerTest.php
  tests/Unit/Service/Avatar/FaviconSourceTest.php
  tests/Unit/Validation/RemoteHostValidatorTest.php
Labels: 3. to review, technical debt
