Repository nextcloud/mail, pull requests merged in 2023-08, with the labels that each got.

#8655 fix(Quota): set job time insensitive and lower interval
  lib/BackgroundJob/QuotaJob.php
  tests/Unit/BackgroundJob/QuotaJobTest.php
Labels: 3. to review

#8665 Improve and fix account settings modal header
  src/components/AccountSettings.vue
Labels: bug, enhancement, 3. to review, backport-request

#8669 Release v3.3.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8668 fix reply to sender only
  src/components/MenuEnvelope.vue
Labels: bug, 3. to review, skill:frontend

#8489 Add key property to dashboard messages and fix misc errors for emails with empty from array
  src/components/Dashboard.vue
Labels: bug, 4. to release, backport-request

#6863 👌 IMPROVE: don't open first mail by default
  src/components/Mailbox.vue
  src/components/MailboxThread.vue
  src/components/NoMessageSelected.vue
Labels: enhancement, 3. to review, papercut

#6946 Return to primary actions if envelope actions are closed with more actions open
  src/components/Envelope.vue
Labels: bug, 3. to review

#8627 feat: implement trash retention
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/BackgroundJob/TrashRetentionJob.php
  lib/Contracts/IMailManager.php
  lib/Controller/AccountsController.php
  lib/Db/MailAccount.php
  lib/Db/MailAccountMapper.php
  lib/Db/MessageMapper.php
  lib/Db/MessageRetention.php
  lib/Db/MessageRetentionMapper.php
  lib/Listener/MessageKnownSinceListener.php
  lib/Migration/Version3300Date20230801124717.php
  lib/Service/AccountService.php
  lib/Service/CleanupService.php
  lib/Service/MailManager.php
  lib/Service/Sync/ImapToDbSynchronizer.php
  src/components/AccountSettings.vue
  src/components/TrashRetentionSettings.vue
  tests/Integration/Db/MailAccountTest.php
  tests/Unit/Job/TrashRetentionJobTest.php
  tests/Unit/Listener/MessageKnownSinceListenerTest.php
  tests/Unit/Service/MailManagerTest.php
Labels: enhancement, 3. to review

#8674 Add loading skeletons without avatars
  src/components/LoadingSkeleton.vue
Labels: bug, 3. to review, backport-request

#8581 feat: move messages to junk folder
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Controller/AccountsController.php
  lib/Db/MailAccount.php
  lib/Listener/MailboxesSynchronizedSpecialMailboxesUpdater.php
  lib/Listener/MoveJunkListener.php
  lib/Migration/Version3001Date20230307113544.php
  src/components/AccountDefaultsSettings.vue
  src/components/AccountSettings.vue
  src/components/Envelope.vue
  src/components/JunkSettings.vue
  src/components/MenuEnvelope.vue
  src/components/NavigationMailbox.vue
  src/store/actions.js
  src/store/getters.js
  src/tests/unit/store/actions.spec.js
  src/tests/unit/store/getters.spec.js
  tests/Integration/Db/MailAccountTest.php
  tests/Unit/Listener/MoveJunkListenerTest.php
Labels: enhancement, 2. developing

#8676 Release v3.4.0-alpha.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#8680 Release v3.2.6
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8683 test: Replace docker hub container image with ghcr one
  Makefile
Labels: 3. to review

#8687 Add native date picker for send later
  src/components/Composer.vue
Labels: bug, 3. to review, backport-request

#8686 fix(proxy): Add image proxy rate limit
  lib/Controller/ProxyController.php
  psalm.xml
Labels: bug, 3. to review, backport-request

#8705 Release v3.3.0-rc2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8709 fix(setup): Rate limit auto config attempts
  lib/Controller/AutoConfigController.php
  src/components/AccountForm.vue
Labels: bug, 3. to review, backport-request

#8713 Release v3.4.0-beta.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8694 feat: add snooze mvp
  appinfo/info.xml
  appinfo/routes.php
  lib/BackgroundJob/WakeJob.php
  lib/Controller/AccountsController.php
  lib/Controller/MessagesController.php
  lib/Controller/ThreadController.php
  lib/Db/MailAccount.php
  lib/Db/MessageMapper.php
  lib/Db/MessageSnooze.php
  lib/Db/MessageSnoozeMapper.php
  lib/Db/ThreadMapper.php
  lib/Listener/MailboxesSynchronizedSpecialMailboxesUpdater.php
  lib/Migration/Version3400Date20230807300513.php
  lib/Service/IMipService.php
  lib/Service/SnoozeService.php
  src/components/AccountDefaultsSettings.vue
  src/components/Envelope.vue
  src/components/MenuEnvelope.vue
  src/components/NavigationMailbox.vue
  src/service/MessageService.js
  src/service/ThreadService.js
  src/store/actions.js
  tests/Integration/Db/MailAccountTest.php
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Controller/ThreadControllerTest.php
Labels: enhancement, 3. to review, feature parity

#8720 Release v3.4.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#8729 Fix settings modal when autoresponder is turned off
  src/components/AccountSettings.vue
Labels: bug, 3. to review

#8725 Show full mail subject when mail is open.
  src/components/Thread.vue
Labels: enhancement, 3. to review, design

#8717 Add Caching to Thread summaries
  lib/Controller/PageController.php
  lib/Controller/ThreadController.php
  lib/Service/AiIntegrations/AiIntegrationsService.php
  lib/Service/AiIntegrations/Cache.php
  lib/Settings/AdminSettings.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Controller/ThreadControllerTest.php
Labels: enhancement, 3. to review, skill:backend

#8728 fix(Snooze): Allow snoozing gmail messages
  lib/Db/ThreadMapper.php
Labels: bug, 3. to review

#8716 Add unit tests for thread summary feature
  lib/Service/AiIntegrations/AiIntegrationsService.php
  tests/Unit/Controller/ThreadControllerTest.php
  tests/Unit/Service/AiIntegrationsServiceTest.php
Labels: enhancement, 3. to review

#8749 fix: deprecation warning for drafts controller test
  tests/Unit/Controller/DraftsControllerTest.php
Labels: 3. to review, technical debt

#8752 feat: remove toggle for move junk
  appinfo/info.xml
  lib/Controller/AccountsController.php
  lib/Db/MailAccount.php
  lib/Listener/MoveJunkListener.php
  lib/Migration/Version3400Date20230814160451.php
  src/components/AccountSettings.vue
  src/components/JunkSettings.vue
  src/store/actions.js
  src/tests/unit/store/actions.spec.js
  tests/Unit/Listener/MoveJunkListenerTest.php
Labels: enhancement, 3. to review

#8759 feat(snooze): Disable snooze on AJAX cron
  lib/Controller/PageController.php
  src/components/Envelope.vue
  src/components/MenuEnvelope.vue
  src/main.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  tests/Integration/Db/MailAccountTest.php
  tests/Unit/Controller/PageControllerTest.php
Labels: bug, 4. to release

#8764 remove some warnings from jest frontend tests
  src/tests/unit/components/Composer.vue.spec.js
  src/tests/unit/components/ThreadEnvelope.vue.spec.js
Labels: 3. to review, technical debt

#8755 feat: exclude envelopes from junk from threading view
  src/components/Thread.vue
  src/tests/unit/components/Thread.vue.spec.js
Labels: bug, 3. to review

#8765 fix(snooze): Add cleanup orphan db entries
  lib/Db/MessageSnoozeMapper.php
  lib/Service/CleanupService.php
Labels: bug, 3. to review

#8767 fix(snooze): force sync of snooze mailbox
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: bug, 3. to review

#8743 Fix Lost update between last draft and sending a message
  lib/Controller/DraftsController.php
  lib/Service/DraftsService.php
  lib/Service/OutboxService.php
  src/components/NewMessageModal.vue
  tests/Unit/Service/DraftsServiceTest.php
  tests/Unit/Service/OutboxServiceTest.php
Labels: bug, 3. to review, backport-request, regression

#8754 Snooze mvp follow up
  lib/Controller/MessagesController.php
  lib/Controller/ThreadController.php
  lib/Db/MessageSnoozeMapper.php
  lib/Service/SnoozeService.php
  src/components/Envelope.vue
  src/components/MenuEnvelope.vue
  src/components/NavigationMailbox.vue
  src/service/MessageService.js
  src/service/ThreadService.js
  src/store/actions.js
Labels: bug, 3. to review

#8770 Release v3.4.0-beta.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#8772 Release v3.3.0-rc.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8760 Fix preview text
  composer.json
  composer.lock
  lib/IMAP/MessageMapper.php
Labels: bug, 3. to review

#8778 Fix scroll to on mobile
  src/components/ThreadSummary.vue
Labels: bug, 3. to review, skill:frontend

#8774 fix(Snooze): Sort snooze mailbox as specialUse
  src/imap/MailboxSorter.js
  src/store/mutations.js
  src/tests/unit/imap/MailboxSorter.spec.js
Labels: bug, 4. to release

#8777 Fix thread summary box display on mobile
  src/components/ThreadSummary.vue
Labels: bug, 4. to release, skill:frontend

#8616 feat: parse mailto addresses
  package-lock.json
  package.json
  src/components/MailboxThread.vue
Labels: enhancement, 3. to review

#8762 Added "Mark as spam", "Mark as not spam", "Edit tags" buttons to multiselect menu
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/MenuEnvelope.vue
  src/components/TagModal.vue
Labels: enhancement, 3. to review

#8784 Release v3.2.7
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8789 Release 3.3.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8786 Added missing check to see if envelope is eligible to be removed
  src/components/EnvelopeList.vue
Labels: enhancement, 3. to review

#8785 Made icon colors more uniform
  src/components/Navigation.vue
  src/components/NavigationMailbox.vue
Labels: bug, 3. to review, design, papercut

#8804 [Stable3.3] Adding .prevent to ctrl-click on mail list
  src/components/Envelope.vue
Labels: bug, 3. to review

#8805 Added placeholder for new mailbox input
  src/components/NavigationAccount.vue
Labels: bug, 3. to review

#8822 Release 3.4.0-rc.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review
