Repository nextcloud/mail, pull requests merged in 2023-07, with the labels that each got.

#8575 fix(sync): mailboxes not being synced due to short circuiting
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: bug, 4. to release, backport-request

#8596 chore: Add PR feedback automation
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#8607 chore: Remove unused vars
  lib/Controller/DraftsController.php
  lib/IMAP/Threading/ThreadBuilder.php
  lib/Service/Html.php
Labels: 3. to review, technical debt

#8605 chore: Remove unused phpdoc params
  lib/Contracts/IMailSearch.php
  lib/Controller/AccountsController.php
  lib/Controller/ContactIntegrationController.php
  lib/Controller/GoogleIntegrationController.php
  lib/Controller/ListController.php
  lib/Controller/MessagesController.php
  lib/Controller/MicrosoftIntegrationController.php
  lib/Db/AliasMapper.php
  lib/Db/MailboxMapper.php
  lib/IMAP/Threading/ThreadBuilder.php
  lib/Model/Message.php
  lib/Service/AliasesService.php
  lib/Service/Attachment/AttachmentService.php
  lib/Service/ContactsIntegration.php
Labels: 3. to review, technical debt

#8606 fix(provisioning): Clear cache before returning
  lib/Service/Provisioning/Manager.php
Labels: bug, 3. to review, backport-request

#8603 chore: Ignore HTTP response class templates
  lib/Http/AttachmentDownloadResponse.php
  lib/Http/AvatarDownloadResponse.php
  lib/Http/HtmlResponse.php
  lib/Http/JsonResponse.php
  lib/Http/ProxyDownloadResponse.php
Labels: 4. to release, technical debt

#8597 fix: handle attachments without transfer encoding properly
  lib/IMAP/MessageMapper.php
Labels: bug, 3. to review

#8494 perf(imap): Reduce number of STATUS commands for background mailbox sync
  lib/Db/Mailbox.php
  lib/Folder.php
  lib/IMAP/FolderMapper.php
  lib/IMAP/MailboxStats.php
  lib/IMAP/MailboxSync.php
  tests/Unit/IMAP/FolderMapperTest.php
  tests/Unit/IMAP/MailboxSyncTest.php
Labels: 3. to review, performance 🚀, nextcloud-gmbh

#8614 [stable3.2] ci(test): pull service images from ghcr.io
  .github/workflows/test.yml
Labels: 3. to review

#8551 Fix: Autocompletetion for system address book (not just full matches)
  lib/Service/ContactsIntegration.php
  tests/Unit/Service/ContactsIntegrationTest.php
Labels: bug, 3. to review

#8612 [stable3.2] perf(imap): Reduce number of STATUS commands for background mailbox sync
  lib/Db/Mailbox.php
  lib/Folder.php
  lib/IMAP/FolderMapper.php
  lib/IMAP/MailboxStats.php
  lib/IMAP/MailboxSync.php
  tests/Unit/IMAP/FolderMapperTest.php
  tests/Unit/IMAP/MailboxSyncTest.php
Labels: 2. developing

#8620 Release v3.2.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8611 fix: add preview enhancement job to new accounts joblist
  lib/Service/AccountService.php
Labels: bug, 3. to review, backport-request

#8625 Fix force send mail
  src/components/Composer.vue
  src/components/NewMessageModal.vue
Labels: 3. to review

#8604 chore: Drop unnecessary var annotations
  lib/BackgroundJob/MigrateImportantJob.php
  lib/Db/MessageMapper.php
  lib/Db/TrustedSenderMapper.php
  lib/IMAP/MessageMapper.php
  lib/IMAP/PreviewEnhancer.php
  lib/IMAP/Threading/ThreadBuilder.php
  lib/Listener/InteractionListener.php
  lib/Migration/Version0110Date20180825201241.php
  lib/Migration/Version1101Date20210616141806.php
  lib/Migration/Version3000Date20230301152454.php
  lib/Service/HtmlPurify/TransformURLScheme.php
  lib/Service/MailManager.php
  lib/Service/MailTransmission.php
  lib/Service/SmimeService.php
Labels: 3. to review, technical debt

#8571 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#8638 fix: make nested toolbar working for signature editor
  src/components/AccountSettings.vue
  src/components/SignatureSettings.vue
Labels: bug, 3. to review, backport-request

#8646 fix(search): URL-encode all parameters to preserve special characters
  lib/Service/Search/FilterStringParser.php
  src/components/SearchMessages.vue
Labels: bug, 3. to review, filter:search

#8645 feat(search): Use case-independent wildcard matches and match labels
  lib/Db/MessageMapper.php
Labels: enhancement, 3. to review, filter:search, nextcloud-gmbh

#8637 Declare editing state on new message modal
  src/components/NewMessageModal.vue
Labels: 3. to review

#8610 feat: add notification for quota depletion
  appinfo/info.xml
  lib/Account.php
  lib/AppInfo/Application.php
  lib/BackgroundJob/QuotaJob.php
  lib/Db/MailAccount.php
  lib/Migration/FixBackgroundJobs.php
  lib/Migration/Version3300Date20230706140531.php
  lib/Notification/Notifier.php
  lib/Service/AccountService.php
  tests/Integration/Db/MailAccountTest.php
  tests/Unit/BackgroundJob/QuotaJobTest.php
Labels: enhancement, 3. to review, nextcloud-gmbh

#8658 Release v3.2.5
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8659 Update changelog on main
  CHANGELOG.md
Labels: 3. to review

#8660 Release v3.3.0-alpha.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
