Repository nextcloud/mail, pull requests merged in 2023-02, with the labels that each got.

#7975 [stable2.2] Fix CI
  .github/workflows/test.yml
  lib/Http/Middleware/ProvisioningMiddleware.php
Labels: 3. to review

#7691 Make the composer component stateless
  src/components/Composer.vue
  src/components/ComposerAttachments.vue
  src/components/NewMessageModal.vue
  src/tests/unit/components/Composer.vue.spec.js
Labels: 4. to release, technical debt

#7987 Add Provision info to occ account:export command
  lib/Command/ExportAccount.php
Labels: enhancement, 3. to review, php

#7647 Check if htmlBodyId exists before trying to fetch htmlBody
  lib/IMAP/MessageMapper.php
Labels: bug, 4. to release, backport-request

#7997 Show special use icons based on account preference instead of IMAP attributes
  src/components/NavigationMailbox.vue
Labels: enhancement, 4. to release, design

#7996 fix: allow sending of messages with empty body content
  lib/Service/MimeMessage.php
  tests/Unit/Service/MimeMessageTest.php
Labels: bug, 3. to review, feature: HTML mails

#8002 Release v2.2.3
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8004 fix(provisioning): Return database ID of new configs
  lib/Controller/SettingsController.php
  lib/Service/Provisioning/Manager.php
  src/components/settings/AdminSettings.vue
  tests/Unit/Controller/SettingsControllerTest.php
  tests/Unit/Service/Provisioning/ManagerTest.php
Labels: bug, 3. to review, backport-request

#8003 Update changelog for v2.2.3
  CHANGELOG.md
Labels: 3. to review

#7995 Show recipient email in sent mailboxes
  src/components/Envelope.vue
  src/tests/unit/components/Envelope.vue.spec.js
Labels: bug, 3. to review

#7949 feat(smime): sign outgoing emails
  appinfo/info.xml
  appinfo/routes.php
  lib/Controller/AccountsController.php
  lib/Controller/AliasesController.php
  lib/Controller/MessagesController.php
  lib/Controller/OutboxController.php
  lib/Controller/PageController.php
  lib/Controller/SmimeCertificatesController.php
  lib/Db/Alias.php
  lib/Db/LocalMessage.php
  lib/Db/MailAccount.php
  lib/Db/SmimeCertificate.php
  lib/Db/SmimeCertificateMapper.php
  lib/Exception/SmimeCertificateParserException.php
  lib/Exception/SmimeSignException.php
  lib/Migration/Version2300Date20230127093733.php
  lib/Model/EnrichedSmimeCertificate.php
  lib/Model/NewMessageData.php
  lib/Model/SmimeCertificateInfo.php
  lib/Model/SmimeCertificatePurposes.php
  lib/Model/SmimeData.php
  lib/Service/AliasesService.php
  lib/Service/MailTransmission.php
  lib/Service/SMimeService.php
  lib/Service/SmimeService.php
  src/components/AccountSettings.vue
  src/components/AliasForm.vue
  src/components/AliasSettings.vue
  src/components/AppSettingsMenu.vue
  src/components/Composer.vue
  src/components/ThreadEnvelope.vue
  src/components/smime/SmimeCertificateModal.vue
  src/main.js
  src/service/AccountService.js
  src/service/AliasService.js
  src/service/SmimeCertificateService.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  src/tests/unit/components/Composer.vue.spec.js
  src/tests/unit/util/smime.spec.js
  src/util/smime.js
  tests/Integration/Db/MailAccountTest.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Controller/OutboxControllerTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Service/MailTransmissionTest.php
Labels: enhancement, 3. to review, feature:smime

#7998 ci(code-coverage): Use codecov token to improve CI stability
  .github/workflows/test.yml
Labels: 3. to review

#8015 fix background touches search input
  src/components/MailboxThread.vue
  src/components/SearchMessages.vue
Labels: bug, 3. to review, design

#8023 fix(imap): Log exception of failed namespace fetch
  lib/IMAP/MailboxSync.php
Labels: 3. to review

#8021 fix: use api to read input value
  src/components/NavigationAccount.vue
  src/components/NavigationMailbox.vue
Labels: bug, 3. to review

#8025 Pre-release of v2.3.0alpha4
  package-lock.json
  package.json
Labels: 3. to review

#7991 Use keyboard shortcut only if ACL allows it
  src/components/Mailbox.vue
  src/views/KeyboardShortcuts.vue
Labels: enhancement, 3. to review

#8029 fix account:export command
  lib/Command/ExportAccount.php
Labels: bug, 3. to review, php

#8014 Edit tags in both context menus if ACLs allow it
  src/components/Envelope.vue
  src/components/MenuEnvelope.vue
Labels: enhancement, 3. to review

#8034 chore: don't lint php files in vendor-bin
  composer.json
Labels: 3. to review

#8032 Mark as read only if allowed by ACLs
  src/components/ThreadEnvelope.vue
Labels: enhancement, 3. to review, feature: mailbox sharing

#8035 mark as replied in the backend depending on ACL
  lib/Listener/FlagRepliedMessageListener.php
Labels: enhancement, 3. to review, skill:backend

#8036 Check special use via dedicated method
  lib/Listener/FlagRepliedMessageListener.php
Labels: bug, 3. to review, feature:mailbox-management

#8020 chore(autoloading): Only use authoritative classmaps for production
  composer.json
  krankerl.toml
Labels: 3. to review

#8033 disable drag and drop depending on ACLs
  src/components/Envelope.vue
  src/components/NavigationMailbox.vue
  src/directives/drag-and-drop/draggable-envelope/draggable-envelope.js
Labels: enhancement, 3. to review

#8031 Fix close button position in SearchMessages.vue
  src/components/SearchMessages.vue
Labels: bug, 3. to review, design, backport-request

#8024 feat: respect acl when moving threads and mailboxes
  src/components/MailboxPicker.vue
  src/tests/unit/util/acl.spec.js
  src/util/acl.js
Labels: enhancement, 4. to release, feature: mailbox sharing

#8049 feat(acl): check delete acl for move operation
  src/components/NavigationMailbox.vue
Labels: enhancement, 3. to review, feature: mailbox sharing

#8051 Show active state for mailbox
  src/components/Navigation.vue
Labels: bug, 3. to review

#7675 Refactor "sending" of draft message and undo renaming of unrelated variable
  lib/BackgroundJob/IMipMessageJob.php
  lib/Contracts/ILocalMailboxService.php
  lib/Contracts/IMailTransmission.php
  lib/Controller/DraftsController.php
  lib/Controller/OutboxController.php
  lib/Service/DraftsService.php
  lib/Service/MailTransmission.php
  lib/Service/OutboxService.php
  tests/Unit/Service/DraftsServiceTest.php
  tests/Unit/Service/MailTransmissionTest.php
Labels: bug, 3. to review, feature:drafts

#8053 chore(deps): Enable renovate bumps on main
  renovate.json
Labels: 3. to review, dependencies

#8055 fix(mailvelope): hide the missing pgp key warning when mailevelope is…
  src/components/Composer.vue
Labels: enhancement, 3. to review, backport-request

#8017 Add link picker
  lib/Controller/PageController.php
  package-lock.json
  package.json
  src/components/Composer.vue
  src/main.js
  src/store/getters.js
  tests/Unit/Controller/PageControllerTest.php
Labels: 3. to review, feature:integration, feature:composer

#8057 [stable1.15] chore(deps): Bump loader-utilis
  package-lock.json
Labels: 3. to review

#8058 Release v1.15.2
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8054 docs(smime): rename CA to 0 S/MIME CA
  doc/developer.md
Labels: enhancement, 3. to review

#7692 Add draft id to composer
  src/components/NewMessageModal.vue
  src/service/MessageService.js
  src/store/actions.js
Labels: bug, 3. to review

#8069 fix: handling of envelope fetch error messages
  src/components/Error.vue
  src/components/ThreadEnvelope.vue
Labels: bug, 3. to review, backport-request

#8067 chore(deps): Group ckeditor family for renovate
  renovate.json
Labels: 3. to review, dependencies

#8068 chore(deps): Enable renovate automerge for minor and patch bumps
  renovate.json
Labels: 3. to review, dependencies

#8073 Hide 'clear mailbox' if it doesnt have sufficient rights
  src/components/NavigationMailbox.vue
Labels: enhancement, 3. to review

#8077 chore(deps): Use renovate bot for github actions
  renovate.json
Labels: 3. to review, dependencies

#8026 feat(smime): decrypt incoming messages
  appinfo/info.xml
  lib/Account.php
  lib/Attachment.php
  lib/Contracts/IMailManager.php
  lib/Controller/MessagesController.php
  lib/Db/Message.php
  lib/Db/MessageMapper.php
  lib/Db/SmimeCertificateMapper.php
  lib/Exception/SmimeDecryptException.php
  lib/IMAP/ImapMessageFetcher.php
  lib/IMAP/ImapMessageFetcherFactory.php
  lib/IMAP/MessageMapper.php
  lib/IMAP/MessageStructureData.php
  lib/IMAP/PreviewEnhancer.php
  lib/IMAP/Sync/Synchronizer.php
  lib/Mailbox.php
  lib/Migration/Version2300Date20230214104736.php
  lib/Model/IMAPMessage.php
  lib/Model/SmimeData.php
  lib/Service/Attachment/AttachmentService.php
  lib/Service/ItineraryService.php
  lib/Service/MailManager.php
  lib/Service/MailTransmission.php
  lib/Service/SmimeService.php
  lib/Service/Sync/ImapToDbSynchronizer.php
  src/components/Envelope.vue
  src/components/ThreadEnvelope.vue
  tests/Integration/Framework/ImapTest.php
  tests/Integration/IMAP/AbstractTest.php
  tests/Integration/IMAP/ImapMessageFetcherIntegrationTest.php
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/IMAP/MessageMapperTest.php
  tests/Unit/IMAP/Sync/SynchronizerTest.php
  tests/Unit/Model/IMAPMessageTest.php
  tests/Unit/Service/Attachment/AttachmentServiceTest.php
  tests/Unit/Service/MailManagerTest.php
  tests/Unit/Service/MailTransmissionTest.php
  tests/Unit/Service/SmimeServiceTest.php
  tests/data/decrypted-message-body.txt
  tests/data/decrypted-signed-opaque-message-body.txt
  tests/data/encrypted-message.txt
  tests/data/encrypted-signed-opaque-message.txt
  tests/data/signed-opaque-message.txt
  tests/data/smime-certs/domain.tld.ca.crt
  tests/data/smime-certs/user@domain.tld.crt
  tests/data/smime-certs/user@domain.tld.key
  tests/data/smime-certs/user@imap.localhost.crt
  tests/data/smime-certs/user@imap.localhost.key
Labels: enhancement, 4. to release, feature:smime

#8078 chore(deps): Fine-tune Renovate bot PR labels
  renovate.json
Labels: 3. to review, dependencies

#8090 chore(deps): Assign reviewers to renovate prs
  renovate.json
Labels: 3. to review

#8076 chore(deps): Drop Dependabot
  .github/dependabot.yml
  .github/workflows/dependabot-approve-merge.yml
Labels: 3. to review, dependencies

#8095 chore(deps): Fix ckeditor package group
  renovate.json
Labels: 3. to review, dependencies

#7539 Fix open composer actions after changing encryption mode
  src/components/Composer.vue
Labels: bug, 4. to release, backport-request

#8112 chore(deps): Configure renovate commit titles
  renovate.json
Labels: 3. to review, dependencies

#8101 feat(smime): import pkcs12 certificates
  package-lock.json
  package.json
  src/components/smime/SmimeCertificateModal.vue
  src/tests/data/user@imap.localhost.crt
  src/tests/data/user@imap.localhost.key
  src/tests/data/user@imap.localhost.p12
  src/tests/setup.js
  src/tests/unit/util/pkcs12.spec.js
  src/util/pkcs12.js
Labels: enhancement, 4. to release, feature:smime

#8094 replace hasAcls() with mailboxHasRights()
  src/components/Envelope.vue
  src/components/Mailbox.vue
  src/components/MenuEnvelope.vue
  src/components/NavigationMailbox.vue
  src/components/ThreadEnvelope.vue
Labels: 3. to review, technical debt, feature: mailbox sharing

#8130 feat!(deps): Drop Nextcloud 25 support
  .github/workflows/psalm-matrix.yml
  .github/workflows/test.yml
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#8109 chore(deps): Do not request review for automerge PRs
  renovate.json
Labels: 3. to review, dependencies

#8113 chore(deps): Use sign-off for renovate commits
  renovate.json
Labels: 3. to review, dependencies

#8141 [stable2.2] Bump/json5 and loader utils
  package-lock.json
Labels: 3. to review

#8142 Release v2.2.4
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8152 Revert "fix(deps): bump @nextcloud/dialogs from 3.2.0 to v4.0.1"
  package-lock.json
  package.json
  src/main-settings.js
  src/main.js
Labels: bug, 3. to review, regression

#8147 Add supported PHP version to default list in bug template
  .github/ISSUE_TEMPLATE/bug_report_form.yml
Labels: 3. to review

#8154 Release v3.0.0-alpha.1
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8158 chore: use attachment dto instead of assoc array
  lib/Attachment.php
  lib/Contracts/IMailManager.php
  lib/Controller/MessagesController.php
  lib/IMAP/MessageMapper.php
  lib/Service/MailManager.php
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Service/MailManagerTest.php
Labels: 3. to review, technical debt
