Repository nextcloud/mail, pull requests merged in 2023-12, with the labels that each got.

#9121 Feat/show email on hovering a `RecipientListItem` in the new email modal
  src/components/RecipientListItem.vue
Labels: enhancement, 3. to review, backport-request

#9126 fix(search): Align advanced search UI elements better
  src/components/SearchMessages.vue
Labels: bug, 3. to review, design, backport-request, filter:search

#5602 Exclude pgp signtures as attachments
  lib/IMAP/ImapMessageFetcher.php
Labels: bug, 3. to review

#9136 Align all icons of composer action menu
  src/components/TextEditor.vue
Labels: bug, 3. to review, backport-request

#9131 fix(search): Reduce advanced search icon size
  src/components/SearchMessages.vue
Labels: bug, 3. to review, backport-request, filter:search

#9140 Fix information icon on small screen
  src/components/MailboxThread.vue
Labels: bug, 3. to review

#9074 Exclude empty tags from saving
  src/components/TagModal.vue
Labels: bug, 3. to review, backport-request

#9157 fix: Alien envelopes that vanish and reappear continuously
  src/store/mutations.js
Labels: bug, 3. to review, backport-request, regression

#9143 Move mail settings into a modal
  src/components/AccountSettings.vue
  src/components/AppSettingsMenu.vue
  src/components/Navigation.vue
Labels: 3. to review

#9169 Fix gravatar typo
  src/components/AppSettingsMenu.vue
Labels: 4. to release

#9185 Add keyboard shortcut inside settings modal
  src/components/AppSettingsMenu.vue
  src/views/KeyboardShortcuts.vue
Labels: enhancement, 4. to release

#9174 Enh/trim message preview
  lib/Db/MessageMapper.php
  src/components/Envelope.vue
Labels: 3. to review, php, javascript

#9199 test: Run integration tests in transactions
  tests/Integration/Db/LocalAttachmentMapperTest.php
  tests/Integration/Db/LocalMessageMapperTest.php
  tests/Integration/Db/RecipientMapperTest.php
Labels: 3. to review, backport-request

#8993 fix(provisioning): Clean up orphaned accounts
  lib/Db/MailAccount.php
  lib/Db/MailAccountMapper.php
  lib/Service/CleanupService.php
  tests/Integration/Db/MailAccountMapperTest.php
Labels: bug, 3. to review, backport-request

#9197 fix(provisioning): Do not require master password if disabled
  src/components/settings/ProvisioningSettings.vue
Labels: bug, 3. to review, backport-request, regression

#8868 chore: Remove unused imports
  lib/Migration/Version1100Date20210512142306.php
  lib/Service/SmimeService.php
  tests/Integration/Framework/ImapTest.php
  tests/Integration/Service/AvatarServiceIntegrationTest.php
  tests/Unit/Job/PreviewEnhancementProcessingJobTest.php
Labels: 3. to review

#9194 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
Labels: 4. to release, dependencies, automated

#9205 Fix: Remove unused method
  src/components/AppSettingsMenu.vue
Labels: bug, 4. to release

#9208 Fix: select alias
  src/components/Composer.vue
Labels: 3. to review, regression
