Repository nextcloud/mail, pull requests merged in 2023-04, with the labels that each got.

#8175 improve certificate to alias mapping UI
  src/components/AccountSettings.vue
  src/components/AliasForm.vue
  src/components/AliasSettings.vue
  src/components/CertificateSettings.vue
Labels: enhancement, 4. to release, feature:smime

#8331 chores - Update changelog for 2.2.4, 2.2.5, 3.0.0
  CHANGELOG.md
Labels: 3. to review

#8337 Rename toolbar to toolbarElements
  src/components/NewMessageModal.vue
Labels: enhancement, 3. to review

#8319 fix(strings): Few string fixes spotted while translating
  .gitignore
  src/components/SearchMessages.vue
  src/components/TagModal.vue
Labels: enhancement, 3. to review, feature:composer

#8342 fix(drafts): delete old draft when saving new version
  src/components/NewMessageModal.vue
Labels: bug, 3. to review, backport-request, regression, feature:composer

#8346 refactor: replace deprecated IQueryBuilder::execute
  lib/Db/AliasMapper.php
  lib/Db/CollectedAddressMapper.php
  lib/Db/LocalAttachmentMapper.php
  lib/Db/LocalMessageMapper.php
  lib/Db/MailAccountMapper.php
  lib/Db/MailboxMapper.php
  lib/Db/MessageMapper.php
  lib/Db/RecipientMapper.php
  lib/Db/StatisticsDao.php
  lib/Db/TagMapper.php
  lib/Db/ThreadMapper.php
  lib/Db/TrustedSenderMapper.php
  lib/Migration/Version0110Date20180825201241.php
  lib/Migration/Version0161Date20190902103701.php
  lib/Migration/Version0161Date20190902114635.php
  lib/Migration/Version1030Date20200228105714.php
  lib/Migration/Version1040Date20200422130220.php
  lib/Migration/Version1060Date20201015084952.php
  lib/Migration/Version1100Date20210419080523.php
  lib/Migration/Version1105Date20210922104324.php
  lib/Migration/Version2010Date20221002201527.php
  tests/Integration/Db/CollectedAddressMapperTest.php
  tests/Integration/Db/LocalAttachmentMapperTest.php
  tests/Integration/Db/LocalMessageMapperTest.php
  tests/Integration/Db/MailboxMapperTest.php
  tests/Integration/Db/MessageMapperTest.php
  tests/Integration/Db/RecipientMapperTest.php
  tests/Integration/Db/TrustedSenderMapperTest.php
Labels: 3. to review, technical debt

#8336 fix: colors button dark-theme #3231
  src/components/AppSettingsMenu.vue
Labels: bug, 3. to review

#8340 Fix warnings because of missing aria-label on NcButton component
  src/components/AccountForm.vue
  src/components/AliasForm.vue
  src/components/AliasSettings.vue
  src/components/AppSettingsMenu.vue
  src/components/CertificateSettings.vue
  src/components/Composer.vue
  src/components/Error.vue
  src/components/Imip.vue
  src/components/MailboxPicker.vue
  src/components/NewMessageButtonHeader.vue
  src/components/NewMessageModal.vue
  src/components/OutOfOfficeForm.vue
  src/components/RecipientBubble.vue
  src/components/SearchMessages.vue
  src/components/SieveAccountForm.vue
  src/components/SieveFilterForm.vue
  src/components/SignatureSettings.vue
  src/components/ThreadEnvelope.vue
  src/components/TrustedSenders.vue
  src/components/settings/AdminSettings.vue
  src/components/settings/AntiSpamSettings.vue
  src/components/settings/ProvisioningSettings.vue
  src/components/smime/SmimeCertificateModal.vue
Labels: bug, 3. to review

#8355 fix: style of "Save sieve script" button
  src/components/SieveFilterForm.vue
Labels: bug, 3. to review, design, backport-request

#8341 fix(composer): add gap between primary actions
  src/components/Composer.vue
Labels: bug, 4. to release, design, feature:composer

#8344 fix: Merge overlapping recipient popovers
  src/components/RecipientBubble.vue
Labels: bug, 3. to review, regression

#8367 fix(imap): Chunk UIDs by string length
  lib/IMAP/Sync/Synchronizer.php
  lib/functions.php
  tests/Unit/FunctionsTest.php
  tests/Unit/IMAP/Sync/SynchronizerTest.php
Labels: bug, 3. to review, nextcloud-gmbh

#8345 chore(deps): Prevent automerge of non-semantic cs-fixer bumps
  renovate.json
Labels: 3. to review, dependencies

#7992 fix(provisioning): Clear config cache after every mutation
  lib/Service/Provisioning/Manager.php
Labels: bug, 4. to release, backport-request

#8350 enhancement: sort tags alphabetically
  src/components/SearchMessages.vue
  src/components/TagModal.vue
Labels: enhancement, 3. to review

#8294 Show message timestamp in action menu
  src/components/Envelope.vue
  src/util/shortRelativeDatetime.js
Labels: enhancement, 3. to review, skill:frontend

#8393 Release v2.2.6
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8394 fix: Add missing background box for redirect page
  templates/redirect.php
Labels: bug, 3. to review, backport-request, regression

#8383 fix(imap): Chunk MessageMapper::findByIds by command length
  lib/IMAP/MessageMapper.php
  lib/IMAP/Sync/Synchronizer.php
  lib/Service/MailManager.php
  tests/Unit/IMAP/MessageMapperTest.php
Labels: bug, 3. to review, backport-request, nextcloud-gmbh

#8405 chore: format js code with eslint
  src/components/NewMessageModal.vue
  src/components/RecipientBubble.vue
Labels: 4. to release, technical debt

#8408 chore(deps): Use stable3.1 instead of stable3.0 for renovate
  renovate.json
Labels: 3. to review, dependencies

#8376 Display email address
  src/components/ThreadEnvelope.vue
Labels: enhancement, 4. to release

#8416 fix: Position thread envelope icons relative to avatar
  src/components/Envelope.vue
  src/components/ThreadEnvelope.vue
Labels: 3. to review, design

#8418 perf(frontend): Load NewMessageModal async
  src/views/Home.vue
Labels: 3. to review, performance 🚀

#8420 perf(frontend): Load the account settings modal async
  src/components/AccountSettings.vue
  src/components/NavigationAccount.vue
Labels: enhancement, 3. to review, performance 🚀

#8395 feat: Easy unsubscribe from lists with http unsubscribe header
  lib/IMAP/ImapMessageFetcher.php
  lib/Model/IMAPMessage.php
  src/components/ConfirmationModal.vue
  src/components/ThreadEnvelope.vue
  src/tests/unit/components/ConfirmationModal.vue.spec.js
  tests/Unit/Model/IMAPMessageTest.php
Labels: enhancement, 3. to review, feature parity

#8421 chore: Fix undeclared properties in tests
  tests/Unit/Controller/AccountsControllerTest.php
  tests/Unit/Service/GroupsIntegrationTest.php
  tests/Unit/Service/MailTransmissionTest.php
Labels: 3. to review, technical debt

#8419 chore(deps-dev): downgrade postcss-loader to ^4.3.0
  package-lock.json
  package.json
  renovate.json
Labels: 4. to release, regression, dependencies
