Repository nextcloud/mail, pull requests merged in 2023-11, with the labels that each got.

#9046 chore(release): v3.5.0-beta1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#8870 feat: delete tags
  appinfo/routes.php
  lib/Contracts/IMailManager.php
  lib/Controller/TagsController.php
  lib/Db/MessageTags.php
  lib/Db/MessageTagsMapper.php
  lib/Service/MailManager.php
  src/components/DeleteTagModal.vue
  src/components/TagItem.vue
  src/components/TagModal.vue
  src/service/MessageService.js
  src/store/actions.js
  src/store/mutations.js
  tests/Unit/Service/MailManagerTest.php
Labels: enhancement, 3. to review, feature:tags, skill:backend, skill:frontend

#9053 Add possiblitity to search message bodies in priority inbox
  lib/Controller/PageController.php
  src/components/AppSettingsMenu.vue
  src/components/SearchMessages.vue
  src/main.js
  templates/index.php
  tests/Unit/Controller/PageControllerTest.php
Labels: enhancement, 3. to review

#8231 add sorting capabilities to mail
  lib/Contracts/IMailSearch.php
  lib/Controller/AccountsController.php
  lib/Controller/MailboxesController.php
  lib/Controller/MessagesController.php
  lib/Controller/PageController.php
  lib/Db/MessageMapper.php
  lib/IMAP/Sync/Synchronizer.php
  lib/Service/Search/MailSearch.php
  lib/Service/Sync/SyncService.php
  src/components/AppSettingsMenu.vue
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  src/main.js
  src/service/MessageService.js
  src/store/actions.js
  src/store/mutations.js
  src/tests/unit/store/actions.spec.js
  src/tests/unit/store/mutations.spec.js
  tests/Integration/IMAP/MessageMapperTest.php
  tests/Integration/MailboxSynchronizationTest.php
  tests/Integration/Service/AntiSpamServiceIntegrationTest.php
  tests/Integration/Service/OutboxServiceIntegrationTest.php
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Service/Search/MailSearchTest.php
  tests/Unit/Service/Sync/SyncServiceTest.php
Labels: enhancement, 3. to review

#9055 Fix colors for slash command and emoji picker for dark/light theme
  src/components/TextEditor.vue
Labels: bug, 3. to review, feature:editor, skill:frontend

#9052 fix(search): Fix combining IMAP and DB search results
  lib/Db/MessageMapper.php
Labels: bug, 3. to review, filter:search

#9056 Fix multiple tags with same label
  src/components/TagModal.vue
Labels: bug, 3. to review

#9008 feat(provisioning): Master password support
  appinfo/info.xml
  lib/Db/Provisioning.php
  lib/Db/ProvisioningMapper.php
  lib/Http/Middleware/ProvisioningMiddleware.php
  lib/Migration/Version3500Date20231005091430.php
  lib/Service/Provisioning/Manager.php
  package-lock.json
  package.json
  src/components/Navigation.vue
  src/components/settings/ProvisioningSettings.vue
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  tests/Unit/Db/ProvisioningTest.php
  tests/Unit/Http/Middleware/ProvisioningMiddlewareTest.php
  tests/Unit/Service/Provisioning/ManagerTest.php
Labels: enhancement, 3. to review

#9002 feat(search): allow date and recipient search
  lib/AppInfo/Application.php
  lib/Db/MessageMapper.php
  lib/Search/FilteringProvider.php
  lib/Search/Provider.php
  psalm.xml
  tests/Unit/Search/FilteringProviderTest.php
  tests/psalm-baseline.xml
Labels: enhancement, 3. to review

#9070 chore: initialize $lastMessageTimestamp with null
  lib/Controller/MailboxesController.php
Labels: 3. to review

#9062 Fix: delete tags unset before confirmation
  src/components/DeleteTagModal.vue
  src/components/TagItem.vue
  src/components/TagModal.vue
Labels: bug, 3. to review, feature:tags

#9080 perf: Add performance logger to clean up
  lib/BackgroundJob/CleanupJob.php
  lib/Command/CleanUp.php
  lib/Service/CleanupService.php
Labels: 3. to review, performance 🚀

#9071 fix: allow syncing of mailboxes with a trailing space
  appinfo/info.xml
  lib/Db/Mailbox.php
  lib/Db/MailboxMapper.php
  lib/IMAP/MailboxSync.php
  lib/Migration/Version3500Date20231115182612.php
  lib/Migration/Version3500Date20231115184458.php
  tests/Integration/Db/MailboxMapperTest.php
Labels: bug, 3. to review

#9088 feat(deps): Support Nextcloud 29
  .github/workflows/psalm-matrix.yml
  .github/workflows/test.yml
  appinfo/info.xml
Labels: 3. to review

#9077 feat: apply personal out-of-office data to the auto responder
  appinfo/info.xml
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/Controller/OutOfOfficeController.php
  lib/Controller/PageController.php
  lib/Controller/SieveController.php
  lib/Db/MailAccount.php
  lib/Exception/OutOfOfficeParserException.php
  lib/Listener/OutOfOfficeListener.php
  lib/Migration/Version3500Date20231114180656.php
  lib/Service/OutOfOffice/OutOfOfficeParser.php
  lib/Service/OutOfOffice/OutOfOfficeParserResult.php
  lib/Service/OutOfOffice/OutOfOfficeState.php
  lib/Service/OutOfOfficeService.php
  lib/Service/SieveService.php
  lib/Sieve/NamedSieveScript.php
  package-lock.json
  package.json
  psalm.xml
  src/components/OutOfOfficeForm.vue
  src/service/OutOfOfficeService.js
  src/tests/unit/util/outOfOffice.spec.js
  src/util/outOfOffice.js
  tests/Integration/Db/MailAccountTest.php
  tests/Unit/Controller/OutOfOfficeControllerTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Controller/SieveControllerTest.php
  tests/Unit/Service/OutOfOffice/OutOfOfficeParserTest.php
  tests/Unit/Service/SieveServiceTest.php
  tests/data/sieve-vacation-cleaned.txt
  tests/data/sieve-vacation-off.txt
  tests/data/sieve-vacation-on-no-end-date.txt
  tests/data/sieve-vacation-on-special-chars-message.txt
  tests/data/sieve-vacation-on-special-chars-subject.txt
  tests/data/sieve-vacation-on-subject-placeholder.txt
  tests/data/sieve-vacation-on.txt
  tests/psalm-baseline.xml
Labels: enhancement, 3. to review, backport-request

#9091 fix: add name_hash as nullable
  appinfo/info.xml
  lib/Migration/Version3500Date20231115182612.php
  lib/Migration/Version3500Date20231115184458.php
Labels: bug, 3. to review

#9090 [stable3.5] feat: apply personal out-of-office data to the auto responder
  appinfo/info.xml
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/Controller/OutOfOfficeController.php
  lib/Controller/PageController.php
  lib/Controller/SieveController.php
  lib/Db/MailAccount.php
  lib/Exception/OutOfOfficeParserException.php
  lib/Listener/OutOfOfficeListener.php
  lib/Migration/Version3500Date20231114180656.php
  lib/Service/OutOfOffice/OutOfOfficeParser.php
  lib/Service/OutOfOffice/OutOfOfficeParserResult.php
  lib/Service/OutOfOffice/OutOfOfficeState.php
  lib/Service/OutOfOfficeService.php
  lib/Service/SieveService.php
  lib/Sieve/NamedSieveScript.php
  package-lock.json
  package.json
  psalm.xml
  src/components/OutOfOfficeForm.vue
  src/service/OutOfOfficeService.js
  src/tests/unit/util/outOfOffice.spec.js
  src/util/outOfOffice.js
  tests/Integration/Db/MailAccountTest.php
  tests/Unit/Controller/OutOfOfficeControllerTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Controller/SieveControllerTest.php
  tests/Unit/Service/OutOfOffice/OutOfOfficeParserTest.php
  tests/Unit/Service/SieveServiceTest.php
  tests/data/sieve-vacation-cleaned.txt
  tests/data/sieve-vacation-off.txt
  tests/data/sieve-vacation-on-no-end-date.txt
  tests/data/sieve-vacation-on-special-chars-message.txt
  tests/data/sieve-vacation-on-special-chars-subject.txt
  tests/data/sieve-vacation-on-subject-placeholder.txt
  tests/data/sieve-vacation-on.txt
  tests/psalm-baseline.xml
Labels: 3. to review

#9092 fix: add name_hash as nullable
  lib/Migration/Version3500Date20231115182612.php
  lib/Migration/Version3500Date20231115184458.php
Labels: 3. to review

#9093 chore: add todos about injecting IAvailabilityCoordinator
  lib/Controller/OutOfOfficeController.php
  lib/Controller/PageController.php
Labels: 3. to review

#9095 fix: listen to more out-of-office events to prevent missed changes
  lib/AppInfo/Application.php
  lib/Listener/OutOfOfficeListener.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: bug, 3. to review, backport-request

#9104 ci: Test against stable28, not master for stable3.4
  .github/workflows/test.yml
Labels: 3. to review
