Repository nextcloud/mail, pull requests merged in 2024-12, with the labels that each got.

#10438 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10442 fix(imap): Consider charset for preview text decoding
  lib/IMAP/MessageMapper.php
  tests/Unit/IMAP/MessageMapperTest.php
Labels: bug, 4. to release, backport-request

#10446 fix(ui): Restore account quota fetching
  src/components/NavigationAccount.vue
Labels: bug, 3. to review, backport-request

#10455 ci: Update stable branches for public suffix updates
  .github/workflows/update-public-suffix-list.yml
Labels: 3. to review

#10457 [stable3.7] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10456 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10454 ci: Fix public suffix data file path
  .github/workflows/update-public-suffix-list.yml
Labels: 3. to review

#10460 [stable4.0] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10459 [stable4.1] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10390 fix(contactsintegration): Limit number of matches
  lib/Service/ContactsIntegration.php
  tests/Unit/Service/ContactsIntegrationTest.php
Labels: bug, 3. to review, backport-request

#10468 [stable4.1] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10466 [stable4.0] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10467 [stable3.7] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10470 fix(ui): Add padding to primary evenlope actions
  src/components/EnvelopePrimaryActions.vue
Labels: bug, 3. to review, backport-request

#10187 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10437 feat: make multiselect menu more discoverable
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/MenuEnvelope.vue
Labels: enhancement, 3. to review

#10476 fix: phishing detection fixes
  lib/Service/PhishingDetection/DateCheck.php
  lib/Service/PhishingDetection/LinkCheck.php
  tests/Unit/Service/Phishing/DateCheckTest.php
  tests/Unit/Service/Phishing/LinkCheckTest.php
Labels: bug, 3. to review

#10479 [stable4.1] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10482 chore: welcome back webpack
  .eslintrc.js
  .gitignore
  babel.config.cjs
  babel.config.js
  css/html-response.css
  css/mail.scss
  css/mobile.scss
  css/redirect.css
  jest.config.js
  krankerl.toml
  lib/Controller/MessagesController.php
  lib/Http/HtmlResponse.php
  package-lock.json
  package.json
  patches/vue-tabs-component+1.5.0.patch
  src/autoredirect.js
  src/components/Envelope.vue
  src/components/NavigationAccount.vue
  src/components/NewMessageModal.vue
  src/components/TextEditor.vue
  src/components/ThreadEnvelope.vue
  src/html-response.js
  src/main-oauth-popup.js
  src/main-settings.js
  src/main.js
  src/router.js
  src/views/Home.vue
  templates/index.php
  templates/oauth_done.php
  templates/redirect.php
  templates/settings-admin.php
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Http/HtmlResponseTest.php
  vite.config.js
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
  webpack.test.js
Labels: 3. to review, performance 🚀

#10483 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10491 [stable4.1] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10478 [stable4.0] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10496 fix(Envelope): RTL support
  src/components/Envelope.vue
  src/components/EnvelopeSkeleton.vue
Labels: bug, 3. to review

#10494 fix(AccountForm): RTL support
  src/components/AccountForm.vue
Labels: bug, 3. to review, design, skill:frontend

#10502 ci: Only update public suffix list twice a month
  .github/workflows/update-public-suffix-list.yml
Labels: 3. to review

#10501 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10500 [stable4.1] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10484 [stable3.7] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10505 fix: wrong path for itinerary executable
  lib/Migration/MakeItineraryExtractorExecutable.php
Labels: bug, 3. to review, backport-request

#10510 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10511 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10514 fix: Disable mail provider
  lib/AppInfo/Application.php
Labels: 3. to review

#10517 ci: Update stable branches to 3.7 and 4.1
  .tx/backport
  renovate.json
Labels: 3. to review

#10277 feat: classify emails by importance based on subjects
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/BackgroundJob/TrainImportanceClassifierJob.php
  lib/Command/PredictImportance.php
  lib/Command/RunMetaEstimator.php
  lib/Command/TrainAccount.php
  lib/Db/Classifier.php
  lib/Db/ClassifierMapper.php
  lib/Listener/NewMessageClassificationListener.php
  lib/Migration/Version4100Date20241021091352.php
  lib/Model/Classifier.php
  lib/Model/ClassifierPipeline.php
  lib/Service/Classification/FeatureExtraction/CompositeExtractor.php
  lib/Service/Classification/FeatureExtraction/SubjectExtractor.php
  lib/Service/Classification/ImportanceClassifier.php
  lib/Service/Classification/NewMessagesClassifier.php
  lib/Service/Classification/PersistenceService.php
  lib/Service/Classification/RubixMemoryPersister.php
  lib/Service/CleanupService.php
  lib/Service/Sync/ImapToDbSynchronizer.php
Labels: enhancement, 3. to review, feature:priority inbox

#10523 fix(notifications): Notifier::prepare() threw \InvalidArgumentExcepti…
  lib/Notification/Notifier.php
Labels: 3. to review, backport-request

#10526 fix: make filter routes available for normal users
  lib/Controller/FilterController.php
Labels: bug, 3. to review

#10465 feat: ai message summary
  lib/AppInfo/Application.php
  lib/Db/Message.php
  lib/Listener/NewMessagesSummarizeListener.php
  lib/Listener/TaskProcessingListener.php
  lib/Migration/Version4100Date20241209000000.php
  lib/Service/AiIntegrations/AiIntegrationsService.php
  package-lock.json
  package.json
  src/components/Envelope.vue
  tests/Unit/Service/AiIntegrationsServiceTest.php
Labels: enhancement, 4. to release

#10531 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
