Repository nextcloud/mail, pull requests merged in 2024-02, with the labels that each got.

#9232 fix(imap): Only rate limit actual auth errors
  lib/IMAP/ImapClientRateLimitingDecorator.php
Labels: bug, 4. to release, backport-request

#9283 Add aria-label-combobox on NcSelect
  src/components/CertificateSettings.vue
  src/components/Imip.vue
  src/components/RecipientBubble.vue
  src/components/TaskModal.vue
Labels: 3. to review

#9269 fix(quota): don't divide by limit zero
  lib/Account.php
  tests/Unit/BackgroundJob/QuotaJobTest.php
Labels: bug, 3. to review, backport-request

#9235 perf(sync): Reduce db operations for accounts without CONDSTORE
  lib/Db/MessageMapper.php
Labels: enhancement, 3. to review, performance 🚀

#9296 fix(setup): Increase rate limit
  lib/Controller/AutoConfigController.php
Labels: bug, 3. to review, comp:setup

#9308 fix(composer): duplicate label in to, cc and bcc selects
  src/components/Composer.vue
Labels: bug, 3. to review, regression, feature:composer

#9309 Delete attachments after removing it from composer
  src/components/Composer.vue
  src/components/ComposerAttachments.vue
Labels: bug, 3. to review

#9315 [Bugfix #9281]: Added check in condition if accounts are not equal to null
  src/views/Home.vue
Labels: bug, 4. to release, backport-request

#9316 chore: remove deprecated dashboard listener
  lib/Listener/DashboardPanelListener.php
Labels: 3. to review, technical debt, backport-request

#9323 enh: change reply button placement
  src/components/Message.vue
Labels: 3. to review, skill:frontend

#9324 fix(setup): Sort MX records by weight
  lib/Service/AutoConfig/MxRecord.php
Labels: bug, 3. to review, comp:setup, feat:autoconfig

#9320 fix(composer): creating new options in recipient selects
  src/components/Composer.vue
Labels: bug, 3. to review, feature:composer

#9328 fix(setup): Use MX sort result
  lib/Service/AutoConfig/MxRecord.php
Labels: bug, 3. to review, backport-request

#9327 fix(setup): Use MX record TLD for ISPDB lookup
  appinfo/routes.php
  lib/Controller/AutoConfigController.php
  src/components/AccountForm.vue
  src/service/AutoConfigService.js
Labels: bug, 3. to review, comp:setup, feat:autoconfig

#9344 feat(integration): Support DESCRPTION for events
  src/components/EventModal.vue
Labels: enhancement, 3. to review, feature:integration

#9346 Fix the scrolling for empty content on setup mail
  src/views/Setup.vue
Labels: bug, 3. to review

#9348 Fix loading thread position
  src/components/Loading.vue
Labels: bug, 3. to review

#9341 fix(message): Translate task description label
  src/components/TaskModal.vue
Labels: bug, 3. to review, feature:integration, backport-request

#9355 fix(smime): alias to cert mapping in account settings
  src/components/CertificateSettings.vue
Labels: bug, 3. to review, regression, feature:smime

#9352 Fix: Add to contact ncSelect
  src/components/RecipientBubble.vue
Labels: bug, 3. to review, regression

#9359 Better error message for null mailbox stats
  lib/IMAP/FolderMapper.php
  tests/Integration/Service/FolderMapperIntegrationTest.php
  tests/Unit/IMAP/FolderMapperTest.php
Labels: enhancement, 3. to review

#9272 fix(setup) - correctly apply EMAILLOCALPART (take 2)
  lib/Service/AutoConfig/IspDb.php
Labels: bug, 3. to review, backport-request, comp:setup, skill:backend

#9373 chore(deps): Update stable branches for Renovate
  renovate.json
Labels: 3. to review, dependencies

#9366 feat(integration): Use LLM to fill event details
  appinfo/routes.php
  lib/Controller/ThreadController.php
  lib/Model/EventData.php
  lib/Service/AiIntegrations/AiIntegrationsService.php
  src/components/EventModal.vue
  src/service/AiIntergrationsService.js
  src/tests/unit/components/EventModal.vue.spec.js
  tests/Unit/Controller/ThreadControllerTest.php
  tests/Unit/Model/EventDataTest.php
  tests/Unit/Service/AiIntegrationsServiceTest.php
  tests/psalm-baseline.xml
Labels: enhancement, 4. to release, feature:integration

#5882 Change how charsets are detected for emails
  lib/IMAP/Charset/Converter.php
  lib/IMAP/ImapMessageFetcher.php
  lib/IMAP/ImapMessageFetcherFactory.php
  tests/Unit/IMAP/Charset/ConverterTest.php
Labels: bug, 3. to review

#8880 Implement Reply-To header support when replying
  lib/Model/IMAPMessage.php
  lib/Model/IMessage.php
  lib/Model/Message.php
  src/ReplyBuilder.js
  src/store/actions.js
  tests/Unit/Model/IMAPMessageTest.php
Labels: bug, 4. to release

#9295 perf(db): optimise indices of mail tables
  lib/Listener/OptionalIndicesListener.php
  lib/Migration/Version1100Date20210304143008.php
  lib/Migration/Version1130Date20220412111833.php
  lib/Migration/Version2300Date20221216115727.php
  lib/Migration/Version3600Date20240205180726.php
Labels: 4. to release, performance 🚀

#9280 chore(vue3): migrate deprecated template syntax
  src/components/Composer.vue
  src/components/MailboxThread.vue
  src/components/NavigationMailbox.vue
  src/components/OutboxMessageListItem.vue
  src/components/TaskModal.vue
  src/components/Thread.vue
Labels: 4. to release, technical debt

#9408 ci: Add npm audit fix workflow
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#9413 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9414 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9302 enh: Use filepicker Vue component
  src/components/ComposerAttachments.vue
Labels: enhancement, 4. to release

#9376 feat(integration): Combine all LLM feature flags
  appinfo/info.xml
  appinfo/routes.php
  lib/Controller/PageController.php
  lib/Controller/SettingsController.php
  lib/Migration/Version3600Date20240227172825.php
  lib/Settings/AdminSettings.php
  package-lock.json
  package.json
  src/components/EventModal.vue
  src/components/Thread.vue
  src/components/ThreadEnvelope.vue
  src/components/settings/AdminSettings.vue
  src/service/SettingsService.js
  src/tests/unit/components/EventModal.vue.spec.js
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Settings/AdminSettingsTest.php
Labels: enhancement, 4. to release, feature:integration

#9425 fix: Hack CSS to restore envelope styling
  src/components/Envelope.vue
Labels: bug, 3. to review, regression
