Repository nextcloud/mail, pull requests merged in 2024-08, with the labels that each got.

#9962 chore: update kitinerary-sys
  composer.lock
Labels: 3. to review, dependencies

#9956 Thread: make recipient bubbles prettier
  src/components/RecipientBubble.vue
  src/components/Thread.vue
Labels: 3. to review

#9963 chore: update developer documentation
  doc/developer.md
Labels: 3. to review

#9940 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9972 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9971 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9878 fix(composer): Adjust expand/collapse cc/bcc icon size
  src/components/Composer.vue
Labels: 3. to review, design

#9927 fix(search): Improve quick search element alignment
  src/components/SearchMessages.vue
Labels: bug, 3. to review, design, filter:search

#9977 fix:change the button to new style
  src/components/MdnRequest.vue
Labels: 3. to review

#9983 chore: drop ocp/nextcloud composer (dev) dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#9928 Restyle envelope view
  src/components/Envelope.vue
  src/components/EnvelopeSkeleton.vue
Labels: 2. developing

#9989 feat: make sieve filter form only resizable vertically
  src/components/SieveFilterForm.vue
Labels: enhancement, 3. to review, design

#9991 fix: case insensitive comparison for contact emails
  lib/Service/PhishingDetection/ContactCheck.php
  tests/Unit/Service/Phishing/ContactCheckTest.php
Labels: bug, 3. to review, skill:backend

#9985 feat(composer): Redesign inputs
  src/components/Composer.vue
Labels: enhancement, 3. to review

#9993 chore: bump version to trigger migrations
  appinfo/info.xml
Labels: bug, 3. to review

#9925 fix(tags): Hide Notjunk tag
  src/components/tags.js
Labels: bug, 3. to review

#9994 Feat: link checking for phishing detection
  composer.json
  composer.lock
  lib/Service/PhishingDetection/LinkCheck.php
  lib/Service/PhishingDetection/PhishingDetectionService.php
  src/components/PhishingWarning.vue
  tests/Integration/Service/Phishing/PhishingDetectionServiceIntegrationTest.php
  tests/Unit/Service/Phishing/PhishingDetectionServiceTest.php
Labels: enhancement, 3. to review, skill:backend

#9990 fix(autoresponder): enable immediately on an OutOfOfficeStartedEvent
  lib/Listener/OutOfOfficeListener.php
Labels: bug, 4. to release, feature:integration

#9986 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9987 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9988 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9979 chore(dashboard): remove obsolete js widget
  lib/AppInfo/Application.php
  lib/Dashboard/ImportantMailWidgetV2.php
  lib/Dashboard/MailWidget.php
  lib/Dashboard/MailWidgetV2.php
  lib/Dashboard/UnreadMailWidgetV2.php
  src/components/Dashboard.vue
  src/main-dashboard.js
  src/views/DashboardImportant.vue
  src/views/DashboardUnread.vue
  webpack.common.js
Labels: 3. to review, technical debt

#9998 refactor: Drop request debugging log
  src/http/sessionExpiryHandler.js
Labels: 4. to release, technical debt

#10001 fix: handle missing email in contact check
  lib/Service/ContactsIntegration.php
  lib/Service/PhishingDetection/ContactCheck.php
Labels: bug, 3. to review

#10005 ci: ignore version requirement for ci workflows
  .github/workflows/test.yml
Labels: 3. to review

#10002 fix: line ending for sieve scripts should be clrf
  .gitattributes
  REUSE.toml
  lib/Service/OutOfOffice/OutOfOfficeParser.php
  tests/Unit/Service/OutOfOffice/OutOfOfficeParserTest.php
  tests/data/sieve-vacation-cleaned.sieve
  tests/data/sieve-vacation-off.sieve
  tests/data/sieve-vacation-on-no-end-date.sieve
  tests/data/sieve-vacation-on-no-tz.sieve
  tests/data/sieve-vacation-on-special-chars-message.sieve
  tests/data/sieve-vacation-on-special-chars-subject.sieve
  tests/data/sieve-vacation-on-subject-placeholder.sieve
  tests/data/sieve-vacation-on.sieve
Labels: bug, 3. to review

#10007 fix:flagged icons position
  src/components/Envelope.vue
Labels: bug, 3. to review

#10009 Composer, RecipientListItem: make long recipients clip and subject unconstrained
  src/components/Composer.vue
  src/components/RecipientListItem.vue
Labels: 3. to review

#10012 chore: fix npm version number
  package-lock.json
Labels: 3. to review, dependencies

#10010 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10011 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10023 fix: use correct type for button, type for prop
  src/components/PhishingWarning.vue
Labels: bug, 4. to release

#9992 fix: send imip when importing an event in mail
  src/components/Imip.vue
Labels: bug, 3. to review

#10032 chore(deps): Update openapi-extractor to v1.0.0
  vendor-bin/openapi/composer.json
  vendor-bin/openapi/composer.lock
Labels: 3. to review, dependencies

#10022 fix: polish list item
  src/components/Envelope.vue
  src/components/EnvelopeSkeleton.vue
Labels: bug, 3. to review, design

#10013 chore(deps): Drop eslint-plugin-node
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#10044 EnvelopeSkeleton: make oneline envelopes actually one line and not two
  src/components/Envelope.vue
  src/components/EnvelopeSkeleton.vue
Labels: 3. to review

#10041 fix: smart reply button jump
  src/components/Message.vue
Labels: 3. to review

#10055 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10054 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10058 fix: hide show links button when not needed
  src/components/PhishingWarning.vue
Labels: bug, 3. to review

#10059 Alter Outbox logic to handle automated messages better
  lib/Controller/OutboxController.php
  src/components/OutboxMessageListItem.vue
Labels: 3. to review
