Repository nextcloud/mail, pull requests merged in 2024-11, with the labels that each got.

#10318 fix(quick-search): RTL support
  src/components/SearchMessages.vue
Labels: bug, 3. to review

#10321 fix(contactsintegration): Limit number of search results
  lib/Service/ContactsIntegration.php
Labels: bug, 3. to review, backport-request

#10324 chore: enable transifex for stable4.1
  .tx/backport
Labels: backport-request

#10330 chore(psalm): add explicit type annotation for widget items
  lib/Dashboard/MailWidget.php
Labels: 3. to review, technical debt

#10116 feat: add iMip Request Handling
  lib/Dashboard/MailWidget.php
  lib/Service/IMipService.php
  tests/Unit/Service/IMipServiceTest.php
Labels: bug, 4. to release

#10337 fix: CKEditor translations
  src/components/TextEditor.vue
Labels: bug, 3. to review, backport-request, regression

#10341 Revert "fix: CKEditor translations"
  src/components/TextEditor.vue
Labels: 3. to review

#10272 fix: loading icon position
  src/components/Mailbox.vue
Labels: 3. to review, feedback-requested

#10343 fix: accept avatars with image/vnd.microsoft.icon mime types
  lib/Service/AvatarService.php
Labels: bug, 4. to release, backport-request

#10349 chore: remove some obsolete server version checks
  lib/AppInfo/Application.php
  src/components/MailboxThread.vue
  src/components/ThreadEnvelope.vue
Labels: 3. to review, technical debt

#10346 [stable4.1] Bump bytestream/horde-stream from to ^1.7.2 and bytestream/horde-imap-client to ^2.33.3
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#10347 [stable3.7] Bump bytestream/horde-stream from to ^1.7.2 and bytestream/horde-imap-client to ^2.33.3
  composer.json
  composer.lock
Labels: 4. to release, dependencies

#10352 fix(ThreadTitle) Rtl support
  src/components/Thread.vue
Labels: 4. to release, design

#10328 fix: Junk/NotJunk flags
  lib/Service/MailManager.php
  tests/Unit/Service/MailManagerTest.php
Labels: bug, 3. to review, backport-request

#10363 fix(avatar): Use Nextcloud HTTP client for favicons
  lib/AppInfo/Application.php
  lib/Service/Avatar/FaviconDataAccess.php
  tests/Unit/Service/Avatar/FaviconDataAccessTest.php
Labels: bug, 4. to release, backport-request

#10370 [stable3. 7] Fix conventional release paths
  .github/workflows/appstore-conventional-build-publish.yml
Labels: 2. developing

#10267 fix: Reply all inside message thread
  src/components/MenuEnvelope.vue
Labels: bug, 3. to review

#10368 refactor: Use array_merge to combine string-keyed array
  lib/Service/Avatar/FaviconDataAccess.php
Labels: 3. to review, technical debt

#10376 [stable4.1] ci: Prevent feat commits
  .github/workflows/block-unconventional-commits.yml
Labels: 3. to review

#10377 [stable4.0] ci: Prevent feat commits
  .github/workflows/conventional_commits.yml
Labels: 3. to review

#10379 fix(release): Ignore unnecessary files
  .nextcloudignore
Labels: 3. to review, backport-request

#10385 [stable3.7] ci(psalm-matrix): don't run on stable30
  .github/workflows/psalm-matrix.yml
Labels: 3. to review, technical debt

#10378 [stable3.7] ci: Prevent feat commits
  .github/workflows/conventional_commits.yml
Labels: 3. to review

#10391 fix(release): Specify release committer
  .github/workflows/appstore-conventional-build-publish.yml
Labels: 3. to review, backport-request

#10403 fix: disable async vue components
  package.json
  src/components/NavigationAccount.vue
  src/router.js
  src/views/Home.vue
Labels: backport-request

#10418 fix: new message button misalignment
  src/components/NoMessageSelected.vue
Labels: bug, 3. to review, backport-request

#10410 fix(ui): Restore message/thread styling
  src/components/RecipientBubble.vue
  src/components/Thread.vue
Labels: bug, 3. to review, backport-request, regression
