Repository nextcloud/mail, pull requests merged in 2024-05, with the labels that each got.

#9626 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9615 Fix:Search mailbox by address
  src/components/SearchMessages.vue
Labels: bug, 3. to review, regression

#9632 Fix: Save attachement to files
  src/components/MessageAttachment.vue
Labels: 3. to review, backport-request

#9641 fix: Check if mailbox folder is selectable
  lib/IMAP/MailboxSync.php
Labels: bug, 3. to review

#9639 fix: create tasks from emails
  src/components/TaskModal.vue
Labels: bug, 3. to review, feature:integration, backport-request

#9646 chore: remove legacy Account::newMessage() method
  lib/Account.php
  lib/Service/AntiSpamService.php
  lib/Service/MailTransmission.php
  tests/Unit/Service/MailTransmissionTest.php
Labels: 3. to review, technical debt

#9650 build: release v3.6.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#9657 fix(.nextcloudignore): Exclude php-stemmer tests from package
  .nextcloudignore
Labels: enhancement, 3. to review

#9658 chore(tests): Clean-up phpunit.unit.xml
  tests/phpunit.unit.xml
Labels: 3. to review, technical debt

#9661 fix(composer): Revive ckeditor translations
  package-lock.json
  package.json
  src/components/TextEditor.vue
Labels: bug, 3. to review, feature:composer

#9491 Fix: misplaced border ncselect
  src/components/Composer.vue
Labels: bug, 3. to review, design, backport-request, regression, feature:composer

#9642 fix: selecting drafts via shortcut shouldnt open the composer
  src/components/Envelope.vue
Labels: bug, 3. to review, backport-request

#9640 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9677 Use whole certificate chain for S/MIME signing/verification - take 2
  lib/Service/SmimeService.php
  src/tests/data/user@imap.localhost.chain.crt
  src/tests/unit/util/pkcs12.spec.js
  src/util/pkcs12.js
  tests/Unit/Service/SmimeServiceTest.php
  tests/data/smime-certs/chain-leaf-only@imap.localhost.crt
  tests/data/smime-certs/chain-partial@imap.localhost.crt
  tests/data/smime-certs/chain@imap.localhost.crt
Labels: bug, 3. to review, backport-request, feature:smime

#9687 fix: inconsistent encoding in saved sent messages
  lib/Service/MailTransmission.php
  tests/Unit/Service/MailTransmissionTest.php
Labels: bug, 3. to review, backport-request, regression
