Repository nextcloud/mail, pull requests merged in 2024-01, with the labels that each got.

#9186 Show password on password field
  src/components/AccountForm.vue
Labels: enhancement, 3. to review

#9210 Fix : sql order by
  lib/Db/MessageMapper.php
  tests/Integration/Db/MessageMapperTest.php
Labels: 3. to review, backport-request, regression

#9211 chore(vue3): migrate event buses to mitt
  package-lock.json
  package.json
  src/components/Composer.vue
  src/components/ComposerAttachment.vue
  src/components/ComposerAttachments.vue
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  src/components/MailboxThread.vue
  src/components/NavigationMailbox.vue
  src/components/OutOfOfficeForm.vue
  src/components/SignatureSettings.vue
  src/components/TextEditor.vue
  src/directives/drag-and-drop/draggable-envelope/draggable-envelope.js
  src/directives/drag-and-drop/droppable-mailbox/droppable-mailbox.js
  src/directives/drag-and-drop/util/dragEventBus.js
  src/directives/infinite-scroll.js
  src/tests/unit/components/TextEditor.spec.js
Labels: 3. to review, technical debt

#9216 fix(setup): Fix rate limit annotation syntax
  lib/Controller/AutoConfigController.php
Labels: bug, 3. to review, backport-request

#9220 fix: cache accounts by userId in AccountService
  lib/Service/AccountService.php
  tests/Unit/Service/AccountServiceTest.php
Labels: bug, 3. to review, backport-request

#9228 fix(autoresponder): use subject placeholder instead of ooo short message
  lib/Controller/OutOfOfficeController.php
  lib/Listener/OutOfOfficeListener.php
  tests/Unit/Controller/OutOfOfficeControllerTest.php
Labels: bug, 4. to release, feature:integration, backport-request

#9163 Add an option to maximize composer modal
  src/components/NewMessageModal.vue
Labels: enhancement, 4. to release

#9233 [stable3.5] fix(autoresponder): use subject placeholder instead of ooo short message
  lib/Controller/OutOfOfficeController.php
  lib/Listener/OutOfOfficeListener.php
  tests/Unit/Controller/OutOfOfficeControllerTest.php
Labels: bug, 3. to review, feature:integration

#9234 fix: add command to repair broken autoresponders
  appinfo/info.xml
  lib/Command/UpdateSystemAutoresponders.php
  lib/Controller/OutOfOfficeController.php
  lib/Db/MailAccountMapper.php
  lib/Service/OutOfOfficeService.php
  tests/Unit/Controller/OutOfOfficeControllerTest.php
  tests/Unit/Service/OutOfOfficeServiceTest.php
Labels: 3. to review, backport-request

#8863 Smart replies for mail
  appinfo/routes.php
  lib/Controller/MessagesController.php
  lib/Controller/PageController.php
  lib/Controller/SettingsController.php
  lib/Service/AiIntegrations/AiIntegrationsService.php
  lib/Service/AiIntegrations/Cache.php
  lib/Settings/AdminSettings.php
  psalm.xml
  src/components/Composer.vue
  src/components/Message.vue
  src/components/NewMessageModal.vue
  src/components/ThreadEnvelope.vue
  src/components/settings/AdminSettings.vue
  src/service/AiIntergrationsService.js
  src/service/SettingsService.js
  src/store/actions.js
  src/store/mutations.js
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Service/AiIntegrationsServiceTest.php
  tests/Unit/Settings/AdminSettingsTest.php
Labels: 3. to review

#9239 [stable3.5] fix: add command to repair broken autoresponders
  appinfo/info.xml
  lib/Command/UpdateSystemAutoresponders.php
  lib/Controller/OutOfOfficeController.php
  lib/Db/MailAccountMapper.php
  lib/Service/OutOfOfficeService.php
  tests/Unit/Controller/OutOfOfficeControllerTest.php
  tests/Unit/Service/OutOfOfficeServiceTest.php
Labels: 3. to review

#9206 perf(db): Add message_id index for mail_messages table
  lib/AppInfo/Application.php
  lib/Listener/OptionalIndicesListener.php
  lib/Migration/Version1130Date20220412111833.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: 4. to release, backport-request, performance 🚀

#9244 [stable3.5] perf(db): Add message_id index for mail_messages table
  lib/AppInfo/Application.php
  lib/Listener/OptionalIndicesListener.php
  lib/Migration/Version1130Date20220412111833.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: bug, 3. to review, performance 🚀

#9254 fix(db): add version check for index with length
  lib/Listener/OptionalIndicesListener.php
Labels: bug, 3. to review, backport-request

#9250 Close the action menu after clicking an action
  src/components/Composer.vue
Labels: bug, 3. to review, backport-request

#9260 fix(deps): Switch KItinerary vendor
  composer.json
  composer.lock
  lib/Integration/KItinerary/ItineraryExtractor.php
  lib/Service/ItineraryService.php
  tests/Integration/KItinerary/ItineraryExtractorTest.php
  tests/Unit/Service/ItineraryServiceTest.php
Labels: 4. to release, dependencies

#9246 Update npm and node engines versions
  package.json
Labels: dependencies

#9144 Update to nextcloud/vue 8
  package-lock.json
  package.json
  src/components/AccountSettings.vue
  src/components/AliasForm.vue
  src/components/AliasSettings.vue
  src/components/AppSettingsMenu.vue
  src/components/Avatar.vue
  src/components/CertificateSettings.vue
  src/components/Composer.vue
  src/components/ComposerSessionIndicator.vue
  src/components/Dashboard.vue
  src/components/EmptyMailbox.vue
  src/components/EmptyMailboxSection.vue
  src/components/Envelope.vue
  src/components/Error.vue
  src/components/EventModal.vue
  src/components/Imip.vue
  src/components/Loading.vue
  src/components/Mailbox.vue
  src/components/MessageHTMLBody.vue
  src/components/NavigationAccount.vue
  src/components/NavigationAccountExpandCollapse.vue
  src/components/NavigationMailbox.vue
  src/components/NavigationOutbox.vue
  src/components/NewMessageModal.vue
  src/components/NoMessageSelected.vue
  src/components/OutOfOfficeForm.vue
  src/components/OutboxMessageContent.vue
  src/components/OutboxMessageListItem.vue
  src/components/RecipientBubble.vue
  src/components/RecipientListItem.vue
  src/components/SearchMessages.vue
  src/components/SignatureSettings.vue
  src/components/TaskModal.vue
  src/components/TextEditor.vue
  src/components/ThreadEnvelope.vue
  src/components/smime/SmimeCertificateModal.vue
  src/views/Setup.vue
Labels: 3. to review, dependencies, skill:frontend
