Repository nextcloud/mail, pull requests merged in 2024-06, with the labels that each got.

#9698 Fix: replace deprecated filepicker
  src/components/MessageAttachments.vue
Labels: bug, 3. to review, backport-request

#9696 fix: filter change icon to be shown only when the filter changes
  src/components/SearchMessages.vue
Labels: bug, 3. to review

#9697 Fix: query share attributes for filepicker
  src/main.js
Labels: bug, 3. to review, backport-request, regression

#9592 enh: add backend check for download permission for cloud attachements
  lib/Service/Attachment/AttachmentService.php
  tests/Unit/Service/Attachment/AttachmentServiceTest.php
  tests/psalm-baseline.xml
Labels: enhancement, 4. to release, backport-request, skill:backend

#9599 feat: search on subject, to, from by default
  lib/Db/MessageMapper.php
  lib/Service/Search/FilterStringParser.php
  lib/Service/Search/SearchQuery.php
  src/components/SearchMessages.vue
Labels: enhancement, 3. to review

#9688 Migrate/Outbox store to Pinia
  package-lock.json
  package.json
  src/components/Navigation.vue
  src/components/NavigationOutbox.vue
  src/components/NewMessageModal.vue
  src/components/Outbox.vue
  src/components/OutboxMessageListItem.vue
  src/components/ThreadEnvelope.vue
  src/main.js
  src/store/actions.js
  src/store/index.js
  src/store/outbox/actions.js
  src/store/outbox/getters.js
  src/store/outbox/index.js
  src/store/outbox/mutations.js
  src/store/outbox/state.js
  src/store/outboxStore.js
Labels: 2. developing, technical debt

#9473 fix: honour MDN requests
  appinfo/info.xml
  lib/Controller/DraftsController.php
  lib/Controller/OutboxController.php
  lib/Db/LocalMessage.php
  lib/Migration/Version3700Date20240506161400.php
  lib/Service/MailTransmission.php
  tests/Unit/Controller/DraftsControllerTest.php
  tests/Unit/Controller/OutboxControllerTest.php
Labels: bug, 3. to review, backport-request, feature: outbox

#9720 fix: save horde cache backend on imap client logout
  lib/Cache/Cache.php
  lib/IMAP/HordeImapClient.php
  lib/IMAP/IMAPClientFactory.php
  tests/Integration/IMAP/IMAPClientFactoryTest.php
Labels: bug, 3. to review

#9721 chore: drop obsolete Account::getImapConnection() method
  lib/Account.php
  tests/Integration/IMAP/AbstractTest.php
  tests/Integration/IMAP/AccountTest.php
Labels: 4. to release, technical debt

#9728 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9426 Enh: Improve smart replies prompt
  lib/Controller/MessagesController.php
  lib/Service/AiIntegrations/AiIntegrationsService.php
Labels: enhancement, 3. to review

#9733 fix(outbox): handle missing raw message gracefully
  lib/Send/CopySentMessageHandler.php
  tests/Unit/Send/CopySendMessageHandlerTest.php
Labels: bug, 3. to review, backport-request

#9741 fix: account deletion modal design
  src/components/NavigationAccount.vue
Labels: bug, 3. to review, design, regression

#9748 [stable3.7] chore(deps): Bump braces from 3.0.2 to 3.0.3
  package-lock.json
Labels: 3. to review, dependencies

#9727 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9726 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9751 Feat: Authorize domain to Mailvelope with a single click
  src/components/AppSettingsMenu.vue
Labels: enhancement, 3. to review

#9758 fix: composer session indicator height
  src/components/ComposerSessionIndicator.vue
Labels: bug, 3. to review, design

#9750 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9766 fix: set unique keys for ncSelect in composer
  src/components/Composer.vue
Labels: bug, 4. to release, backport-request

#9765 fix: add repair job to deleted duplicated cached messages
  appinfo/info.xml
  lib/Db/MessageMapper.php
  lib/Migration/DeleteDuplicateUids.php
Labels: bug, 3. to review

#9761 fix(db): Delete recipients without sub query
  lib/Db/MessageMapper.php
Labels: bug, 3. to review, performance 🚀

#9762 Feat:change new message button to secondary
  src/components/NewMessageButtonHeader.vue
Labels: 3. to review

#9772 fix: align reply and attachment icon with subject
  src/components/Envelope.vue
Labels: bug, 3. to review

#9561 fix: close smtp connection after sending or on error
  lib/Service/MailTransmission.php
Labels: bug, 3. to review

#9567 feat: follow up reminders
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/BackgroundJob/FollowUpClassifierJob.php
  lib/Controller/FollowUpController.php
  lib/Controller/PageController.php
  lib/Db/ThreadMapper.php
  lib/Listener/FollowUpClassifierListener.php
  lib/Service/AiIntegrations/AiIntegrationsService.php
  lib/Service/Sync/ImapToDbSynchronizer.php
  lib/Settings/AdminSettings.php
  src/components/AppSettingsMenu.vue
  src/components/Envelope.vue
  src/components/Mailbox.vue
  src/components/MailboxThread.vue
  src/components/Message.vue
  src/components/TagItem.vue
  src/components/ThreadEnvelope.vue
  src/main.js
  src/service/FollowUpService.js
  src/store/actions.js
  src/store/constants.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  src/tests/setup.js
  src/util/tag.js
  templates/index.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Job/FollowUpClassifierJobTest.php
  tests/Unit/Listener/FollowUpClassifierListenerTest.php
  tests/Unit/Service/AiIntegrationsServiceTest.php
  tests/Unit/Service/MailManagerTest.php
Labels: enhancement, 4. to release, feature:integration

#9719 fix: change appnavigation to appnavigationcaption for the email account
  package-lock.json
  package.json
  src/components/NavigationAccount.vue
Labels: 3. to review

#9778 fix: declare all properties in unit tests
  tests/Unit/Service/AntiSpamServiceTest.php
  tests/Unit/Service/OutboxServiceTest.php
Labels: bug, 3. to review

#9610 Feat: phishing detection
  lib/Address.php
  lib/IMAP/ImapMessageFetcher.php
  lib/IMAP/ImapMessageFetcherFactory.php
  lib/IMAP/MessageMapper.php
  lib/Model/IMAPMessage.php
  lib/PhishingDetectionList.php
  lib/PhishingDetectionResult.php
  lib/Service/ContactsIntegration.php
  lib/Service/PhishingDetection/ContactCheck.php
  lib/Service/PhishingDetection/CustomEmailCheck.php
  lib/Service/PhishingDetection/DateCheck.php
  lib/Service/PhishingDetection/PhishingDetectionService.php
  lib/Service/PhishingDetection/ReplyToCheck.php
  src/components/Message.vue
  src/components/PhishingWarning.vue
  tests/Integration/Service/Phishing/PhishingDetectionServiceIntegrationTest.php
  tests/Unit/Controller/ListControllerTest.php
  tests/Unit/IMAP/MessageMapperTest.php
  tests/Unit/Model/IMAPMessageTest.php
  tests/Unit/Service/Phishing/ContactCheckTest.php
  tests/Unit/Service/Phishing/CustomEmailCheckTest.php
  tests/Unit/Service/Phishing/DateCheckTest.php
  tests/Unit/Service/Phishing/PhishingDetectionServiceTest.php
  tests/Unit/Service/Phishing/ReplyToCheckTest.php
  tests/data/phishing-mail-headers.txt
  tests/data/phishing-mail-headers.txt.license
Labels: enhancement, 3. to review
