Repository nextcloud/mail, pull requests merged in 2024-07, with the labels that each got.

#9781 fix: make sure inbound_password uses null as default
  appinfo/info.xml
  lib/Migration/Version3800Date20240628163133.php
Labels: bug, 3. to review

#8644 Update AccountForm.vue so Reconnect button works for Microsoft accounts
  src/components/AccountForm.vue
Labels: bug, 4. to release, feedback-requested

#9653 Master password: Make sure accounts without password are included
  lib/Http/Middleware/ProvisioningMiddleware.php
  lib/Service/Provisioning/Manager.php
  tests/Unit/Http/Middleware/ProvisioningMiddlewareTest.php
  tests/Unit/Service/Provisioning/ManagerTest.php
Labels: bug, 4. to release, feedback-requested

#9606 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#9787 fix: mailbox error empty content alignment
  src/components/Mailbox.vue
Labels: bug, 3. to review, design, backport-request

#9791 fix(l10n): Update mailbox button text from "Edit name" to "Rename"
  src/components/NavigationMailbox.vue
Labels: bug, 3. to review

#8951 perf: Use local caches for avatars
  lib/Service/Avatar/Cache.php
  tests/Unit/Service/Avatar/CacheTest.php
Labels: 3. to review, performance 🚀

#9792 fix(deps)!: Drop support for Nextcloud 29 and older
  .github/workflows/psalm-matrix.yml
  .github/workflows/test.yml
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#9798 Remove instance name from share link add button
  src/components/Composer.vue
Labels: 3. to review, design, feature:composer

#9797 ci: Semantic release automation
  .github/workflows/appstore-conventional-build-publish.yml
  build/pre-commit.js
Labels: 3. to review

#9800 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
  img/LICENSES.md
Labels: dependencies

#9811 Migrate REUSE to TOML
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt

#9805 feat: Separate attachments from three-dot-menu
  src/components/Composer.vue
  src/components/TextEditor.vue
Labels: enhancement, 3. to review

#9793 fix: duplicate uid repair job failing on postgres
  lib/Db/MessageMapper.php
  tests/Integration/Db/MessageMapperTest.php
Labels: bug, 3. to review, backport-request

#9802 fix: background-color of outbox-button
  src/components/Navigation.vue
Labels: bug, 3. to review

#9819 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9749 feat(ocs): notify of new messages and provide API endpoint to retrieve its contents
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/Controller/MessageApiController.php
  lib/Db/MessageMapper.php
  lib/Events/NewMessageReceivedEvent.php
  lib/IMAP/ImapMessageFetcher.php
  lib/Listener/NewMessagesNotifier.php
  lib/Model/IMAPMessage.php
  lib/Service/MailManager.php
  lib/Service/SmimeService.php
  lib/Service/TrustedSenderService.php
  tests/Unit/Controller/MessageApiControllerTest.php
Labels: enhancement, 3. to review

#9829 fix: remove the app navigation spacer
  src/components/Navigation.vue
Labels: 3. to review

#9827 feat:change the icon size to fit the new text size
  src/components/AccountForm.vue
  src/components/AliasForm.vue
  src/components/AliasSettings.vue
  src/components/AppSettingsMenu.vue
  src/components/Composer.vue
  src/components/ComposerSessionIndicator.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/Imip.vue
  src/components/Loading.vue
  src/components/MailboxPicker.vue
  src/components/MailboxThread.vue
  src/components/MenuEnvelope.vue
  src/components/Message.vue
  src/components/MessageAttachment.vue
  src/components/MessageHTMLBody.vue
  src/components/Navigation.vue
  src/components/NavigationAccount.vue
  src/components/NavigationMailbox.vue
  src/components/NavigationOutbox.vue
  src/components/NewMessageButtonHeader.vue
  src/components/NewMessageModal.vue
  src/components/OutOfOfficeForm.vue
  src/components/OutboxMessageListItem.vue
  src/components/PhishingWarning.vue
  src/components/RecipientBubble.vue
  src/components/RecipientListItem.vue
  src/components/SearchMessages.vue
  src/components/SieveFilterForm.vue
  src/components/SignatureSettings.vue
  src/components/TagModal.vue
  src/components/ThreadEnvelope.vue
  src/components/ThreadSummary.vue
  src/components/imip/EventData.vue
  src/components/itinerary/CalendarImport.vue
  src/components/settings/AdminSettings.vue
  src/components/settings/AntiSpamSettings.vue
  src/components/settings/ProvisioningSettings.vue
  src/components/smime/SmimeCertificateModal.vue
Labels: enhancement, 3. to review

#9818 fix(printing): Fix long emails getting cut for print
  src/views/Home.vue
Labels: bug, 3. to review, backport-request

#9843 fix(dashboard): Fix dashboard icon
  REUSE.toml
  img/mail-dark.svg
  lib/Dashboard/MailWidget.php
Labels: 3. to review

#9847 ci: allow coverage upload to fail
  .github/workflows/test.yml
Labels: 3. to review

#9806 fix: close the ncselect dropdown when clicked somewhere else
  src/components/Composer.vue
Labels: bug, 3. to review, regression

#9848 fix: remove the global styling from the composer list
  src/components/TextEditor.vue
Labels: bug, 3. to review

#9852 QoL improvements to email printing
  src/components/MenuEnvelope.vue
  src/components/Thread.vue
Labels: 3. to review

#9861 fix: Align version number in package-lock.json
  package-lock.json
Labels: 3. to review, dependencies

#9864 fix: move delete duplicate uids repair step to a job
  lib/BackgroundJob/DeleteDuplicatedUidsJob.php
  lib/Migration/DeleteDuplicateUids.php
Labels: bug, 3. to review, backport-request

#9845 chore: update to min PHP8.1
  .github/workflows/lint-php.yml
  appinfo/info.xml
  composer.json
  composer.lock
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/mozart/composer.json
  vendor-bin/mozart/composer.lock
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
Labels: 3. to review

#9875 style(mail navigation): remove unnecessary spacing
  src/components/Navigation.vue
  src/components/NewMessageButtonHeader.vue
Labels: 3. to review

#9876 fix(composer): Remove to/cc/bcc/subject separators
  src/components/Composer.vue
Labels: bug, 3. to review, design, feature:composer

#9672 feat(ocs): send a message via api
  lib/Controller/MessageApiController.php
  lib/Send/Chain.php
  lib/Service/AliasesService.php
  lib/Service/MailTransmission.php
  lib/Service/OutboxService.php
  tests/Unit/Controller/MessageApiControllerTest.php
  tests/Unit/Send/ChainTest.php
Labels: enhancement, 4. to release, feature:integration

#9887 fix: lost focus in reference picker
  src/components/Composer.vue
  src/components/NewMessageModal.vue
Labels: bug, 3. to review, backport-request

#9889 fix: set link icon size explicitly
  src/components/TextEditor.vue
Labels: bug, 3. to review, design, backport-request, regression

#9865 fix: migrate advanced search to nc dialog
  package-lock.json
  package.json
  src/components/SearchMessages.vue
Labels: 3. to review, skill:frontend

#9863 refactor: migrate setup page to nextcloud-vue components
  src/components/AccountForm.vue
Labels: enhancement, 2. developing

#9898 SieveAccountForm: improve styling and implement Nextcloud vue components
  src/components/SieveAccountForm.vue
Labels: 3. to review

#9901 feat: improve the search bar icons
  src/components/SearchMessages.vue
Labels: 4. to release

#9904 Release v4.0.0-alpha1
  CHANGELOG.md
Labels: 4. to release

#9905 ci: update app store build and publish workflow
  .github/workflows/appstore-build-publish.yml
Labels: 3. to review

#9903 fix: thread padding
  src/components/Thread.vue
Labels: 3. to review

#9911 fix: ellips the subject and position of the important icon
  src/components/Envelope.vue
Labels: 3. to review

#9879 Settings: reduce amount of sections
  src/components/AppSettingsMenu.vue
Labels: 3. to review

#9846 chore: drop unused code from accounts object
  lib/Account.php
Labels: 3. to review, technical debt

#9912 fix: button text colour on dark theme
  src/components/MessageHTMLBody.vue
Labels: 3. to review

#9924 Navigation: make new message button not scroll
  src/components/Navigation.vue
Labels: 3. to review

#9922 AccountForm: improve spacing and remove button borders
  src/components/AccountForm.vue
Labels: 3. to review

#9926 fix(outbox): Revive item subname
  src/components/OutboxMessageListItem.vue
Labels: bug, 3. to review

#9939 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9897 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9943 fix: Fine-tune thread summary box design
  src/components/ThreadSummary.vue
Labels: bug, 3. to review, design

#9938 fix: Separate quick search and threads list with a line
  src/components/MailboxThread.vue
  src/components/SearchMessages.vue
Labels: bug, 3. to review

#9921 fix: Show message reply (all) action in toolbar
  src/components/MenuEnvelope.vue
  src/components/ThreadEnvelope.vue
Labels: bug, 3. to review

#9914 feat:fine-tune CKEditor toolback to look and feel like Nextcloud
  src/components/TextEditor.vue
Labels: 3. to review
