Repository nextcloud/mail, pull requests merged in 2024-04, with the labels that each got.

#9519 ci: Test against stable29 not master
  .github/workflows/psalm-matrix.yml
  .github/workflows/test.yml
Labels: 3. to review

#9522 fix(deps): Replace @nextcloud/vue-dashboard with @nextcloud/vue
  package-lock.json
  package.json
  src/components/Dashboard.vue
Labels: 3. to review, technical debt

#9504 Reset additional background styles from toolbar in CKEditor
  src/components/TextEditor.vue
Labels: 3. to review

#9521 ci: Ignore vue-loader 16/17
  renovate.json
Labels: 3. to review, dependencies

#9524 ci: npm-audit the stable3.6 branch
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#9528 Revert "chore(deps): bump marcelklehr/pr-feedback-action digest to 1883b38 (main)"
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#9527 ci: Silence PR feedback acount about Nextcloud GmbH employees
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#9538 ci: Do not test server master with PHP8.0
  .github/workflows/test.yml
Labels: 3. to review

#9525 fix(composer): Prevent leaving the tab with unsaved changes
  src/components/NewMessageModal.vue
Labels: bug, 3. to review, feature parity

#9364 fix(outbox): catch failed SENT copy operation
  lib/AppInfo/Application.php
  lib/BackgroundJob/QuotaJob.php
  lib/Contracts/IMailTransmission.php
  lib/Controller/DraftsController.php
  lib/Controller/OutboxController.php
  lib/Db/LocalMessage.php
  lib/Db/LocalMessageMapper.php
  lib/Events/BeforeMessageSentEvent.php
  lib/Events/DraftSavedEvent.php
  lib/Events/MessageSentEvent.php
  lib/IMAP/MessageMapper.php
  lib/Listener/AddressCollectionListener.php
  lib/Listener/AntiAbuseListener.php
  lib/Listener/FlagRepliedMessageListener.php
  lib/Listener/InteractionListener.php
  lib/Listener/SaveSentMessageListener.php
  lib/Migration/Version3600Date20240220134813.php
  lib/Send/AHandler.php
  lib/Send/AntiAbuseHandler.php
  lib/Send/Chain.php
  lib/Send/CopySentMessageHandler.php
  lib/Send/FlagRepliedMessageHandler.php
  lib/Send/SendHandler.php
  lib/Send/SentMailboxHandler.php
  lib/Service/AntiAbuseService.php
  lib/Service/AntiSpamService.php
  lib/Service/DraftsService.php
  lib/Service/MailTransmission.php
  lib/Service/OutboxService.php
  lib/Service/TransmissionService.php
  src/components/NewMessageModal.vue
  src/components/OutboxMessageListItem.vue
  src/store/constants.js
  src/store/outbox/actions.js
  src/store/outbox/mutations.js
  tests/Integration/Db/LocalAttachmentMapperTest.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Integration/Service/OutboxServiceIntegrationTest.php
  tests/Unit/Controller/OutboxControllerTest.php
  tests/Unit/Listener/AddressCollectionListenerTest.php
  tests/Unit/Listener/FlagRepliedMessageListenerTest.php
  tests/Unit/Listener/InteractionListenerTest.php
  tests/Unit/Listener/SaveSentMessageListenerTest.php
  tests/Unit/Send/AntiAbuseHandlerTest.php
  tests/Unit/Send/ChainTest.php
  tests/Unit/Send/CopySendMessageHandlerTest.php
  tests/Unit/Send/FlagRepliedMessageHandlerTest.php
  tests/Unit/Send/SendHandlerTest.php
  tests/Unit/Send/SentMailboxHandlerTest.php
  tests/Unit/Service/AntiAbuseServiceTest.php
  tests/Unit/Service/AntiSpamServiceTest.php
  tests/Unit/Service/MailTransmissionTest.php
  tests/Unit/Service/OutboxServiceTest.php
  tests/Unit/Service/TransmissionServiceTest.php
Labels: bug, 3. to review, backport-request

#9526 fix: PHP deprecations
  lib/Controller/AccountsController.php
  lib/Controller/MailboxesController.php
  lib/Model/NewMessageData.php
  lib/Service/Sync/SyncService.php
  tests/Integration/IMAP/MessageMapperTest.php
  tests/Integration/MailboxSynchronizationTest.php
  tests/Integration/Migration/MigrateImportantFromImapAndDbTest.php
  tests/Integration/Service/AntiSpamServiceIntegrationTest.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Integration/Service/OutboxServiceIntegrationTest.php
  tests/Unit/Model/NewMessageDataTest.php
  tests/Unit/Service/AntiSpamServiceTest.php
  tests/Unit/Service/MailTransmissionTest.php
  tests/Unit/Service/Sync/SyncServiceTest.php
Labels: 4. to release

#9492 Fix imap smtp button on firefox
  src/components/AccountForm.vue
Labels: bug, 3. to review, backport-request

#9552 Revert "fix: Check if mailbox folder is selectable"
  lib/IMAP/MailboxSync.php
Labels: 3. to review

#9553 fix: Sanitize forward slashes from name before generating url
  lib/Dashboard/MailWidget.php
Labels: 3. to review, backport-request

#9569 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9536 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9570 Fix: Display from, to, cc, bcc correctly on advance search
  src/components/SearchMessages.vue
Labels: bug, 3. to review

#9577 Fix: inaccessible filepicker
  src/components/ComposerAttachments.vue
Labels: bug, 3. to review, backport-request, regression

#9575 fix(pi): section title margins affected by global styles
  src/components/MailboxThread.vue
Labels: bug, 4. to release, design, regression, feature:priority inbox

#9581 fix(threading): Run manual garbage collection
  lib/Listener/AccountSynchronizedThreadUpdaterListener.php
Labels: bug, 3. to review, feature:threading

#9568 chore: merge duplicated tagging code
  lib/Service/MailManager.php
  tests/Unit/Service/MailManagerTest.php
Labels: 3. to review, technical debt

#9582 fix: remove unused package
  package-lock.json
  package.json
Labels: 3. to review, backport-request, dependencies

#9576 Add static icon for unknown user
  src/components/Composer.vue
Labels: bug, 4. to release, design

#9587 Fix: downgrade webdav to fix Filepicker
  package-lock.json
  package.json
  src/components/ComposerAttachments.vue
Labels: bug, 3. to review, backport-request, regression

#9593 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9594 test(integration): disable Jan's Gravatar test
  tests/Integration/Service/AvatarServiceIntegrationTest.php
Labels: 4. to release

#9509 Filter messages sent in the last 7 days and from me
  src/components/SearchMessages.vue
Labels: enhancement, 3. to review

#9609 feat: implement admin setting to disable classification by default
  appinfo/routes.php
  lib/BackgroundJob/TrainImportanceClassifierJob.php
  lib/Command/TrainAccount.php
  lib/Controller/PageController.php
  lib/Controller/SettingsController.php
  lib/Listener/NewMessageClassificationListener.php
  lib/Service/Classification/ClassificationSettingsService.php
  lib/Settings/AdminSettings.php
  src/components/settings/AdminSettings.vue
  src/service/SettingsService.js
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Service/Classification/ClassificationSettingsServiceTest.php
  tests/Unit/Settings/AdminSettingsTest.php
Labels: enhancement, 3. to review

#9584 fix(outbox): handle indeterminate smtp errors
  appinfo/info.xml
  lib/Db/LocalMessage.php
  lib/Migration/Version3700Date20240430115406.php
  lib/Send/Chain.php
  lib/Send/CopySentMessageHandler.php
  lib/Service/MailTransmission.php
  src/components/OutboxMessageListItem.vue
  src/store/constants.js
  tests/Unit/Send/ChainTest.php
Labels: bug, 3. to review, feature: outbox
