Repository nextcloud/mail, pull requests merged in 2024-10, with the labels that each got.

#10207 ci: Update renovate's base branches
  renovate.json
Labels: 3. to review

#10208 ci: Add PHP8.4 to the testing matrix
  .github/workflows/test.yml
Labels: 3. to review

#9757 perf: bundle with vite
  .eslintrc.cjs
  .gitignore
  babel.config.cjs
  babel.config.js
  jest.config.cjs
  krankerl.toml
  lib/Controller/MessagesController.php
  lib/Http/HtmlResponse.php
  package-lock.json
  package.json
  patches/vue-tabs-component+1.5.0.patch
  src/autoredirect.js
  src/components/Envelope.vue
  src/components/NewMessageModal.vue
  src/components/ThreadEnvelope.vue
  src/css/html-response.css
  src/css/mail.scss
  src/css/mobile.scss
  src/css/redirect.css
  src/html-response.js
  src/main-oauth-popup.js
  src/main-settings.js
  src/main.js
  src/views/Home.vue
  templates/index.php
  templates/oauth_done.php
  templates/redirect.php
  templates/settings-admin.php
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Http/HtmlResponseTest.php
  vite.config.js
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
  webpack.test.js
Labels: enhancement, 3. to review, performance 🚀

#10038 feat: implement periodic full sync job to repair cache inconsistencies
  appinfo/routes.php
  lib/BackgroundJob/RepairSyncJob.php
  lib/Controller/MailboxesController.php
  lib/IMAP/IMAPClientFactory.php
  lib/Migration/FixBackgroundJobs.php
  lib/Service/Sync/ImapToDbSynchronizer.php
  lib/Service/Sync/SyncService.php
  src/components/NavigationMailbox.vue
  src/service/MailboxService.js
  tests/Integration/Sync/ImapToDbSynchronizerTest.php
Labels: bug, 4. to release, backport-request

#10209 chore: update readme
  README.md
Labels: 3. to review

#10218 chore: update badges on readme (again)
  README.md
Labels: 3. to review

#10220 fix(psrlog): Make the logger compatible with the upcoming bump to psr…
  lib/Support/ConsoleLoggerDecorator.php
Labels: bug, 3. to review

#10122 feat: add mention to mail
  lib/Controller/ContactIntegrationController.php
  lib/Service/ContactIntegration/ContactIntegrationService.php
  src/ckeditor/smartpicker/InsertItemCommand.js
  src/components/Composer.vue
  src/components/TextEditor.vue
  src/service/ContactIntegrationService.js
Labels: enhancement, 2. developing

#10237 chore: bump psr/log to 3.0.2
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#10234 chore: accounts controller patch response
  lib/Controller/AccountsController.php
Labels: 3. to review, technical debt

#10244 refactor: drop fallback for availability coordinator
  lib/Service/OutOfOfficeService.php
  tests/Unit/Service/OutOfOfficeServiceTest.php
Labels: 3. to review, technical debt

#10246 hello coding-standard 1.3.1
  .git-blame-ignore-revs
  lib/Account.php
  lib/BackgroundJob/MigrateImportantJob.php
  lib/BackgroundJob/QuotaJob.php
  lib/BackgroundJob/SyncJob.php
  lib/BackgroundJob/TrainImportanceClassifierJob.php
  lib/Command/ExportAccount.php
  lib/Controller/AccountsController.php
  lib/Controller/ContactIntegrationController.php
  lib/Controller/InternalAddressController.php
  lib/Controller/MessageApiController.php
  lib/Controller/OutboxController.php
  lib/Controller/SieveController.php
  lib/Db/MessageMapper.php
  lib/Db/MessageSnoozeMapper.php
  lib/Events/MessageSentEvent.php
  lib/Events/NewMessageReceivedEvent.php
  lib/IMAP/FolderMapper.php
  lib/IMAP/ImapMessageFetcher.php
  lib/Listener/AddressCollectionListener.php
  lib/Listener/NewMessageClassificationListener.php
  lib/Listener/NewMessagesNotifier.php
  lib/Migration/MigrateImportantFromImapAndDb.php
  lib/Migration/Version1140Date20221113205737.php
  lib/Migration/Version1140Date20221206162029.php
  lib/Migration/Version3500Date20231115182612.php
  lib/Migration/Version3600Date20240227172825.php
  lib/Migration/Version3700Date20240430115406.php
  lib/Migration/Version3800Date20240628163133.php
  lib/Model/EventData.php
  lib/Model/IMAPMessage.php
  lib/Provider/Command/MessageSend.php
  lib/Provider/MailProvider.php
  lib/Send/AHandler.php
  lib/Send/AntiAbuseHandler.php
  lib/Send/Chain.php
  lib/Send/CopySentMessageHandler.php
  lib/Send/FlagRepliedMessageHandler.php
  lib/Send/SendHandler.php
  lib/Service/AiIntegrations/AiIntegrationsService.php
  lib/Service/AntiSpamService.php
  lib/Service/Attachment/AttachmentService.php
  lib/Service/DkimService.php
  lib/Service/IMipService.php
  lib/Service/MailTransmission.php
  lib/Service/OutboxService.php
  lib/Service/PhishingDetection/ContactCheck.php
  lib/Service/PhishingDetection/CustomEmailCheck.php
  lib/Service/PhishingDetection/LinkCheck.php
  lib/Service/PhishingDetection/PhishingDetectionService.php
  lib/Service/PreprocessingService.php
  lib/Service/SnoozeService.php
  lib/Service/TransmissionService.php
  tests/Unit/Service/AiIntegrationsServiceTest.php
  tests/bootstrap.php
  vendor-bin/cs-fixer/composer.lock
Labels: 3. to review, dependencies

#10084 fix: thread disappearing after refresh
  src/components/MailboxThread.vue
Labels: bug, 3. to review

#10252 fix(iframe): scroll horizontally in case of overflow
  src/components/MessageHTMLBody.vue
  src/css/html-response.css
Labels: bug, 3. to review, feature: HTML mails

#10255 fix: input icons and native datepicker
  src/components/SearchMessages.vue
Labels: bug, 3. to review, skill:frontend

#10259 fix(rtl): phishing warning component
  src/components/PhishingWarning.vue
Labels: bug, 3. to review, skill:frontend

#10260 fix: app version
  appinfo/info.xml
Labels: 3. to review

#10249 [stable4.0] build: run tests against stable30
  .github/workflows/psalm-matrix.yml
  .github/workflows/test.yml
  composer.json
  composer.lock
Labels: 3. to review, technical debt

#10195 Fix PGP/MIME sending and viewing
  appinfo/info.xml
  lib/Controller/DraftsController.php
  lib/Controller/OutboxController.php
  lib/Db/LocalMessage.php
  lib/IMAP/ImapMessageFetcher.php
  lib/Migration/Version4100Date20240916174827.php
  lib/Model/IMAPMessage.php
  lib/Service/MailTransmission.php
  lib/Service/MimeMessage.php
  src/components/Composer.vue
  src/components/Message.vue
  tests/Unit/Controller/DraftsControllerTest.php
  tests/Unit/Controller/ListControllerTest.php
  tests/Unit/Controller/OutboxControllerTest.php
  tests/Unit/Model/IMAPMessageTest.php
Labels: bug, 4. to release, feedback-requested

#10282 chore: replace int db types with integer
  lib/Db/Alias.php
  lib/Db/Classifier.php
  lib/Db/MailAccount.php
Labels: 3. to review, technical debt

#10281 chore(composer): raise minimum required php version to 8.1
  composer.json
Labels: 4. to release, technical debt

#10293 chore: bring back needs info workflow
  .github/no-response.yml
  .github/stale.yml
  .github/workflows/stale.yml
Labels: 3. to review

#10299 fix(PhishingDetection): empty href
  lib/Service/PhishingDetection/LinkCheck.php
Labels: bug, 3. to review, backport-request

#10302 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10176 fix(threading): Handle threads with duplicate send times
  lib/Db/MessageMapper.php
Labels: bug, 3. to review, feature:threading, papercut

#10158 fix: open search buttons on focus and fix the wraping
  src/components/SearchMessages.vue
Labels: bug, 3. to review
