Repository nextcloud/mail, pull requests merged in 2024-03, with the labels that each got.

#9430 chore(release): v3.6.0-beta1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#9422 fix(db): Avoid dirty read for collected addresses
  lib/Db/CollectedAddressMapper.php
  lib/Service/AutoCompletion/AddressCollector.php
  tests/Integration/Db/CollectedAddressMapperTest.php
  tests/Unit/Service/Autocompletion/AddressCollectorTest.php
Labels: bug, 3. to review

#9431 fix(integration): Allow LLM event titles/agendas for non-admins
  lib/Controller/ThreadController.php
Labels: bug, 3. to review

#9423 fix(db): Avoid dirty reads while deleting messages by uid
  lib/Db/MessageMapper.php
  tests/Integration/Db/MessageMapperTest.php
Labels: bug, 3. to review, performance 🚀

#9434 Fix: Thread summaries fail for threads across multiple mailboxes
  lib/Controller/ThreadController.php
  lib/Service/AiIntegrations/AiIntegrationsService.php
  tests/Unit/Service/AiIntegrationsServiceTest.php
Labels: bug, 3. to review

#9415 chore(deps): Drop vue-slide-up-down
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#9438 ci: Enforce conventional commits for backports
  .github/workflows/conventional_commits.yml
Labels: 3. to review, backport-request

#9443 fix(navigation): Only make mailboxes with children collapsible
  src/components/NavigationMailbox.vue
Labels: bug, 4. to release, regression

#9441 feat(composer): Use editor toolbar instead of balloon
  package-lock.json
  package.json
  src/components/Composer.vue
  src/components/TextEditor.vue
Labels: enhancement, 3. to review, feature:composer

#9455 chore(vue3): migrate ::v-deep to :deep
  src/components/AppSettingsMenu.vue
  src/components/NoMessageSelected.vue
Labels: 3. to review, technical debt

#9458 fix(imap): Pass flags as array for the STORE command
  lib/IMAP/MessageMapper.php
Labels: bug, 3. to review

#9285 Add the possibility to change mail list view into full width
  lib/Controller/PageController.php
  src/components/AppSettingsMenu.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
  src/components/MailboxThread.vue
  src/main.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  src/tests/unit/components/Envelope.vue.spec.js
  src/views/Home.vue
  templates/index.php
  tests/Unit/Controller/PageControllerTest.php
Labels: enhancement, 4. to release

#9439 Enh: Improve smart reply UI
  src/components/Message.vue
  src/components/ThreadEnvelope.vue
Labels: enhancement, 3. to review

#9472 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#9462 Add horizontal split for mailing list
  src/components/AppSettingsMenu.vue
Labels: enhancement, 3. to review

#9469 Fix: slash command and emoji picker styling
  src/components/TextEditor.vue
Labels: bug, 3. to review

#9474 feat(utility): make json methods work the same for `$data`
  lib/Http/JsonResponse.php
Labels: 4. to release

#9488 Add ckeditor5 editor decoupled on renovate
  renovate.json
Labels: 3. to review

#9468 Split subject and preview with a dot only for one line layout
  src/components/Envelope.vue
Labels: bug, 3. to review

#9490 Fix color for preview when in active state
  src/components/Envelope.vue
Labels: bug, 4. to release

#9493 fix(jobs): Skip background jobs if no authentication is possible
  lib/BackgroundJob/PreviewEnhancementProcessingJob.php
  lib/BackgroundJob/QuotaJob.php
  lib/BackgroundJob/SyncJob.php
  lib/BackgroundJob/TrainImportanceClassifierJob.php
  lib/Db/MailAccount.php
  tests/Unit/BackgroundJob/QuotaJobTest.php
  tests/Unit/BackgroundJob/SyncJobTest.php
  tests/Unit/Job/PreviewEnhancementProcessingJobTest.php
Labels: bug, 4. to release, backport-request

#9471 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies
