Repository nextcloud/mail, pull requests merged in 2025-01, with the labels that each got.

#10541 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10542 [stable3.7] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10529 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10453 Add mail translation
  appinfo/info.xml
  lib/Controller/PageController.php
  lib/Service/AiIntegrations/AiIntegrationsService.php
  src/components/Envelope.vue
  src/components/MenuEnvelope.vue
  src/components/ThreadEnvelope.vue
  src/components/TranslationModal.vue
  src/main.js
  src/service/translationService.js
  src/store/getters.js
  src/store/index.js
  src/store/mutations.js
  src/util/text.js
  tests/Unit/Controller/PageControllerTest.php
Labels: enhancement, 3. to review

#10554 perf(ui): Load avatar URLs with low priority
  src/service/AvatarService.js
Labels: 3. to review, performance 🚀

#10562 fix: empty content position
  src/components/Mailbox.vue
Labels: 3. to review

#10564 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10567 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10569 ci: Do not update public suffix list for stable4.0
  .github/workflows/update-public-suffix-list.yml
Labels: 3. to review

#10477 fix: add ability to send alternet text (html and plain)
  appinfo/info.xml
  lib/Controller/DraftsController.php
  lib/Controller/MessageApiController.php
  lib/Controller/OutboxController.php
  lib/Db/LocalMessage.php
  lib/Migration/Version4200Date20241210000000.php
  lib/Migration/Version4200Date20241210000001.php
  lib/Provider/Command/MessageSend.php
  lib/Service/AntiSpamService.php
  lib/Service/MailTransmission.php
  lib/Service/MimeMessage.php
  package-lock.json
  package.json
  src/components/NewMessageModal.vue
  src/components/OutboxMessageListItem.vue
  src/store/mainStore/actions.js
  src/store/outboxStore.js
  tests/Integration/Db/LocalAttachmentMapperTest.php
  tests/Integration/Db/LocalMessageMapperTest.php
  tests/Integration/Db/LocalMessageTest.php
  tests/Integration/Db/RecipientMapperTest.php
  tests/Integration/Service/DraftServiceIntegrationTest.php
  tests/Integration/Service/MailTransmissionIntegrationTest.php
  tests/Integration/Service/OutboxServiceIntegrationTest.php
  tests/Unit/Controller/DraftsControllerTest.php
  tests/Unit/Controller/MessageApiControllerTest.php
  tests/Unit/Controller/OutboxControllerTest.php
  tests/Unit/Provider/Command/MessageSendTest.php
  tests/Unit/Service/DraftsServiceTest.php
  tests/Unit/Service/MailTransmissionTest.php
  tests/Unit/Service/MimeMessageTest.php
  tests/Unit/Service/OutboxServiceTest.php
Labels: 3. to review

#10573 fix(translationService) correct API reading
  src/service/translationService.js
Labels: 3. to review

#10574 feat: setup check for mail transport php-mail
  lib/AppInfo/Application.php
  lib/SetupChecks/MailTransport.php
  tests/Unit/SetupChecks/MailTransportTest.php
Labels: enhancement, 3. to review

#10571 fix: message content escaping message element
  src/views/Home.vue
Labels: bug, 3. to review

#10577 chore: Remove Psalm ignores for Nextcloud 28 APIs
  psalm.xml
Labels: 3. to review

#10584 fix(migration): make misc migrations idempotent
  lib/Migration/Version4000Date20240716172702.php
  lib/Migration/Version4100Date20241021091352.php
  lib/Migration/Version4200Date20241210000001.php
Labels: 3. to review, technical debt

#10585 fix: migrate preferences to initial state
  lib/Controller/PageController.php
  src/init.js
  templates/index.php
  tests/Unit/Controller/PageControllerTest.php
Labels: bug, 4. to release, regression

#10590 Revert "fix: message content escaping message element"
  src/views/Home.vue
Labels: 3. to review

#10592 docs: update imap and smtp timeout
  doc/admin.md
Labels: 3. to review

#10580 Fix reply button spacing #10525
  src/components/Message.vue
Labels: 3. to review

#10599 release v4.2.0-beta4
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#10611 fix(summarizeMessages): use TextToText
  lib/Service/AiIntegrations/AiIntegrationsService.php
Labels: bug, 3. to review, backport-request

#10610 fix(message-summary): respect admin config
  lib/Listener/NewMessagesSummarizeListener.php
  tests/Unit/Listener/NewMessagesSummarizeListenerTest.php
Labels: bug, 3. to review, backport-request

#10621 fix: deprecation warning
  tests/Unit/IMAP/Sync/RequestTest.php
Labels: 3. to review

#10620 fix: Adjust TaskProcessingListener
  lib/Listener/NewMessagesSummarizeListener.php
  lib/Service/AiIntegrations/AiIntegrationsService.php
  tests/Unit/Listener/NewMessagesSummarizeListenerTest.php
  tests/Unit/Service/AiIntegrationsServiceTest.php
Labels: 3. to review

#10629 fix: Adjust TaskProcessingListener Again
  lib/Listener/TaskProcessingListener.php
  lib/Service/AiIntegrations/AiIntegrationsService.php
  tests/Unit/Service/AiIntegrationsServiceTest.php
Labels: 3. to review, backport-request

#10609 fix: issues with AI integration
  src/service/AiIntergrationsService.js
Labels: bug, 3. to review, backport-request

#10614 fix: apostrophe issue
  src/components/NoMessageSelected.vue
Labels: 3. to review, backport-request
