Repository nextcloud/mail, pull requests merged in 2025-05, with the labels that each got.

#11053 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#11052 [stable5.0] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#11050 [stable3.7] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#11051 [stable4.3] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10919 Use css variables instead of magic numbers
  src/components/AccountForm.vue
  src/components/AccountSettings.vue
  src/components/AppSettingsMenu.vue
  src/components/CalendarPickerOption.vue
  src/components/Composer.vue
  src/components/ComposerSessionIndicator.vue
  src/components/MailboxPicker.vue
  src/components/NewMessageButtonHeader.vue
  src/components/Thread.vue
  src/components/ThreadEnvelope.vue
  src/components/smime/SmimeCertificateModal.vue
Labels: 3. to review

#11056 chore(github): Assign types to issues from forms
  .github/ISSUE_TEMPLATE/bug_report_form.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: 3. to review

#11043 fix: use alias name for from header
  lib/Service/MailTransmission.php
  tests/Unit/Service/MailTransmissionTest.php
Labels: bug, 3. to review, backport-request

#11081 fix(deps): update ckeditor dev utils to 44
  package-lock.json
  package.json
Labels: bug, 3. to review

#11103 chore(deps): remove eslint-plugin-standard
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#11094 fix: show warning when creating a folder fails
  src/components/NavigationAccount.vue
Labels: bug, 4. to release, backport-request

#11096 chore: remove legacy iframe-resizer
  package-lock.json
  package.json
Labels: 4. to release, dependencies

#11108 Update calendar-js and timezones
  package-lock.json
  package.json
  renovate.json
Labels: 4. to release, dependencies

#11110 [stable5.0] fix(deps): update vulnerable @nextcloud/moment and babel packages
  package-lock.json
Labels: bug, 3. to review

#11111 ci(test): do not run tests with PHP8.5
  .github/workflows/test.yml
Labels: 3. to review

#11119 fix(phishing): strip exactly 1 character from the end of a link strin…
  lib/Service/PhishingDetection/LinkCheck.php
  tests/Unit/Service/Phishing/LinkCheckTest.php
Labels: bug, 3. to review, backport-request

#11118 fix(smime): use proper binary encoding when signing messages
  REUSE.toml
  lib/Service/SmimeService.php
  tests/Unit/Service/SmimeServiceTest.php
  tests/data/html-with-signature.txt
Labels: bug, 3. to review, backport-request, feature:smime

#11123 ci: drop stable4.3 and stable3.7 from audit fixes
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#10750 perf: skip message skeleton if it is cached
  src/components/ThreadEnvelope.vue
  src/store/mainStore/actions.js
Labels: enhancement, 3. to review, performance 🚀

#11113 fix(mime): ignore HTML parsing errors consistently
  lib/Html/Parser.php
  lib/IMAP/MessageMapper.php
  lib/Service/MimeMessage.php
  lib/Service/PhishingDetection/LinkCheck.php
Labels: bug, 3. to review, backport-request

#11129 [stable5.0] fix(deps): bump bytestream/horde-imap-client from 2.33.5 to ^2.33.6
  composer.json
  composer.lock
Labels: 3. to review

#10976 feat: close modal on send
  src/components/NewMessageModal.vue
  src/store/outboxStore.js
Labels: 4. to release

#11031 fix: show submailboxes for filtering
  src/components/MailboxInlinePicker.vue
  src/components/mailFilter/Action.vue
  src/components/mailFilter/ActionFileinto.vue
  src/components/mailFilter/UpdateModal.vue
  src/store/mainStore/getters.js
Labels: bug, 3. to review, backport-request

#11141 ci(test): use low runner to run summary step
  .github/workflows/test.yml
Labels: 3. to review

#11046 test(e2e): add test for basic functionality of mail app
  .github/workflows/test.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.js
  src/tests/e2e/login.js
  src/tests/e2e/mail-e2e.spec.js
Labels: 4. to release, backport-request

#11147 fix(smime): handle encoding properly when signing and encrypting
  lib/Service/SmimeService.php
  tests/Unit/Service/SmimeServiceTest.php
  tests/data/mime-html-unicode.txt
  tests/data/mime-html-unicode.txt.license
Labels: bug, 3. to review, backport-request, feature:smime

#11154 [stable5.0] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#11153 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#11156 ci: update public suffix list only for stable5.0
  .github/workflows/update-public-suffix-list.yml
Labels: 3. to review

#11159 ci: include stable5.1
  .github/workflows/npm-audit-fix.yml
  .github/workflows/update-public-suffix-list.yml
  .tx/backport
  renovate.json
Labels: 4. to release

#11172 build: fix compatibility with node < 20.19.0 (and >= 20.0.0)
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: 3. to review, technical debt

#11175 ci: put stable5.0 into EOL
  .github/workflows/npm-audit-fix.yml
  .github/workflows/update-public-suffix-list.yml
  .tx/backport
  renovate.json
Labels: 3. to review

#11178 Use html comments for recipientinfo and update code style for imip
  src/components/Imip.vue
  src/components/RecipientInfo.vue
Labels: 3. to review

#10945 feat: Allow user to control message view mode
  appinfo/routes.php
  lib/Contracts/IMailSearch.php
  lib/Controller/MessagesController.php
  lib/Controller/PageController.php
  lib/Controller/SettingsController.php
  lib/Db/MessageMapper.php
  lib/Listener/AccountSynchronizedThreadUpdaterListener.php
  lib/Service/Search/MailSearch.php
  lib/Service/Search/SearchQuery.php
  lib/Settings/AdminSettings.php
  src/components/AppSettingsMenu.vue
  src/components/Envelope.vue
  src/components/NavigationMailbox.vue
  src/components/Thread.vue
  src/components/settings/AdminSettings.vue
  src/directives/drag-and-drop/droppable-mailbox/droppable-mailbox.js
  src/init.js
  src/service/MessageService.js
  src/service/SettingsService.js
  src/store/mainStore/actions.js
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Service/Search/MailSearchTest.php
  tests/Unit/Settings/AdminSettingsTest.php
Labels: 3. to review

#11183 fix(ui): replace deprecated iframe resizer attribute
  lib/Http/HtmlResponse.php
Labels: 3. to review, technical debt

#11164 fix: html message alignment
  src/components/PhishingWarning.vue
Labels: bug, 2. developing, design, backport-request

#11190 fix: don't propagate click event on reply
  src/components/Message.vue
  src/components/ThreadEnvelope.vue
Labels: bug, 3. to review, backport-request

#11186 feat: start loading additional envelopes earlier
  src/components/MailboxThread.vue
Labels: enhancement, 3. to review

#11195 fix(smime): only accept certificates and keys in file input
  src/components/smime/SmimeCertificateModal.vue
Labels: enhancement, 3. to review, backport-request

#8215 save sign preference
  lib/Controller/PageController.php
  src/components/Composer.vue
  src/init.js
  tests/Unit/Controller/PageControllerTest.php
Labels: enhancement, 4. to release, backport-request, feature:smime

#11193 feat(composer): suggest recipients from own identities
  src/components/Composer.vue
Labels: enhancement, 3. to review
