Repository nextcloud/mail, pull requests merged in 2025-09, with the labels that each got.

#11603 [stable5.4] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#11602 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#11601 [stable5.3] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#11615 fix(deps): bump @nextcloud/vue to ^8.30.0
  jest.config.js
  package-lock.json
  package.json
  src/tests/jsdom-structured-clone-env.js
Labels: 3. to review, dependencies

#11621 fix: clear search icon should not be outline
  src/components/SearchMessages.vue
Labels: bug, 4. to release, design, backport-request

#11611 fix(ui): use fluid background image for the setup view
  css/fluid.scss
  src/components/NoMessageSelected.vue
  src/views/Setup.vue
Labels: bug, 4. to release, design, backport-request

#11624 feat(deps): Add Nextcloud 33 support
  appinfo/info.xml
Labels: enhancement, 4. to release

#11623 chore(CI): Adjust testing matrix for Nextcloud 32 on main
  .github/workflows/psalm-matrix.yml
  .github/workflows/test.yml
Labels: 4. to release

#11642 fix(AliasSettings): alignment
  src/components/AliasSettings.vue
Labels: 3. to review

#11676 [stable5.5] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 4. to release, dependencies

#11677 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#11694 fix: correct the default sort order value
  src/components/Mailbox.vue
Labels: bug, 4. to release, backport-request

#11705 [main] fix(deps): update @nextcloud/dialogs
  package-lock.json
Labels: 3. to review, dependencies

#11665 Fix CKEditor color in darkmode
  src/components/TextEditor.vue
Labels: bug, 3. to review

#11712 fix: check email in recipient picker
  src/components/Composer.vue
Labels: bug, 3. to review, backport-request

#11657 fix(deps): drop Nextcloud 30 support (EOL)
  .github/workflows/test.yml
  appinfo/info.xml
  lib/Listener/FollowUpClassifierListener.php
  lib/Listener/OptionalIndicesListener.php
  lib/Service/IMipService.php
  lib/Service/Provisioning/Manager.php
  lib/Settings/AdminSettings.php
  src/components/settings/ProvisioningSettings.vue
  tests/Unit/Listener/FollowUpClassifierListenerTest.php
  tests/Unit/Service/IMipServiceTest.php
Labels: 4. to release, dependencies

#11721 fix(quickaction): log js error to console
  src/components/quickActions/Settings.vue
Labels: bug, 3. to review, backport-request

#11724 refactor(quick-actions): use try catch
  src/components/quickActions/Settings.vue
Labels: 3. to review

#11715 refactor: Use modern way to insert entity in DB
  tests/Integration/Db/CollectedAddressMapperTest.php
Labels: 3. to review

#11633 fix: schedule repair sync job when adding an account
  lib/Migration/FixBackgroundJobs.php
  lib/Service/AccountService.php
  lib/Service/Provisioning/Manager.php
  tests/Unit/Service/AccountServiceTest.php
  tests/Unit/Service/Provisioning/ManagerTest.php
Labels: bug, 3. to review, backport-request

#11735 fix: allow reloading the INBOX favorites page
  appinfo/routes.php
  lib/Controller/PageController.php
Labels: bug, 3. to review, backport-request

#11745 fix(migration): check if account service method exists
  lib/Migration/FixBackgroundJobs.php
Labels: bug, 4. to release, backport-request

#11749 fix: display email actions tooltip correctly
  src/components/ThreadEnvelope.vue
Labels: backport-request

#11760 chore: bump version number
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#11762 fix(ui): use filled icons for active navigation mailboxes
  src/components/NavigationMailbox.vue
Labels: bug, 3. to review, backport-request

#11763 fix: mail pane resetting between layout changes
  src/components/MailboxThread.vue
  src/components/Outbox.vue
Labels: 4. to release
