Repository nextcloud/mail, pull requests merged in 2025-08, with the labels that each got.

#11436 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#11445 chore(styleint): make rtl checks error level
  src/directives/drag-and-drop/styles/draggable-envelope.scss
  stylelint.config.js
Labels: enhancement, 3. to review

#11446 fix(translation): respect llm admin setting
  lib/Controller/PageController.php
  tests/Unit/Controller/PageControllerTest.php
Labels: bug, 4. to release, backport-request

#11455 fix(ui): resize action icons from 16px to 20px
  src/components/ComposerSessionIndicator.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/MenuEnvelope.vue
  src/components/MessageAttachment.vue
  src/components/MessageHTMLBody.vue
  src/components/NavigationAccount.vue
  src/components/NavigationMailbox.vue
  src/components/NavigationOutbox.vue
  src/components/OutboxMessageListItem.vue
  src/components/TagModal.vue
  src/components/ThreadEnvelope.vue
  src/components/itinerary/CalendarImport.vue
Labels: 4. to release

#11457 fix(ui): resize button icons from 16px to 20px
  src/components/AccountForm.vue
  src/components/AliasForm.vue
  src/components/AliasSettings.vue
  src/components/AppSettingsMenu.vue
  src/components/Composer.vue
  src/components/EnvelopeList.vue
  src/components/MailboxPicker.vue
  src/components/MailboxThread.vue
  src/components/NewMessageButtonHeader.vue
  src/components/OutOfOfficeForm.vue
  src/components/RecipientBubble.vue
  src/components/SieveFilterForm.vue
  src/components/SignatureSettings.vue
  src/components/TagModal.vue
  src/components/ThreadSummary.vue
  src/components/mailFilter/CreateModal.vue
  src/components/mailFilter/UpdateModal.vue
  src/components/settings/AdminSettings.vue
  src/components/settings/AntiSpamSettings.vue
  src/components/settings/ProvisioningSettings.vue
  src/components/smime/SmimeCertificateModal.vue
  src/components/textBlocks/ListItem.vue
  src/components/textBlocks/TextBlockModal.vue
Labels: 3. to review, design

#11440 feat(ai-integration): detect if message needs translation
  appinfo/routes.php
  lib/Controller/MessagesController.php
  lib/Service/AiIntegrations/AiIntegrationsService.php
  src/components/Message.vue
  src/components/MessageHTMLBody.vue
  src/components/MessagePlainTextBody.vue
  src/components/NeedsTranslationInfo.vue
  src/components/ThreadEnvelope.vue
  src/components/TranslationModal.vue
  src/service/AiIntergrationsService.js
  tests/Unit/Controller/MessagesControllerTest.php
  tests/Unit/Service/AiIntegrationsServiceTest.php
Labels: enhancement, 4. to release

#11464 fix(ui): resize inline icons from 16px to 20px
  src/components/AppSettingsMenu.vue
  src/components/ComposerAttachment.vue
  src/components/ComposerAttachments.vue
  src/components/ComposerSessionIndicator.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/Imip.vue
  src/components/MailboxPicker.vue
  src/components/Message.vue
  src/components/MessageAttachments.vue
  src/components/Navigation.vue
  src/components/PhishingWarning.vue
  src/components/RecipientInfo.vue
  src/components/RecipientListItem.vue
  src/components/imip/EventData.vue
  src/components/textBlocks/ListItem.vue
Labels: bug, 4. to release, design

#11400 feat: make thread elements have the same space around them
  src/components/EnvelopeSkeleton.vue
  src/components/Message.vue
  src/components/Thread.vue
Labels: enhancement, 4. to release

#11510 [stable5.3] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#11518 fix: white space between section titles
  src/components/EnvelopeList.vue
  src/components/Mailbox.vue
Labels: bug, 3. to review, backport-request

#11517 fix: ckeditor dropdown overlaping
  src/components/NewMessageModal.vue
  src/components/RecipientInfo.vue
  src/components/TextEditor.vue
Labels: bug, 3. to review

#11528 fix(ui): revert recipient delete icon to filled variant
  src/components/RecipientListItem.vue
Labels: bug, 3. to review, backport-request, regression

#11536 fix(ui): revert composer session close icon to filled variant
  src/components/ComposerSessionIndicator.vue
Labels: bug, 3. to review, backport-request, regression

#11540 fix(ui): use gradient as fallback for themed fluid design
  src/components/NoMessageSelected.vue
Labels: bug, 3. to review, backport-request

#11356 fix: thread heading alignment and participants
  src/components/MailboxThread.vue
  src/components/Message.vue
  src/components/MessageHTMLBody.vue
  src/components/Thread.vue
Labels: bug, 3. to review, backport-request, design: review 🔍

#11554 fix EnvelopeSkeleton: make action hover area square again
  src/components/EnvelopeSkeleton.vue
Labels: 3. to review

#11560 fix(deps): bump sha.js from 2.4.11 to 2.4.12
  package-lock.json
Labels: bug, 3. to review, backport-request

#11570 ci: allow feats for main only
  .github/workflows/block-unconventional-commits.yml
Labels: 3. to review, backport-request

#11579 chore(deps): Update nextcloud/openapi-extractor to ^1.8.1
  lib/Controller/AccountApiController.php
  lib/Controller/MessageApiController.php
  lib/Db/AliasMapper.php
  lib/Db/MailAccountMapper.php
  lib/ResponseDefinitions.php
  lib/Service/AccountService.php
  lib/Service/AliasesService.php
  vendor-bin/openapi/composer.json
  vendor-bin/openapi/composer.lock
Labels: 3. to review, dependencies, php

#11585 Use material symbol variant of delete icon
  src/components/AliasForm.vue
  src/components/Composer.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/EnvelopeSingleClickActions.vue
  src/components/MailboxPicker.vue
  src/components/NavigationAccount.vue
  src/components/NavigationMailbox.vue
  src/components/OutboxMessageListItem.vue
  src/components/TagItem.vue
  src/components/ThreadEnvelope.vue
  src/components/mailFilter/Action.vue
  src/components/mailFilter/MailFilters.vue
  src/components/mailFilter/Test.vue
  src/components/settings/AntiSpamSettings.vue
  src/components/settings/ProvisioningSettings.vue
  src/components/smime/SmimeCertificateModal.vue
Labels: 3. to review, design, backport-request

#11590 [stable5.3] Use material symbol variant of delete icon
  src/components/AliasForm.vue
  src/components/Composer.vue
  src/components/Envelope.vue
  src/components/EnvelopeList.vue
  src/components/MailboxPicker.vue
  src/components/NavigationAccount.vue
  src/components/NavigationMailbox.vue
  src/components/OutboxMessageListItem.vue
  src/components/TagItem.vue
  src/components/ThreadEnvelope.vue
  src/components/mailFilter/Action.vue
  src/components/mailFilter/MailFilters.vue
  src/components/mailFilter/Test.vue
  src/components/settings/AntiSpamSettings.vue
  src/components/settings/ProvisioningSettings.vue
  src/components/smime/SmimeCertificateModal.vue
Labels: 3. to review, design

#11582 fix: update wording for mailvelope
  src/components/AppSettingsMenu.vue
Labels: bug, 3. to review

#11597 fix(ui): adapt setup page to fluid logo
  img/mail-fluid.svg
  img/mail-fluid.svg.license
  src/views/Setup.vue
Labels: bug, 3. to review, backport-request, comp:setup
