Repository nextcloud/mail, pull requests merged in 2025-03, with the labels that each got.

#10782 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10783 [stable4.2] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10781 [stable3.7] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10739 Thread: add error message for emails not able to be opened
  src/components/Thread.vue
Labels: 3. to review

#10787 Fix(deps): bump ckeditor from 37 to 38
  README.md
  package-lock.json
  package.json
  src/components/AppSettingsMenu.vue
  src/components/TextEditor.vue
Labels: 3. to review, dependencies

#10791 refactor: handle temporary files not being created gracefully
  lib/Service/SmimeService.php
Labels: 3. to review, technical debt

#10797 chore: update ical.js to 2.1.0
  package-lock.json
  package.json
  src/components/imip/EventData.vue
Labels: 3. to review, dependencies

#10802 fix(deps) Bump ckeditor from 38.1.1 t0 39.0.2
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#10817 chore(deps): bump ckeditor from 39.0.2 to 40.0.0
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#10821 fix(deps): bump ckeditor from v40 to v41
  package-lock.json
  package.json
  src/components/TextEditor.vue
Labels: 3. to review, dependencies

#10840 fix(deps): bump ckeditor v41 to v43
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#10835 ci(npmaudit): Run on stable4.3-stable3.7
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#10831 [stable4.3] fix: update ical.js and calendar-js
  package-lock.json
  package.json
  src/components/imip/EventData.vue
Labels: bug, 3. to review

#10839 fix(db): Catch message IDs that are too long
  lib/Db/MessageMapper.php
Labels: bug, 3. to review, backport-request

#10674 fix: user must scroll to view most recent message in thread
  src/components/ThreadEnvelope.vue
Labels: bug, 3. to review, backport-request

#10860 fix: import for getTimezoneManager
  src/components/EventModal.vue
Labels: bug, 3. to review, backport-request

#10859 refactor: update imports for nextcloud/vue 9
  src/components/Avatar.vue
  src/components/Composer.vue
  src/components/EmptyMailbox.vue
  src/components/EmptyMailboxSection.vue
  src/components/Error.vue
  src/components/MenuEnvelope.vue
  src/components/NewMessageButtonHeader.vue
  src/components/OutboxMessageContent.vue
  src/components/SearchMessages.vue
  src/components/TextEditor.vue
  src/components/ThreadEnvelope.vue
  src/components/ThreadSummary.vue
  src/components/mailFilter/ActionFileinto.vue
  src/components/settings/AdminSettings.vue
  src/components/settings/AntiSpamSettings.vue
  src/components/settings/ProvisioningSettings.vue
  src/views/OauthDone.vue
Labels: 3. to review, technical debt

#10853 [stable4.2] fix: update ical.js and calendar-js
  package-lock.json
  package.json
  src/components/EventModal.vue
  src/components/imip/EventData.vue
Labels: bug, 3. to review

#10863 fix: do not force the SAB
  lib/Controller/ContactIntegrationController.php
  lib/Service/ContactIntegration/ContactIntegrationService.php
  lib/Service/ContactsIntegration.php
  lib/Service/PhishingDetection/ContactCheck.php
  src/components/TextEditor.vue
  src/service/ContactIntegrationService.js
  tests/Integration/Service/Phishing/PhishingDetectionServiceIntegrationTest.php
  tests/Unit/Service/Phishing/ContactCheckTest.php
Labels: bug, 3. to review, backport-request

#10862 feat: add warning when you try to send a new message that has no subject
  src/components/NewMessageModal.vue
  src/errors/SubjectMissingError.js
Labels: enhancement, 3. to review

#10851 fix: allow to send attachment without setting filename
  lib/Provider/Command/MessageSend.php
  lib/Service/TransmissionService.php
Labels: 3. to review, backport-request

#10858 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10822 fix(imap): Sync mailboxes without a status
  lib/IMAP/MailboxSync.php
  tests/Unit/IMAP/MailboxSyncTest.php
Labels: bug, backport-request

#10833 fix: shorten ai summaries to fit in message list better
  lib/Service/AiIntegrations/AiIntegrationsService.php
Labels: 3. to review, backport-request

#10874 fix(db): Allow long references
  lib/Db/MessageMapper.php
Labels: bug, 3. to review, backport-request, regression

#10879 ci: Automate pre-releases
  .github/workflows/appstore-conventional-build-publish.yml
Labels: 3. to review

#10848 fix: reloading recipeint info when you expand and collapse the composer
  src/components/NewMessageModal.vue
Labels: bug, 3. to review, backport-request

#10892 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10893 [stable3.7] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10895 [stable4.2] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10901 fix(CKEditor): show mentions
  src/components/TextEditor.vue
Labels: bug, 3. to review, backport-request, regression

#10903 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10857 fix(deps): Apply npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#10899 fix(deps): bump ckeditor v43 to latest
  package-lock.json
  package.json
  src/components/TextEditor.vue
  src/tests/unit/components/MailPlugin.spec.js
  src/tests/unit/components/PickerPlugin.vue.spec.js
  src/tests/unit/components/QuotePlugin.spec.js
  src/tests/unit/components/SignaturePlugin.spec.js
  src/tests/unit/components/TextEditor.spec.js
Labels: 3. to review, dependencies

#10904 fix: go back warning discards the reply text
  src/components/NewMessageModal.vue
Labels: bug, 4. to release, backport-request

#10920 feat(deps): Add PHP8.4 support
  .github/workflows/test.yml
  appinfo/info.xml
Labels: 4. to release, dependencies

#10696 fix(imap): Avoid OOM when syncing sparse mailboxes
  lib/IMAP/MessageMapper.php
  tests/Unit/IMAP/MessageMapperTest.php
Labels: bug, 3. to review, backport-request

#10933 fix: dont summerize empty messages
  lib/Service/AiIntegrations/AiIntegrationsService.php
  tests/Unit/Service/AiIntegrationsServiceTest.php
Labels: 3. to review, backport-request

#10670 Fix text cutting off when printing and differences between clicking print and doing ctrl + P
  package-lock.json
  package.json
  src/components/MenuEnvelope.vue
  src/components/MessageHTMLBody.vue
  src/components/Thread.vue
  src/components/ThreadEnvelope.vue
  src/html-response.js
Labels: 3. to review
