Repository nextcloud/mail, pull requests merged in 2025-02, with the labels that each got.

#10647 fix: decoding preview texts
  lib/IMAP/MessageMapper.php
Labels: bug, 4. to release, backport-request

#10641 fix: outbox message not being cleared after retry
  lib/Service/MailTransmission.php
Labels: backport-request

#10654 [stable3.7] fix: outbox message not being cleared after retry
  lib/Service/MailTransmission.php
Labels: 3. to review

#10657 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#10661 fix: detect imip messages from outlook.com
  REUSE.toml
  lib/IMAP/MessageMapper.php
  tests/Unit/IMAP/MessageMapperTest.php
  tests/data/imip/request_google.txt
  tests/data/imip/request_outlook_com.txt
Labels: 3. to review

#10673 fix: reset filter does not work
  src/components/SearchMessages.vue
Labels: bug, 3. to review, backport-request

#10659 feat: check connection performance of mail service
  lib/AppInfo/Application.php
  lib/Db/MailAccountMapper.php
  lib/Db/ProvisioningMapper.php
  lib/SetupChecks/MailConnectionPerformance.php
  lib/SetupChecks/MicroTime.php
  tests/Integration/Db/ProvisioningMapperTest.php
  tests/Unit/SetupChecks/MailConnectionPerformanceTest.php
Labels: 3. to review

#10683 fix: always show email address for suggestions from address collector
  src/components/Composer.vue
Labels: bug, 3. to review, backport-request

#10689 fix: recipient label should not contain email address
  lib/Service/AutoCompletion/AutoCompleteService.php
  lib/Service/ContactsIntegration.php
  lib/Service/GroupsIntegration.php
  src/components/Composer.vue
  tests/Unit/Service/Autocompletion/AutoCompleteServiceTest.php
  tests/Unit/Service/ContactsIntegrationTest.php
  tests/Unit/Service/GroupsIntegrationTest.php
Labels: bug, 3. to review, backport-request

#10694 fix: change status code from 404 to 204 for missing avatars
  lib/Controller/AvatarsController.php
  tests/Unit/Controller/AvatarControllerTest.php
Labels: bug, 3. to review

#10643 [main] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10568 [stable3.7] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10543 [stable4.1] fix(dns): Update public suffix list
  resources/public_suffix_list.dat
Labels: 3. to review, dependencies

#10706 fix(deps): Do not ship psr/log
  .github/workflows/test.yml
  REUSE.toml
  composer.json
  composer.lock
  psalm.xml
  vendor-bin/psalm-stubs/composer.json
  vendor-bin/psalm-stubs/composer.lock
Labels: bug, 3. to review, backport-request, dependencies

#10728 fix: handle 204 response
  src/service/AvatarService.js
Labels: bug, 3. to review, backport-request

#10710 ci: Do not force-enable the app
  .github/workflows/test.yml
Labels: 4. to release

#10760 fix: harden phishing detection against missing and malformed headers
  lib/Service/PhishingDetection/DateCheck.php
  lib/Service/PhishingDetection/PhishingDetectionService.php
  tests/Unit/Service/Phishing/PhishingDetectionServiceTest.php
  tests/data/phishing-mail-headers.malformed-date.txt
  tests/data/phishing-mail-headers.malformed-date.txt.license
  tests/data/phishing-mail-headers.no-date.txt
  tests/data/phishing-mail-headers.no-date.txt.license
  tests/data/phishing-mail-headers.no-from.txt
  tests/data/phishing-mail-headers.no-from.txt.license
  tests/data/phishing-mail-headers.no-reply-to.txt
  tests/data/phishing-mail-headers.no-reply-to.txt.license
Labels: bug, 3. to review, backport-request

#10761 Fixes "Uninitialized string offset" error
  lib/Service/PhishingDetection/LinkCheck.php
Labels: bug, 3. to review, backport-request

#10763 fix: html5 tag errors
  lib/Service/MimeMessage.php
Labels: 3. to review, backport-request

#10767 Set license for changelog.md
  CHANGELOG.md
  CHANGELOG.md.license
Labels: 4. to release, backport-request

#10771 fix: handle utf-8 strings correctly in the link detection
  lib/Service/PhishingDetection/LinkCheck.php
  tests/Unit/Service/Phishing/LinkCheckTest.php
Labels: bug, 3. to review, backport-request

#10776 fix: remove photo property from groups integration
  lib/Service/GroupsIntegration.php
  tests/Unit/Service/GroupsIntegrationTest.php
Labels: bug, 3. to review, backport-request

#10779 chore: better help text when sieve is not enabled
  src/components/AccountSettings.vue
Labels: bug, 4. to release, backport-request
